/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package grafica;

import java.awt.Color;
import java.awt.Font;
import java.io.IOException;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import logica.Producto;
import logica.Sistema;
import logica.Usuario;

/**
 *
 * @author Franco
 */
public class Almacen extends javax.swing.JFrame {

    int xMouse, yMouse;
    Usuario usuario;
    DefaultTableModel modelo = new DefaultTableModel();

    public Almacen() throws ClassNotFoundException, SQLException, IOException {
        initComponents();
        this.setLocationRelativeTo(null);
        txtProducto.setEnabled(false);
        txtPrecioKg.requestFocus();
        tbeListado_Productos.setModel(Sistema.getInstance().mostrarListadoProductos());
        tbeListado_Productos.setBackground(Color.white);
        tbeListado_Productos.getTableHeader().setFont(new Font("Seoge UI", Font.BOLD, 12));
        tbeListado_Productos.getTableHeader().setOpaque(false);
        tbeListado_Productos.getTableHeader().setBackground(new Color(32, 136, 203));
        tbeListado_Productos.getTableHeader().setForeground(new Color(0, 0, 0));
        Sistema.getInstance().llenarComboBoxSuministrador(cboSuministrador);

        modelo.addColumn("ID");
        modelo.addColumn("Producto");
        modelo.addColumn("Cantidad");
        modelo.addColumn("Precio");
        tbeDetalleCompra.setModel(modelo);        
    }

    public Almacen(Usuario usuario) throws ClassNotFoundException, SQLException, IOException {
        initComponents();
        this.setLocationRelativeTo(null);
        txtProducto.setEnabled(false);
        txtPrecioKg.requestFocus();
        tbeListado_Productos.setModel(Sistema.getInstance().mostrarListadoProductos());
        tbeListado_Productos.setBackground(Color.white);
        tbeListado_Productos.getTableHeader().setFont(new Font("Seoge UI", Font.BOLD, 12));
        tbeListado_Productos.getTableHeader().setOpaque(false);
        tbeListado_Productos.getTableHeader().setBackground(new Color(32, 136, 203));
        tbeListado_Productos.getTableHeader().setForeground(new Color(0, 0, 0));
        Sistema.getInstance().llenarComboBoxSuministrador(cboSuministrador);

        modelo.addColumn("ID");
        modelo.addColumn("Producto");
        modelo.addColumn("Cantidad");
        modelo.addColumn("Precio");
        tbeDetalleCompra.setModel(modelo);
        this.usuario = usuario;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        BarraTitulo = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        btnExit = new javax.swing.JPanel();
        txtExit = new javax.swing.JLabel();
        lblIcono2 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        lblTitulo4 = new javax.swing.JLabel();
        RegistroUsuario = new javax.swing.JPanel();
        txtNumeroFactura = new javax.swing.JTextField();
        txtProducto = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtPrecioKg = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtCantidad = new javax.swing.JTextField();
        lblTotal = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        cboSuministrador = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbeListado_Productos = new javax.swing.JTable();
        lblTitulo5 = new javax.swing.JLabel();
        btnBuscar = new javax.swing.JPanel();
        lblBuscar = new javax.swing.JLabel();
        btnVerTodos = new javax.swing.JPanel();
        lblVerTodos = new javax.swing.JLabel();
        btnSeleccionar = new javax.swing.JPanel();
        lblSeleccionar = new javax.swing.JLabel();
        btnAgregar = new javax.swing.JPanel();
        lblAgregar = new javax.swing.JLabel();
        btnCancelarSeleccion = new javax.swing.JPanel();
        lblCancelarSeleccion = new javax.swing.JLabel();
        jDateFecha = new com.toedter.calendar.JDateChooser();
        jLabel8 = new javax.swing.JLabel();
        btnConfirmarCompra = new javax.swing.JPanel();
        lblConfirmarCompra = new javax.swing.JLabel();
        btnCancelarCompra = new javax.swing.JPanel();
        lblCancelarCompra = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbeDetalleCompra = new javax.swing.JTable();
        btnEliminarProducto = new javax.swing.JPanel();
        lblEliminarProducto = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        lblRegistrar2 = new javax.swing.JLabel();
        txtBuscador = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btnAtras = new javax.swing.JPanel();
        lblAtras = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(610, 819));
        setMinimumSize(new java.awt.Dimension(610, 819));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(610, 819));
        setResizable(false);
        setSize(new java.awt.Dimension(610, 819));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(231, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BarraTitulo.setBackground(new java.awt.Color(231, 255, 255));
        BarraTitulo.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                BarraTituloMouseDragged(evt);
            }
        });
        BarraTitulo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BarraTituloMousePressed(evt);
            }
        });
        BarraTitulo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitulo.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(153, 153, 153));
        lblTitulo.setText("Almacén - Compras y Stock");
        BarraTitulo.add(lblTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 8, -1, -1));

        btnExit.setBackground(new java.awt.Color(231, 255, 255));
        btnExit.setForeground(new java.awt.Color(255, 255, 255));
        btnExit.setMaximumSize(new java.awt.Dimension(30, 30));
        btnExit.setMinimumSize(new java.awt.Dimension(30, 30));
        btnExit.setPreferredSize(new java.awt.Dimension(30, 30));
        btnExit.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtExit.setBackground(new java.awt.Color(51, 51, 51));
        txtExit.setFont(new java.awt.Font("Roboto Light", 1, 24)); // NOI18N
        txtExit.setForeground(new java.awt.Color(0, 0, 0));
        txtExit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtExit.setText("X");
        txtExit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtExitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtExitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtExitMouseExited(evt);
            }
        });
        btnExit.add(txtExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 35, 30));

        BarraTitulo.add(btnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(575, 0, 35, 30));

        lblIcono2.setBackground(new java.awt.Color(51, 51, 51));
        lblIcono2.setFont(new java.awt.Font("Roboto Light", 1, 24)); // NOI18N
        lblIcono2.setForeground(new java.awt.Color(0, 0, 0));
        lblIcono2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblIcono2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/grafica/Imagenes/Icono 15px.png"))); // NOI18N
        lblIcono2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        BarraTitulo.add(lblIcono2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 35, 30));

        jPanel1.add(BarraTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 610, 30));

        jPanel7.setBackground(new java.awt.Color(21, 47, 62));

        lblTitulo4.setBackground(new java.awt.Color(0, 0, 0));
        lblTitulo4.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        lblTitulo4.setForeground(new java.awt.Color(255, 255, 255));
        lblTitulo4.setText("Gestión de Compras y Stock");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 610, Short.MAX_VALUE)
            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel7Layout.createSequentialGroup()
                    .addGap(0, 151, Short.MAX_VALUE)
                    .addComponent(lblTitulo4)
                    .addGap(0, 152, Short.MAX_VALUE)))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel7Layout.createSequentialGroup()
                    .addGap(0, 5, Short.MAX_VALUE)
                    .addComponent(lblTitulo4)
                    .addGap(0, 6, Short.MAX_VALUE)))
        );

        jPanel1.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 610, 40));

        RegistroUsuario.setBackground(new java.awt.Color(21, 47, 62));
        RegistroUsuario.setForeground(new java.awt.Color(204, 204, 204));
        RegistroUsuario.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        RegistroUsuario.add(txtNumeroFactura, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 320, 70, -1));
        RegistroUsuario.add(txtProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 400, 150, -1));

        jLabel3.setFont(new java.awt.Font("Roboto Light", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(4, 224, 190));
        jLabel3.setText("Producto:");
        RegistroUsuario.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 400, -1, 20));

        jLabel5.setFont(new java.awt.Font("Roboto Light", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(4, 224, 190));
        jLabel5.setText("Nº Fact/Bol:");
        RegistroUsuario.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, -1, 20));
        RegistroUsuario.add(txtPrecioKg, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 400, 80, -1));

        jLabel6.setFont(new java.awt.Font("Roboto Light", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(4, 224, 190));
        jLabel6.setText("Precio Kg:");
        RegistroUsuario.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 400, -1, 20));
        RegistroUsuario.add(txtCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 400, 80, -1));

        lblTotal.setFont(new java.awt.Font("Roboto Light", 1, 12)); // NOI18N
        lblTotal.setForeground(new java.awt.Color(255, 255, 255));
        lblTotal.setText("Total: $ 0.0");
        RegistroUsuario.add(lblTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 610, -1, 20));

        jLabel10.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(4, 224, 190));
        jLabel10.setText("Suministrador:");
        RegistroUsuario.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, -1, 20));

        RegistroUsuario.add(cboSuministrador, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 360, 320, 25));

        tbeListado_Productos.setBackground(new java.awt.Color(255, 255, 255));
        tbeListado_Productos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tbeListado_Productos.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tbeListado_Productos.setFocusable(false);
        tbeListado_Productos.setRowHeight(23);
        tbeListado_Productos.setSelectionBackground(new java.awt.Color(204, 28, 66));
        tbeListado_Productos.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tbeListado_Productos);

        RegistroUsuario.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 550, 160));

        lblTitulo5.setBackground(new java.awt.Color(0, 0, 0));
        lblTitulo5.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        lblTitulo5.setForeground(new java.awt.Color(255, 255, 255));
        lblTitulo5.setText("* Busque el producto y presione \"Seleccionar\"");
        RegistroUsuario.add(lblTitulo5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        btnBuscar.setBackground(new java.awt.Color(255, 77, 123));

        lblBuscar.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        lblBuscar.setForeground(new java.awt.Color(255, 255, 255));
        lblBuscar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/grafica/Imagenes/icons8_search_20px.png"))); // NOI18N
        lblBuscar.setText("BUSCAR");
        lblBuscar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblBuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblBuscarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblBuscarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblBuscarMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnBuscarLayout = new javax.swing.GroupLayout(btnBuscar);
        btnBuscar.setLayout(btnBuscarLayout);
        btnBuscarLayout.setHorizontalGroup(
            btnBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );
        btnBuscarLayout.setVerticalGroup(
            btnBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        RegistroUsuario.add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 40, 100, 40));

        btnVerTodos.setBackground(new java.awt.Color(255, 77, 123));

        lblVerTodos.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        lblVerTodos.setForeground(new java.awt.Color(255, 255, 255));
        lblVerTodos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblVerTodos.setText("Ver Todos");
        lblVerTodos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblVerTodos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblVerTodosMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblVerTodosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblVerTodosMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnVerTodosLayout = new javax.swing.GroupLayout(btnVerTodos);
        btnVerTodos.setLayout(btnVerTodosLayout);
        btnVerTodosLayout.setHorizontalGroup(
            btnVerTodosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblVerTodos, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );
        btnVerTodosLayout.setVerticalGroup(
            btnVerTodosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblVerTodos, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        RegistroUsuario.add(btnVerTodos, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 40, 100, 40));

        btnSeleccionar.setBackground(new java.awt.Color(255, 77, 123));

        lblSeleccionar.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        lblSeleccionar.setForeground(new java.awt.Color(255, 255, 255));
        lblSeleccionar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSeleccionar.setText("Seleccionar");
        lblSeleccionar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblSeleccionar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblSeleccionarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblSeleccionarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblSeleccionarMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnSeleccionarLayout = new javax.swing.GroupLayout(btnSeleccionar);
        btnSeleccionar.setLayout(btnSeleccionarLayout);
        btnSeleccionarLayout.setHorizontalGroup(
            btnSeleccionarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblSeleccionar, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
        );
        btnSeleccionarLayout.setVerticalGroup(
            btnSeleccionarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblSeleccionar, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        RegistroUsuario.add(btnSeleccionar, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 270, 80, 30));

        btnAgregar.setBackground(new java.awt.Color(3, 190, 161));

        lblAgregar.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        lblAgregar.setForeground(new java.awt.Color(255, 255, 255));
        lblAgregar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAgregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/grafica/Imagenes/icons8_add_15px.png"))); // NOI18N
        lblAgregar.setText("Agregar a la lista");
        lblAgregar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblAgregar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblAgregarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblAgregarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblAgregarMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnAgregarLayout = new javax.swing.GroupLayout(btnAgregar);
        btnAgregar.setLayout(btnAgregarLayout);
        btnAgregarLayout.setHorizontalGroup(
            btnAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblAgregar, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
        );
        btnAgregarLayout.setVerticalGroup(
            btnAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblAgregar, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        RegistroUsuario.add(btnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 460, 130, 30));

        btnCancelarSeleccion.setBackground(new java.awt.Color(255, 77, 123));

        lblCancelarSeleccion.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        lblCancelarSeleccion.setForeground(new java.awt.Color(255, 255, 255));
        lblCancelarSeleccion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCancelarSeleccion.setText("Cancelar");
        lblCancelarSeleccion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblCancelarSeleccion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCancelarSeleccionMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblCancelarSeleccionMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblCancelarSeleccionMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnCancelarSeleccionLayout = new javax.swing.GroupLayout(btnCancelarSeleccion);
        btnCancelarSeleccion.setLayout(btnCancelarSeleccionLayout);
        btnCancelarSeleccionLayout.setHorizontalGroup(
            btnCancelarSeleccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblCancelarSeleccion, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
        );
        btnCancelarSeleccionLayout.setVerticalGroup(
            btnCancelarSeleccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblCancelarSeleccion, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        RegistroUsuario.add(btnCancelarSeleccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 270, 80, 30));

        jDateFecha.setBackground(new java.awt.Color(21, 47, 62));
        RegistroUsuario.add(jDateFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 320, 130, -1));

        jLabel8.setFont(new java.awt.Font("Roboto Light", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(4, 224, 190));
        jLabel8.setText("Fecha:");
        RegistroUsuario.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 320, -1, 20));

        btnConfirmarCompra.setBackground(new java.awt.Color(255, 77, 123));

        lblConfirmarCompra.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        lblConfirmarCompra.setForeground(new java.awt.Color(255, 255, 255));
        lblConfirmarCompra.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblConfirmarCompra.setText("Confirmar Compra");
        lblConfirmarCompra.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblConfirmarCompra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblConfirmarCompraMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblConfirmarCompraMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblConfirmarCompraMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnConfirmarCompraLayout = new javax.swing.GroupLayout(btnConfirmarCompra);
        btnConfirmarCompra.setLayout(btnConfirmarCompraLayout);
        btnConfirmarCompraLayout.setHorizontalGroup(
            btnConfirmarCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblConfirmarCompra, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
        );
        btnConfirmarCompraLayout.setVerticalGroup(
            btnConfirmarCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblConfirmarCompra, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        RegistroUsuario.add(btnConfirmarCompra, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 640, 120, 30));

        btnCancelarCompra.setBackground(new java.awt.Color(255, 77, 123));

        lblCancelarCompra.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        lblCancelarCompra.setForeground(new java.awt.Color(255, 255, 255));
        lblCancelarCompra.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCancelarCompra.setText("Cancelar");
        lblCancelarCompra.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblCancelarCompra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCancelarCompraMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblCancelarCompraMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblCancelarCompraMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnCancelarCompraLayout = new javax.swing.GroupLayout(btnCancelarCompra);
        btnCancelarCompra.setLayout(btnCancelarCompraLayout);
        btnCancelarCompraLayout.setHorizontalGroup(
            btnCancelarCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblCancelarCompra, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
        );
        btnCancelarCompraLayout.setVerticalGroup(
            btnCancelarCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblCancelarCompra, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        RegistroUsuario.add(btnCancelarCompra, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 640, 120, 30));

        jLabel9.setFont(new java.awt.Font("Roboto Light", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(4, 224, 190));
        jLabel9.setText("Cantidad Kg:");
        RegistroUsuario.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 400, -1, 20));

        jPanel4.setBackground(new java.awt.Color(4, 224, 190));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 550, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2, Short.MAX_VALUE)
        );

        RegistroUsuario.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 605, 550, 2));

        tbeDetalleCompra.setBackground(new java.awt.Color(255, 255, 255));
        tbeDetalleCompra.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Producto", "Cantidad", "Precio"
            }
        ));
        tbeDetalleCompra.setFocusable(false);
        tbeDetalleCompra.setRowHeight(23);
        tbeDetalleCompra.setSelectionBackground(new java.awt.Color(204, 28, 66));
        tbeDetalleCompra.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(tbeDetalleCompra);

        RegistroUsuario.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 510, 550, 90));

        btnEliminarProducto.setBackground(new java.awt.Color(255, 77, 123));

        lblEliminarProducto.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        lblEliminarProducto.setForeground(new java.awt.Color(255, 255, 255));
        lblEliminarProducto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEliminarProducto.setText("Eliminar Producto");
        lblEliminarProducto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblEliminarProducto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblEliminarProductoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblEliminarProductoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblEliminarProductoMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnEliminarProductoLayout = new javax.swing.GroupLayout(btnEliminarProducto);
        btnEliminarProducto.setLayout(btnEliminarProductoLayout);
        btnEliminarProductoLayout.setHorizontalGroup(
            btnEliminarProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblEliminarProducto, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
        );
        btnEliminarProductoLayout.setVerticalGroup(
            btnEliminarProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblEliminarProducto, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        RegistroUsuario.add(btnEliminarProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 640, 120, 30));

        jPanel10.setBackground(new java.awt.Color(4, 224, 190));

        lblRegistrar2.setBackground(new java.awt.Color(255, 126, 164));
        lblRegistrar2.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        lblRegistrar2.setForeground(new java.awt.Color(255, 255, 255));
        lblRegistrar2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRegistrar2.setText("REGISTRO de COMPRA / ACTUALIZAR STOCK");
        lblRegistrar2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lblRegistrar2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblRegistrar2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblRegistrar2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblRegistrar2MouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblRegistrar2, javax.swing.GroupLayout.DEFAULT_SIZE, 590, Short.MAX_VALUE)
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblRegistrar2, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        RegistroUsuario.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 590, 30));

        txtBuscador.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txtBuscador.setForeground(new java.awt.Color(204, 204, 204));
        txtBuscador.setText("Buscar...");
        txtBuscador.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtBuscadorMousePressed(evt);
            }
        });
        RegistroUsuario.add(txtBuscador, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 45, 180, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/grafica/Imagenes/icons8_search_20px.png"))); // NOI18N
        RegistroUsuario.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        btnAtras.setBackground(new java.awt.Color(42, 72, 89));

        lblAtras.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        lblAtras.setForeground(new java.awt.Color(255, 255, 255));
        lblAtras.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAtras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/grafica/Imagenes/icons8_left_20px.png"))); // NOI18N
        lblAtras.setText("ATRÁS");
        lblAtras.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblAtras.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblAtrasMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblAtrasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblAtrasMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnAtrasLayout = new javax.swing.GroupLayout(btnAtras);
        btnAtras.setLayout(btnAtrasLayout);
        btnAtrasLayout.setHorizontalGroup(
            btnAtrasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblAtras, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
        );
        btnAtrasLayout.setVerticalGroup(
            btnAtrasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblAtras, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
        );

        RegistroUsuario.add(btnAtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 680, -1, -1));

        jPanel1.add(RegistroUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 590, 730));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 610, 820));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtExitMouseClicked
        MenuAdministrador menu = new MenuAdministrador(usuario);
        menu.setVisible(true);
        dispose();
    }//GEN-LAST:event_txtExitMouseClicked

    private void txtExitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtExitMouseEntered
        btnExit.setBackground(new Color(230, 0, 0));
        txtExit.setForeground(Color.white);
    }//GEN-LAST:event_txtExitMouseEntered

    private void txtExitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtExitMouseExited
        btnExit.setBackground(new Color(231, 255, 255));
        txtExit.setForeground(Color.black);
    }//GEN-LAST:event_txtExitMouseExited

    private void BarraTituloMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BarraTituloMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_BarraTituloMouseDragged

    private void BarraTituloMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BarraTituloMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_BarraTituloMousePressed

    private void lblBuscarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBuscarMouseClicked
        String buscar = null;
        if (txtBuscador.getText().isEmpty() || txtBuscador.getText().equals("Buscar...")) {
            JOptionPane.showMessageDialog(this, "Ingrese el producto que desea buscar.");
        } else {

            buscar = "%" + txtBuscador.getText() + "%";
            try {
                tbeListado_Productos.setModel(Sistema.getInstance().buscarProductos(buscar));
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(Almacen.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(Almacen.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(Almacen.class.getName()).log(Level.SEVERE, null, ex);
            }

        }
    }//GEN-LAST:event_lblBuscarMouseClicked

    private void lblBuscarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBuscarMouseEntered
        btnBuscar.setBackground(new Color(255, 147, 178));
    }//GEN-LAST:event_lblBuscarMouseEntered

    private void lblBuscarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBuscarMouseExited
        btnBuscar.setBackground(new Color(255, 77, 123));
    }//GEN-LAST:event_lblBuscarMouseExited

    private void txtBuscadorMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtBuscadorMousePressed
        if (txtBuscador.getText().equals("Buscar...")) {
            txtBuscador.setText("");
            txtBuscador.setForeground(Color.black);
        }
    }//GEN-LAST:event_txtBuscadorMousePressed

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        if (txtBuscador.getText().isEmpty()) {
            txtBuscador.setText("Buscar...");
            txtBuscador.setForeground(new Color(204, 204, 204));
        }
    }//GEN-LAST:event_formMouseClicked

    private void lblVerTodosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblVerTodosMouseClicked
        try {
            tbeListado_Productos.setModel(Sistema.getInstance().mostrarListadoProductos());
            txtBuscador.setText("Buscar...");
            txtBuscador.setForeground(new Color(204, 204, 204));
            txtProducto.requestFocus();;
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Almacen.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Almacen.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(Almacen.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_lblVerTodosMouseClicked

    private void lblVerTodosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblVerTodosMouseEntered
        btnVerTodos.setBackground(new Color(255, 147, 178));
    }//GEN-LAST:event_lblVerTodosMouseEntered

    private void lblVerTodosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblVerTodosMouseExited
        btnVerTodos.setBackground(new Color(255, 77, 123));
    }//GEN-LAST:event_lblVerTodosMouseExited

    private void lblSeleccionarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSeleccionarMouseClicked

        int filaSeleccionada = tbeListado_Productos.getSelectedRow();

        if (filaSeleccionada == -1) {
            JOptionPane.showMessageDialog(this, "Seleccione un producto");
        } else {
            tbeListado_Productos.setEnabled(false);
            txtProducto.setText(String.valueOf(tbeListado_Productos.getValueAt(filaSeleccionada, 1)));

        }
    }//GEN-LAST:event_lblSeleccionarMouseClicked

    private void lblSeleccionarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSeleccionarMouseEntered
        btnSeleccionar.setBackground(new Color(255, 147, 178));
    }//GEN-LAST:event_lblSeleccionarMouseEntered

    private void lblSeleccionarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSeleccionarMouseExited
        btnSeleccionar.setBackground(new Color(255, 77, 123));
    }//GEN-LAST:event_lblSeleccionarMouseExited

    private void lblAgregarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAgregarMouseClicked

        String idProducto = null;
        String producto = null;
        double precio = 0;
        double totalProducto = 0;
        int cantidad = 0;
        double sumaTotal = 0;

        if (!txtPrecioKg.getText().matches("[0-9]+.?[0-9]+") || txtPrecioKg.getText().isEmpty() || Double.parseDouble(txtPrecioKg.getText()) <= 0) {
            JOptionPane.showMessageDialog(this, "Digite un precio válido");
        } else if (!txtCantidad.getText().matches("[0-9]+") || txtPrecioKg.getText().isEmpty() || Double.parseDouble(txtCantidad.getText()) <= 0) {
            JOptionPane.showMessageDialog(this, "Digite una cantidad válida");
        } else {
            int filaSeleccionada = tbeListado_Productos.getSelectedRow();
            idProducto = String.valueOf(tbeListado_Productos.getValueAt(filaSeleccionada, 0));
            producto = String.valueOf(tbeListado_Productos.getValueAt(filaSeleccionada, 1));
            cantidad = Integer.parseInt(txtCantidad.getText());
            precio = Double.parseDouble(txtPrecioKg.getText());
            totalProducto = precio * cantidad;
            double sumar = 0;
            String agregarProducto[] = new String[4];
            agregarProducto[0] = idProducto;
            agregarProducto[1] = producto;
            agregarProducto[2] = txtCantidad.getText();
            agregarProducto[3] = String.valueOf(totalProducto);
            modelo.addRow(agregarProducto);

            if (tbeDetalleCompra.getRowCount() > 0) {
                for (int i = 0; i < tbeDetalleCompra.getRowCount(); i++) {
                    sumar = Double.parseDouble((String) tbeDetalleCompra.getValueAt(i, 3));
                    sumaTotal += sumar;
                }
            }
            lblTotal.setText("Total: $" + sumaTotal);
            tbeListado_Productos.setEnabled(true);
        }
    }//GEN-LAST:event_lblAgregarMouseClicked

    private void lblAgregarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAgregarMouseEntered
        btnAgregar.setBackground(new Color(4, 224, 190));
    }//GEN-LAST:event_lblAgregarMouseEntered

    private void lblAgregarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAgregarMouseExited
        btnAgregar.setBackground(new Color(3, 190, 161));
    }//GEN-LAST:event_lblAgregarMouseExited

    private void lblCancelarSeleccionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCancelarSeleccionMouseClicked
        tbeListado_Productos.setEnabled(true);
        txtProducto.setText("");
        txtCantidad.setText("");
        txtPrecioKg.setText("");
    }//GEN-LAST:event_lblCancelarSeleccionMouseClicked

    private void lblCancelarSeleccionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCancelarSeleccionMouseEntered
        btnCancelarSeleccion.setBackground(new Color(255, 147, 178));
    }//GEN-LAST:event_lblCancelarSeleccionMouseEntered

    private void lblCancelarSeleccionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCancelarSeleccionMouseExited
        btnCancelarSeleccion.setBackground(new Color(255, 77, 123));
    }//GEN-LAST:event_lblCancelarSeleccionMouseExited

    private void lblConfirmarCompraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblConfirmarCompraMouseClicked
        SimpleDateFormat formatoFecha = new SimpleDateFormat("YYYY-MM-dd");
        String fecha = "";
        String numeroFactura = null;
        String idSuministrador = null;
        String idProducto = null;
        double precioKg = 0;
        double cantidad = 0;

        if (tbeDetalleCompra.getRowCount() > 0) {
            try {
                fecha = formatoFecha.format(jDateFecha.getDate());
            } catch (NullPointerException e) {
                JOptionPane.showMessageDialog(this, "Seleccione una fecha");
            }
        }
        if (tbeDetalleCompra.getRowCount() == 0) {
            JOptionPane.showMessageDialog(this, "La lista no puede estar vacía");
        } else if (txtNumeroFactura.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Ingrese el número de Factura/Boleta");
        } else if (cboSuministrador.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(this, "Seleccione un suministrador");
        } else {
            Producto productos[] = new Producto[tbeDetalleCompra.getRowCount()];
            if (tbeDetalleCompra.getRowCount() > 0) {
                for (int i = 0; i < tbeDetalleCompra.getRowCount(); i++) {
                    idProducto = (String) tbeDetalleCompra.getValueAt(i, 0);
                    cantidad = Double.parseDouble((String) tbeDetalleCompra.getValueAt(i, 2));
                    precioKg = (Double.parseDouble((String) tbeDetalleCompra.getValueAt(i, 3))) / cantidad;
                    Producto producto = new Producto("", "", idProducto, cantidad, precioKg);
                    productos[i] = producto;
                }
            }
            numeroFactura = txtNumeroFactura.getText();
            idSuministrador = String.valueOf(cboSuministrador.getItemAt(cboSuministrador.getSelectedIndex()));
            String separarSuministrador[] = idSuministrador.split(" - ", 2);
            idSuministrador = separarSuministrador[0];
            try {
                if (Sistema.getInstance().ingresarCompra(productos, fecha, idSuministrador, numeroFactura)) {
                    JOptionPane.showMessageDialog(this, "Se registró la compra.");
                } else {
                    JOptionPane.showMessageDialog(this, "Ha ocurrido un error, intente nuevamente.");
                }
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(Almacen.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(Almacen.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(Almacen.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_lblConfirmarCompraMouseClicked

    private void lblConfirmarCompraMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblConfirmarCompraMouseEntered
        btnConfirmarCompra.setBackground(new Color(255, 147, 178));
    }//GEN-LAST:event_lblConfirmarCompraMouseEntered

    private void lblConfirmarCompraMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblConfirmarCompraMouseExited
        btnConfirmarCompra.setBackground(new Color(255, 77, 123));
    }//GEN-LAST:event_lblConfirmarCompraMouseExited

    private void lblCancelarCompraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCancelarCompraMouseClicked
        DefaultTableModel modelo = (DefaultTableModel) tbeDetalleCompra.getModel();
        int borrar = tbeDetalleCompra.getRowCount();

        for (int i = borrar - 1; i >= 0; i--) {
            modelo.removeRow(i);
        }
        lblTotal.setText("Total: $ 0.0");
        txtNumeroFactura.setText("");
        txtProducto.setText("");
        txtPrecioKg.setText("");
        txtCantidad.setText("");
        jDateFecha.setCalendar(null);
        cboSuministrador.setSelectedIndex(0);
    }//GEN-LAST:event_lblCancelarCompraMouseClicked

    private void lblCancelarCompraMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCancelarCompraMouseEntered
        btnCancelarCompra.setBackground(new Color(255, 147, 178));
    }//GEN-LAST:event_lblCancelarCompraMouseEntered

    private void lblCancelarCompraMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCancelarCompraMouseExited
        btnCancelarCompra.setBackground(new Color(255, 77, 123));
    }//GEN-LAST:event_lblCancelarCompraMouseExited

    private void lblEliminarProductoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblEliminarProductoMouseClicked
        DefaultTableModel modelo = (DefaultTableModel) tbeDetalleCompra.getModel();

        int filaSeleccionada = tbeDetalleCompra.getSelectedRow();
        double sumaTotal = 0.0;
        if (filaSeleccionada == -1) {
            JOptionPane.showMessageDialog(this, "Seleccione el producto que desea eliminar de la lista...");
        } else {
            modelo.removeRow(filaSeleccionada);
            if (tbeDetalleCompra.getRowCount() > 0) {
                for (int i = 0; i < tbeDetalleCompra.getRowCount(); i++) {
                    double sumar = Double.parseDouble((String) tbeDetalleCompra.getValueAt(i, 3));
                    sumaTotal += sumar;
                }
            }
            lblTotal.setText("Total: $" + sumaTotal);
        }

    }//GEN-LAST:event_lblEliminarProductoMouseClicked

    private void lblEliminarProductoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblEliminarProductoMouseEntered
        btnEliminarProducto.setBackground(new Color(255, 147, 178));
    }//GEN-LAST:event_lblEliminarProductoMouseEntered

    private void lblEliminarProductoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblEliminarProductoMouseExited
        btnEliminarProducto.setBackground(new Color(255, 77, 123));
    }//GEN-LAST:event_lblEliminarProductoMouseExited

    private void lblRegistrar2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRegistrar2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblRegistrar2MouseClicked

    private void lblRegistrar2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRegistrar2MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_lblRegistrar2MouseEntered

    private void lblRegistrar2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRegistrar2MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_lblRegistrar2MouseExited

    private void lblAtrasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAtrasMouseClicked
        MenuAdministrador menu = new MenuAdministrador(usuario);
        menu.setVisible(true);
        dispose();
    }//GEN-LAST:event_lblAtrasMouseClicked

    private void lblAtrasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAtrasMouseEntered
        btnAtras.setBackground(new Color(55, 86, 103));
    }//GEN-LAST:event_lblAtrasMouseEntered

    private void lblAtrasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAtrasMouseExited
        btnAtras.setBackground(new Color(42, 72, 89));
    }//GEN-LAST:event_lblAtrasMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Almacen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Almacen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Almacen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Almacen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Almacen().setVisible(true);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(Almacen.class.getName()).log(Level.SEVERE, null, ex);
                } catch (SQLException ex) {
                    Logger.getLogger(Almacen.class.getName()).log(Level.SEVERE, null, ex);
                } catch (IOException ex) {
                    Logger.getLogger(Almacen.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BarraTitulo;
    private javax.swing.JPanel RegistroUsuario;
    private javax.swing.JPanel btnAgregar;
    private javax.swing.JPanel btnAtras;
    private javax.swing.JPanel btnBuscar;
    private javax.swing.JPanel btnCancelarCompra;
    private javax.swing.JPanel btnCancelarSeleccion;
    private javax.swing.JPanel btnConfirmarCompra;
    private javax.swing.JPanel btnEliminarProducto;
    private javax.swing.JPanel btnExit;
    private javax.swing.JPanel btnSeleccionar;
    private javax.swing.JPanel btnVerTodos;
    private javax.swing.JComboBox<String> cboSuministrador;
    private com.toedter.calendar.JDateChooser jDateFecha;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblAgregar;
    private javax.swing.JLabel lblAtras;
    private javax.swing.JLabel lblBuscar;
    private javax.swing.JLabel lblCancelarCompra;
    private javax.swing.JLabel lblCancelarSeleccion;
    private javax.swing.JLabel lblConfirmarCompra;
    private javax.swing.JLabel lblEliminarProducto;
    private javax.swing.JLabel lblIcono2;
    private javax.swing.JLabel lblRegistrar2;
    private javax.swing.JLabel lblSeleccionar;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblTitulo4;
    private javax.swing.JLabel lblTitulo5;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JLabel lblVerTodos;
    private javax.swing.JTable tbeDetalleCompra;
    private javax.swing.JTable tbeListado_Productos;
    private javax.swing.JTextField txtBuscador;
    private javax.swing.JTextField txtCantidad;
    private javax.swing.JLabel txtExit;
    private javax.swing.JTextField txtNumeroFactura;
    private javax.swing.JTextField txtPrecioKg;
    private javax.swing.JTextField txtProducto;
    // End of variables declaration//GEN-END:variables
}
