/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package grafica;

import java.awt.Color;
import java.io.IOException;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import logica.Usuario;

/**
 *
 * @author Franco
 */
public class MenuAdministrador extends javax.swing.JFrame {

    int xMouse, yMouse;
    Usuario usuario;

    public MenuAdministrador() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    public MenuAdministrador(Usuario usuario) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.usuario = usuario;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Panel = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        lblTitulo4 = new javax.swing.JLabel();
        btnUsuarios = new javax.swing.JPanel();
        btnColorUsuarios = new javax.swing.JPanel();
        lblUsuarios = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnAlmacen = new javax.swing.JPanel();
        btnColorAlmacen = new javax.swing.JPanel();
        lblAlmacen = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        BarraTitulo = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        btnExit = new javax.swing.JPanel();
        txtExit = new javax.swing.JLabel();
        lblIcono2 = new javax.swing.JLabel();
        btnPuntoVenta = new javax.swing.JPanel();
        btnColorPuntoVenta = new javax.swing.JPanel();
        lblPuntoVenta = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnPersonal = new javax.swing.JPanel();
        btnColorPersonal = new javax.swing.JPanel();
        lblPersonal = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnSuministradores = new javax.swing.JPanel();
        btnColorSuministradores = new javax.swing.JPanel();
        lblSuministradores = new javax.swing.JLabel();
        btnProductos = new javax.swing.JLabel();
        btnSolicitudes = new javax.swing.JPanel();
        btnColorSolicitudes = new javax.swing.JPanel();
        lblSolicitudes = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnListadoStock = new javax.swing.JPanel();
        btnColorListadoStock = new javax.swing.JPanel();
        lblListadoStock = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btnEstadisticas = new javax.swing.JPanel();
        btnColorEstadisticas = new javax.swing.JPanel();
        lblEstadisticas = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        btnProductos1 = new javax.swing.JPanel();
        btnColorProductos = new javax.swing.JPanel();
        lblProductos = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menú");
        setMaximumSize(new java.awt.Dimension(760, 855));
        setMinimumSize(new java.awt.Dimension(760, 855));
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Panel.setBackground(new java.awt.Color(21, 47, 62));
        Panel.setForeground(new java.awt.Color(204, 204, 204));
        Panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setBackground(new java.awt.Color(4, 224, 190));

        lblTitulo4.setBackground(new java.awt.Color(0, 0, 0));
        lblTitulo4.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        lblTitulo4.setForeground(new java.awt.Color(255, 255, 255));
        lblTitulo4.setText("Menú Principal");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 760, Short.MAX_VALUE)
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel5Layout.createSequentialGroup()
                    .addGap(0, 299, Short.MAX_VALUE)
                    .addComponent(lblTitulo4)
                    .addGap(0, 300, Short.MAX_VALUE)))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel5Layout.createSequentialGroup()
                    .addGap(0, 15, Short.MAX_VALUE)
                    .addComponent(lblTitulo4)
                    .addGap(0, 16, Short.MAX_VALUE)))
        );

        Panel.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 760, 60));

        btnUsuarios.setBackground(new java.awt.Color(220, 233, 242));
        btnUsuarios.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnUsuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnUsuariosMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnUsuariosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnUsuariosMouseExited(evt);
            }
        });
        btnUsuarios.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnColorUsuarios.setBackground(new java.awt.Color(4, 224, 190));

        lblUsuarios.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        lblUsuarios.setForeground(new java.awt.Color(255, 255, 255));
        lblUsuarios.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblUsuarios.setText("USUARIOS");
        lblUsuarios.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblUsuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblUsuariosMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblUsuariosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblUsuariosMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnColorUsuariosLayout = new javax.swing.GroupLayout(btnColorUsuarios);
        btnColorUsuarios.setLayout(btnColorUsuariosLayout);
        btnColorUsuariosLayout.setHorizontalGroup(
            btnColorUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblUsuarios, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
        );
        btnColorUsuariosLayout.setVerticalGroup(
            btnColorUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnColorUsuariosLayout.createSequentialGroup()
                .addComponent(lblUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        btnUsuarios.add(btnColorUsuarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 180, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/grafica/Imagenes/icons8_users_144px.png"))); // NOI18N
        btnUsuarios.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        Panel.add(btnUsuarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 130, 180, 210));

        btnAlmacen.setBackground(new java.awt.Color(220, 233, 242));
        btnAlmacen.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAlmacen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAlmacenMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAlmacenMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAlmacenMouseExited(evt);
            }
        });
        btnAlmacen.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnColorAlmacen.setBackground(new java.awt.Color(4, 224, 190));

        lblAlmacen.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        lblAlmacen.setForeground(new java.awt.Color(255, 255, 255));
        lblAlmacen.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAlmacen.setText("ALMACÉN");
        lblAlmacen.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblAlmacen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblAlmacenMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblAlmacenMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblAlmacenMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnColorAlmacenLayout = new javax.swing.GroupLayout(btnColorAlmacen);
        btnColorAlmacen.setLayout(btnColorAlmacenLayout);
        btnColorAlmacenLayout.setHorizontalGroup(
            btnColorAlmacenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblAlmacen, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
        );
        btnColorAlmacenLayout.setVerticalGroup(
            btnColorAlmacenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnColorAlmacenLayout.createSequentialGroup()
                .addComponent(lblAlmacen, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        btnAlmacen.add(btnColorAlmacen, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 180, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/grafica/Imagenes/icons8_grocery_shelf_144px_3.png"))); // NOI18N
        btnAlmacen.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        Panel.add(btnAlmacen, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 130, 180, 210));

        BarraTitulo.setBackground(new java.awt.Color(231, 255, 255));
        BarraTitulo.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                BarraTituloMouseDragged(evt);
            }
        });
        BarraTitulo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BarraTituloMousePressed(evt);
            }
        });
        BarraTitulo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitulo.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(153, 153, 153));
        lblTitulo.setText("Almacén - Menú");
        BarraTitulo.add(lblTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 8, -1, -1));

        btnExit.setBackground(new java.awt.Color(231, 255, 255));
        btnExit.setForeground(new java.awt.Color(255, 255, 255));
        btnExit.setMaximumSize(new java.awt.Dimension(30, 30));
        btnExit.setMinimumSize(new java.awt.Dimension(30, 30));
        btnExit.setPreferredSize(new java.awt.Dimension(30, 30));
        btnExit.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtExit.setBackground(new java.awt.Color(51, 51, 51));
        txtExit.setFont(new java.awt.Font("Roboto Light", 1, 24)); // NOI18N
        txtExit.setForeground(new java.awt.Color(0, 0, 0));
        txtExit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtExit.setText("X");
        txtExit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtExitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtExitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtExitMouseExited(evt);
            }
        });
        btnExit.add(txtExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 35, 30));

        BarraTitulo.add(btnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(725, 0, 35, 30));

        lblIcono2.setBackground(new java.awt.Color(51, 51, 51));
        lblIcono2.setFont(new java.awt.Font("Roboto Light", 1, 24)); // NOI18N
        lblIcono2.setForeground(new java.awt.Color(0, 0, 0));
        lblIcono2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblIcono2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/grafica/Imagenes/Icono 15px.png"))); // NOI18N
        lblIcono2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        BarraTitulo.add(lblIcono2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 35, 30));

        Panel.add(BarraTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 760, 30));

        btnPuntoVenta.setBackground(new java.awt.Color(220, 233, 242));
        btnPuntoVenta.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPuntoVenta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPuntoVentaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnPuntoVentaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnPuntoVentaMouseExited(evt);
            }
        });
        btnPuntoVenta.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnColorPuntoVenta.setBackground(new java.awt.Color(4, 224, 190));

        lblPuntoVenta.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        lblPuntoVenta.setForeground(new java.awt.Color(255, 255, 255));
        lblPuntoVenta.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPuntoVenta.setText("PUNTO DE VENTA");
        lblPuntoVenta.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblPuntoVenta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblPuntoVentaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblPuntoVentaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblPuntoVentaMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnColorPuntoVentaLayout = new javax.swing.GroupLayout(btnColorPuntoVenta);
        btnColorPuntoVenta.setLayout(btnColorPuntoVentaLayout);
        btnColorPuntoVentaLayout.setHorizontalGroup(
            btnColorPuntoVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblPuntoVenta, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
        );
        btnColorPuntoVentaLayout.setVerticalGroup(
            btnColorPuntoVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnColorPuntoVentaLayout.createSequentialGroup()
                .addComponent(lblPuntoVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        btnPuntoVenta.add(btnColorPuntoVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 180, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/grafica/Imagenes/icons8_stall_144px.png"))); // NOI18N
        btnPuntoVenta.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        Panel.add(btnPuntoVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 130, 180, 210));

        btnPersonal.setBackground(new java.awt.Color(220, 233, 242));
        btnPersonal.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPersonal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPersonalMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnPersonalMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnPersonalMouseExited(evt);
            }
        });
        btnPersonal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnColorPersonal.setBackground(new java.awt.Color(4, 224, 190));

        lblPersonal.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        lblPersonal.setForeground(new java.awt.Color(255, 255, 255));
        lblPersonal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPersonal.setText("PERSONAL");
        lblPersonal.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblPersonal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblPersonalMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblPersonalMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblPersonalMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnColorPersonalLayout = new javax.swing.GroupLayout(btnColorPersonal);
        btnColorPersonal.setLayout(btnColorPersonalLayout);
        btnColorPersonalLayout.setHorizontalGroup(
            btnColorPersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblPersonal, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
        );
        btnColorPersonalLayout.setVerticalGroup(
            btnColorPersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnColorPersonalLayout.createSequentialGroup()
                .addComponent(lblPersonal, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        btnPersonal.add(btnColorPersonal, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 180, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/grafica/Imagenes/icons8_workers_144px.png"))); // NOI18N
        btnPersonal.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        Panel.add(btnPersonal, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 370, 180, 210));

        btnSuministradores.setBackground(new java.awt.Color(220, 233, 242));
        btnSuministradores.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSuministradores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSuministradoresMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSuministradoresMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSuministradoresMouseExited(evt);
            }
        });
        btnSuministradores.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnColorSuministradores.setBackground(new java.awt.Color(4, 224, 190));

        lblSuministradores.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        lblSuministradores.setForeground(new java.awt.Color(255, 255, 255));
        lblSuministradores.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSuministradores.setText("SUMINISTRADORES");
        lblSuministradores.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblSuministradores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblSuministradoresMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblSuministradoresMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblSuministradoresMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnColorSuministradoresLayout = new javax.swing.GroupLayout(btnColorSuministradores);
        btnColorSuministradores.setLayout(btnColorSuministradoresLayout);
        btnColorSuministradoresLayout.setHorizontalGroup(
            btnColorSuministradoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblSuministradores, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
        );
        btnColorSuministradoresLayout.setVerticalGroup(
            btnColorSuministradoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnColorSuministradoresLayout.createSequentialGroup()
                .addComponent(lblSuministradores, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        btnSuministradores.add(btnColorSuministradores, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 180, -1));

        btnProductos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/grafica/Imagenes/icons8_delivered_144px.png"))); // NOI18N
        btnSuministradores.add(btnProductos, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        Panel.add(btnSuministradores, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 610, 180, 210));

        btnSolicitudes.setBackground(new java.awt.Color(220, 233, 242));
        btnSolicitudes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSolicitudes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSolicitudesMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSolicitudesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSolicitudesMouseExited(evt);
            }
        });
        btnSolicitudes.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnColorSolicitudes.setBackground(new java.awt.Color(4, 224, 190));

        lblSolicitudes.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        lblSolicitudes.setForeground(new java.awt.Color(255, 255, 255));
        lblSolicitudes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSolicitudes.setText("SOLICITUDES");
        lblSolicitudes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblSolicitudes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblSolicitudesMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblSolicitudesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblSolicitudesMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnColorSolicitudesLayout = new javax.swing.GroupLayout(btnColorSolicitudes);
        btnColorSolicitudes.setLayout(btnColorSolicitudesLayout);
        btnColorSolicitudesLayout.setHorizontalGroup(
            btnColorSolicitudesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblSolicitudes, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
        );
        btnColorSolicitudesLayout.setVerticalGroup(
            btnColorSolicitudesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnColorSolicitudesLayout.createSequentialGroup()
                .addComponent(lblSolicitudes, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        btnSolicitudes.add(btnColorSolicitudes, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 180, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/grafica/Imagenes/icons8_note_144px.png"))); // NOI18N
        btnSolicitudes.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        Panel.add(btnSolicitudes, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 370, 180, 210));

        btnListadoStock.setBackground(new java.awt.Color(220, 233, 242));
        btnListadoStock.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnListadoStock.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnListadoStockMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnListadoStockMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnListadoStockMouseExited(evt);
            }
        });
        btnListadoStock.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnColorListadoStock.setBackground(new java.awt.Color(4, 224, 190));

        lblListadoStock.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        lblListadoStock.setForeground(new java.awt.Color(255, 255, 255));
        lblListadoStock.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblListadoStock.setText("LISTADO DE STOCK");
        lblListadoStock.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblListadoStock.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblListadoStockMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblListadoStockMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblListadoStockMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnColorListadoStockLayout = new javax.swing.GroupLayout(btnColorListadoStock);
        btnColorListadoStock.setLayout(btnColorListadoStockLayout);
        btnColorListadoStockLayout.setHorizontalGroup(
            btnColorListadoStockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblListadoStock, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
        );
        btnColorListadoStockLayout.setVerticalGroup(
            btnColorListadoStockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnColorListadoStockLayout.createSequentialGroup()
                .addComponent(lblListadoStock, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        btnListadoStock.add(btnColorListadoStock, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 180, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/grafica/Imagenes/icons8_index_144px.png"))); // NOI18N
        btnListadoStock.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        Panel.add(btnListadoStock, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 610, 180, 210));

        btnEstadisticas.setBackground(new java.awt.Color(220, 233, 242));
        btnEstadisticas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEstadisticas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEstadisticasMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnEstadisticasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnEstadisticasMouseExited(evt);
            }
        });
        btnEstadisticas.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnColorEstadisticas.setBackground(new java.awt.Color(4, 224, 190));

        lblEstadisticas.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        lblEstadisticas.setForeground(new java.awt.Color(255, 255, 255));
        lblEstadisticas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEstadisticas.setText("ESTADÍSTICAS");
        lblEstadisticas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblEstadisticas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblEstadisticasMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblEstadisticasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblEstadisticasMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnColorEstadisticasLayout = new javax.swing.GroupLayout(btnColorEstadisticas);
        btnColorEstadisticas.setLayout(btnColorEstadisticasLayout);
        btnColorEstadisticasLayout.setHorizontalGroup(
            btnColorEstadisticasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblEstadisticas, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
        );
        btnColorEstadisticasLayout.setVerticalGroup(
            btnColorEstadisticasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnColorEstadisticasLayout.createSequentialGroup()
                .addComponent(lblEstadisticas, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        btnEstadisticas.add(btnColorEstadisticas, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 180, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/grafica/Imagenes/icons8_futures_144px.png"))); // NOI18N
        btnEstadisticas.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        Panel.add(btnEstadisticas, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 610, 180, 210));

        btnProductos1.setBackground(new java.awt.Color(220, 233, 242));
        btnProductos1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnProductos1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnProductos1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnProductos1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnProductos1MouseExited(evt);
            }
        });
        btnProductos1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnColorProductos.setBackground(new java.awt.Color(4, 224, 190));

        lblProductos.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        lblProductos.setForeground(new java.awt.Color(255, 255, 255));
        lblProductos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblProductos.setText("PRODUCTOS");
        lblProductos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblProductos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblProductosMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblProductosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblProductosMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnColorProductosLayout = new javax.swing.GroupLayout(btnColorProductos);
        btnColorProductos.setLayout(btnColorProductosLayout);
        btnColorProductosLayout.setHorizontalGroup(
            btnColorProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblProductos, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
        );
        btnColorProductosLayout.setVerticalGroup(
            btnColorProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnColorProductosLayout.createSequentialGroup()
                .addComponent(lblProductos, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        btnProductos1.add(btnColorProductos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 180, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/grafica/Imagenes/icons8_group_of_fruits_144px.png"))); // NOI18N
        btnProductos1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        Panel.add(btnProductos1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 370, 180, 210));

        getContentPane().add(Panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 760, 855));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnUsuariosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUsuariosMouseEntered
        btnUsuarios.setBackground(new java.awt.Color(255, 255, 255));
        btnColorUsuarios.setBackground(new java.awt.Color(4, 208, 177));
    }//GEN-LAST:event_btnUsuariosMouseEntered

    private void btnUsuariosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUsuariosMouseExited
        btnUsuarios.setBackground(new java.awt.Color(220, 223, 242));
        btnColorUsuarios.setBackground(new java.awt.Color(4, 224, 190));
    }//GEN-LAST:event_btnUsuariosMouseExited

    private void lblUsuariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblUsuariosMouseClicked
        try {
            Usuarios ventana = new Usuarios(usuario);
            ventana.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(MenuAdministrador.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(MenuAdministrador.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(MenuAdministrador.class.getName()).log(Level.SEVERE, null, ex);
        }
        dispose();
    }//GEN-LAST:event_lblUsuariosMouseClicked

    private void txtExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtExitMouseClicked
        int confirmacion = JOptionPane.showConfirmDialog(null, "¿Desea cerrar sesión y salir?", "Cerrar Sesión...", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (confirmacion == 0) {
            System.exit(0);
        }
    }//GEN-LAST:event_txtExitMouseClicked

    private void txtExitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtExitMouseEntered
        btnExit.setBackground(new Color(230, 0, 0));
        txtExit.setForeground(Color.white);
    }//GEN-LAST:event_txtExitMouseEntered

    private void txtExitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtExitMouseExited
        btnExit.setBackground(new Color(231, 255, 255));
        txtExit.setForeground(Color.black);
    }//GEN-LAST:event_txtExitMouseExited

    private void BarraTituloMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BarraTituloMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_BarraTituloMouseDragged

    private void BarraTituloMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BarraTituloMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_BarraTituloMousePressed

    private void lblUsuariosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblUsuariosMouseEntered
        btnUsuarios.setBackground(new java.awt.Color(255, 255, 255));
        btnColorUsuarios.setBackground(new java.awt.Color(4, 208, 177));
    }//GEN-LAST:event_lblUsuariosMouseEntered

    private void lblUsuariosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblUsuariosMouseExited
        btnUsuarios.setBackground(new java.awt.Color(220, 223, 242));
        btnColorUsuarios.setBackground(new java.awt.Color(4, 224, 190));
    }//GEN-LAST:event_lblUsuariosMouseExited

    private void btnUsuariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUsuariosMouseClicked
        try {
            Usuarios ventana = new Usuarios(usuario);
            ventana.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(MenuAdministrador.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(MenuAdministrador.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(MenuAdministrador.class.getName()).log(Level.SEVERE, null, ex);
        }
        dispose();
    }//GEN-LAST:event_btnUsuariosMouseClicked

    private void lblAlmacenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAlmacenMouseClicked
        try {
            Almacen ventana = new Almacen(usuario);
            ventana.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(MenuAdministrador.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(MenuAdministrador.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(MenuAdministrador.class.getName()).log(Level.SEVERE, null, ex);
        }
        dispose();
    }//GEN-LAST:event_lblAlmacenMouseClicked

    private void lblAlmacenMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAlmacenMouseEntered
        btnAlmacen.setBackground(new java.awt.Color(255, 255, 255));
        btnColorAlmacen.setBackground(new java.awt.Color(4, 208, 177));
    }//GEN-LAST:event_lblAlmacenMouseEntered

    private void lblAlmacenMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAlmacenMouseExited
        btnAlmacen.setBackground(new java.awt.Color(220, 223, 242));
        btnColorAlmacen.setBackground(new java.awt.Color(4, 224, 190));
    }//GEN-LAST:event_lblAlmacenMouseExited

    private void btnAlmacenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAlmacenMouseClicked
        try {
            Almacen ventana = new Almacen(usuario);
            ventana.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(MenuAdministrador.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(MenuAdministrador.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(MenuAdministrador.class.getName()).log(Level.SEVERE, null, ex);
        }
        dispose();
    }//GEN-LAST:event_btnAlmacenMouseClicked

    private void btnAlmacenMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAlmacenMouseEntered
        btnAlmacen.setBackground(new java.awt.Color(255, 255, 255));
        btnColorAlmacen.setBackground(new java.awt.Color(4, 208, 177));
    }//GEN-LAST:event_btnAlmacenMouseEntered

    private void btnAlmacenMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAlmacenMouseExited
        btnAlmacen.setBackground(new java.awt.Color(220, 223, 242));
        btnColorAlmacen.setBackground(new java.awt.Color(4, 224, 190));
    }//GEN-LAST:event_btnAlmacenMouseExited

    private void lblPuntoVentaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblPuntoVentaMouseClicked
        try {
            Ventas ventana = new Ventas(usuario);
            ventana.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(MenuAdministrador.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(MenuAdministrador.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(MenuAdministrador.class.getName()).log(Level.SEVERE, null, ex);
        }
        dispose();
    }//GEN-LAST:event_lblPuntoVentaMouseClicked

    private void lblPuntoVentaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblPuntoVentaMouseEntered
        btnPuntoVenta.setBackground(new java.awt.Color(255, 255, 255));
        btnColorPuntoVenta.setBackground(new java.awt.Color(4, 208, 177));
    }//GEN-LAST:event_lblPuntoVentaMouseEntered

    private void lblPuntoVentaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblPuntoVentaMouseExited
        btnPuntoVenta.setBackground(new java.awt.Color(220, 223, 242));
        btnColorPuntoVenta.setBackground(new java.awt.Color(4, 224, 190));
    }//GEN-LAST:event_lblPuntoVentaMouseExited

    private void btnPuntoVentaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPuntoVentaMouseClicked
        try {
            Ventas ventana = new Ventas(usuario);
            ventana.setVisible(true);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(MenuAdministrador.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(MenuAdministrador.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(MenuAdministrador.class.getName()).log(Level.SEVERE, null, ex);
        }
        dispose();
    }//GEN-LAST:event_btnPuntoVentaMouseClicked

    private void btnPuntoVentaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPuntoVentaMouseEntered
        btnPuntoVenta.setBackground(new java.awt.Color(255, 255, 255));
        btnColorPuntoVenta.setBackground(new java.awt.Color(4, 208, 177));
    }//GEN-LAST:event_btnPuntoVentaMouseEntered

    private void btnPuntoVentaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPuntoVentaMouseExited
        btnPuntoVenta.setBackground(new java.awt.Color(220, 223, 242));
        btnColorPuntoVenta.setBackground(new java.awt.Color(4, 224, 190));
    }//GEN-LAST:event_btnPuntoVentaMouseExited

    private void lblPersonalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblPersonalMouseClicked
        try {
            Empleados ventana = new Empleados(usuario);
            ventana.setVisible(true);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(MenuAdministrador.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(MenuAdministrador.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(MenuAdministrador.class.getName()).log(Level.SEVERE, null, ex);
        }
        dispose();
    }//GEN-LAST:event_lblPersonalMouseClicked

    private void lblPersonalMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblPersonalMouseEntered
        btnPersonal.setBackground(new java.awt.Color(255, 255, 255));
        btnColorPersonal.setBackground(new java.awt.Color(4, 208, 177));
    }//GEN-LAST:event_lblPersonalMouseEntered

    private void lblPersonalMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblPersonalMouseExited
        btnPersonal.setBackground(new java.awt.Color(220, 223, 242));
        btnColorPersonal.setBackground(new java.awt.Color(4, 224, 190));
    }//GEN-LAST:event_lblPersonalMouseExited

    private void btnPersonalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPersonalMouseClicked
        try {
            Empleados ventana = new Empleados(usuario);
            ventana.setVisible(true);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(MenuAdministrador.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(MenuAdministrador.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(MenuAdministrador.class.getName()).log(Level.SEVERE, null, ex);
        }
        dispose();
    }//GEN-LAST:event_btnPersonalMouseClicked

    private void btnPersonalMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPersonalMouseEntered
        btnPersonal.setBackground(new java.awt.Color(255, 255, 255));
        btnColorPersonal.setBackground(new java.awt.Color(4, 208, 177));
    }//GEN-LAST:event_btnPersonalMouseEntered

    private void btnPersonalMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPersonalMouseExited
        btnPersonal.setBackground(new java.awt.Color(220, 223, 242));
        btnColorPersonal.setBackground(new java.awt.Color(4, 224, 190));
    }//GEN-LAST:event_btnPersonalMouseExited

    private void lblSuministradoresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSuministradoresMouseClicked
        try {
            Suministradores ventana = new Suministradores(usuario);
            ventana.setVisible(true);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(MenuAdministrador.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(MenuAdministrador.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(MenuAdministrador.class.getName()).log(Level.SEVERE, null, ex);
        }
        dispose();
    }//GEN-LAST:event_lblSuministradoresMouseClicked

    private void lblSuministradoresMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSuministradoresMouseEntered
        btnSuministradores.setBackground(new java.awt.Color(255, 255, 255));
        btnColorSuministradores.setBackground(new java.awt.Color(4, 208, 177));
    }//GEN-LAST:event_lblSuministradoresMouseEntered

    private void lblSuministradoresMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSuministradoresMouseExited
        btnSuministradores.setBackground(new java.awt.Color(220, 223, 242));
        btnColorSuministradores.setBackground(new java.awt.Color(4, 224, 190));
    }//GEN-LAST:event_lblSuministradoresMouseExited

    private void btnSuministradoresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSuministradoresMouseClicked
        try {
            Suministradores ventana = new Suministradores(usuario);
            ventana.setVisible(true);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(MenuAdministrador.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(MenuAdministrador.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(MenuAdministrador.class.getName()).log(Level.SEVERE, null, ex);
        }
        dispose();
    }//GEN-LAST:event_btnSuministradoresMouseClicked

    private void btnSuministradoresMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSuministradoresMouseEntered
        btnSuministradores.setBackground(new java.awt.Color(255, 255, 255));
        btnColorSuministradores.setBackground(new java.awt.Color(4, 208, 177));
    }//GEN-LAST:event_btnSuministradoresMouseEntered

    private void btnSuministradoresMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSuministradoresMouseExited
        btnSuministradores.setBackground(new java.awt.Color(220, 223, 242));
        btnColorSuministradores.setBackground(new java.awt.Color(4, 224, 190));
    }//GEN-LAST:event_btnSuministradoresMouseExited

    private void lblSolicitudesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSolicitudesMouseClicked
        try {
            Solicitudes ventana = new Solicitudes(usuario);
            ventana.setVisible(true);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(MenuAdministrador.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(MenuAdministrador.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(MenuAdministrador.class.getName()).log(Level.SEVERE, null, ex);
        }
        dispose();
    }//GEN-LAST:event_lblSolicitudesMouseClicked

    private void lblSolicitudesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSolicitudesMouseEntered
        btnSolicitudes.setBackground(new java.awt.Color(255, 255, 255));
        btnColorSolicitudes.setBackground(new java.awt.Color(4, 208, 177));
    }//GEN-LAST:event_lblSolicitudesMouseEntered

    private void lblSolicitudesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSolicitudesMouseExited
        btnSolicitudes.setBackground(new java.awt.Color(220, 223, 242));
        btnColorSolicitudes.setBackground(new java.awt.Color(4, 224, 190));
    }//GEN-LAST:event_lblSolicitudesMouseExited

    private void btnSolicitudesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSolicitudesMouseClicked
        try {
            Solicitudes ventana = new Solicitudes(usuario);
            ventana.setVisible(true);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(MenuAdministrador.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(MenuAdministrador.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(MenuAdministrador.class.getName()).log(Level.SEVERE, null, ex);
        }
        dispose();
    }//GEN-LAST:event_btnSolicitudesMouseClicked

    private void btnSolicitudesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSolicitudesMouseEntered
        btnSolicitudes.setBackground(new java.awt.Color(255, 255, 255));
        btnColorSolicitudes.setBackground(new java.awt.Color(4, 208, 177));
    }//GEN-LAST:event_btnSolicitudesMouseEntered

    private void btnSolicitudesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSolicitudesMouseExited
        btnSolicitudes.setBackground(new java.awt.Color(220, 223, 242));
        btnColorSolicitudes.setBackground(new java.awt.Color(4, 224, 190));
    }//GEN-LAST:event_btnSolicitudesMouseExited

    private void lblListadoStockMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblListadoStockMouseClicked
        try {
            Stock ventana = new Stock(usuario);
            ventana.setVisible(true);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(MenuAdministrador.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(MenuAdministrador.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(MenuAdministrador.class.getName()).log(Level.SEVERE, null, ex);
        }
        dispose();
    }//GEN-LAST:event_lblListadoStockMouseClicked

    private void lblListadoStockMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblListadoStockMouseEntered
        btnListadoStock.setBackground(new java.awt.Color(255, 255, 255));
        btnColorListadoStock.setBackground(new java.awt.Color(4, 208, 177));
    }//GEN-LAST:event_lblListadoStockMouseEntered

    private void lblListadoStockMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblListadoStockMouseExited
        btnListadoStock.setBackground(new java.awt.Color(220, 223, 242));
        btnColorListadoStock.setBackground(new java.awt.Color(4, 224, 190));
    }//GEN-LAST:event_lblListadoStockMouseExited

    private void btnListadoStockMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnListadoStockMouseClicked
        try {
            Stock ventana = new Stock(usuario);
            ventana.setVisible(true);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(MenuAdministrador.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(MenuAdministrador.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(MenuAdministrador.class.getName()).log(Level.SEVERE, null, ex);
        }
        dispose();
    }//GEN-LAST:event_btnListadoStockMouseClicked

    private void btnListadoStockMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnListadoStockMouseEntered
        btnListadoStock.setBackground(new java.awt.Color(255, 255, 255));
        btnColorListadoStock.setBackground(new java.awt.Color(4, 208, 177));
    }//GEN-LAST:event_btnListadoStockMouseEntered

    private void btnListadoStockMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnListadoStockMouseExited
        btnListadoStock.setBackground(new java.awt.Color(220, 223, 242));
        btnColorListadoStock.setBackground(new java.awt.Color(4, 224, 190));
    }//GEN-LAST:event_btnListadoStockMouseExited

    private void lblEstadisticasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblEstadisticasMouseClicked
        Estadisticas ventana = new Estadisticas(usuario);
        ventana.setVisible(true);
        dispose();
    }//GEN-LAST:event_lblEstadisticasMouseClicked

    private void lblEstadisticasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblEstadisticasMouseEntered
        btnEstadisticas.setBackground(new java.awt.Color(255, 255, 255));
        btnColorEstadisticas.setBackground(new java.awt.Color(4, 208, 177));
    }//GEN-LAST:event_lblEstadisticasMouseEntered

    private void lblEstadisticasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblEstadisticasMouseExited
        btnEstadisticas.setBackground(new java.awt.Color(220, 223, 242));
        btnColorEstadisticas.setBackground(new java.awt.Color(4, 224, 190));
    }//GEN-LAST:event_lblEstadisticasMouseExited

    private void btnEstadisticasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEstadisticasMouseClicked
        Estadisticas ventana = new Estadisticas(usuario);
        ventana.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnEstadisticasMouseClicked

    private void btnEstadisticasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEstadisticasMouseEntered
        btnEstadisticas.setBackground(new java.awt.Color(255, 255, 255));
        btnColorEstadisticas.setBackground(new java.awt.Color(4, 208, 177));
    }//GEN-LAST:event_btnEstadisticasMouseEntered

    private void btnEstadisticasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEstadisticasMouseExited
        btnEstadisticas.setBackground(new java.awt.Color(220, 223, 242));
        btnColorEstadisticas.setBackground(new java.awt.Color(4, 224, 190));
    }//GEN-LAST:event_btnEstadisticasMouseExited

    private void lblProductosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblProductosMouseClicked
        try {
            Productos ventana = new Productos(usuario);
            ventana.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(MenuAdministrador.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(MenuAdministrador.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(MenuAdministrador.class.getName()).log(Level.SEVERE, null, ex);
        }
        dispose();
    }//GEN-LAST:event_lblProductosMouseClicked

    private void lblProductosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblProductosMouseEntered
        btnProductos1.setBackground(new java.awt.Color(255, 255, 255));
        btnColorProductos.setBackground(new java.awt.Color(4, 208, 177));
    }//GEN-LAST:event_lblProductosMouseEntered

    private void lblProductosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblProductosMouseExited
        btnProductos1.setBackground(new java.awt.Color(220, 223, 242));
        btnColorProductos.setBackground(new java.awt.Color(4, 224, 190));
    }//GEN-LAST:event_lblProductosMouseExited

    private void btnProductos1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnProductos1MouseClicked
        try {
            Productos ventana = new Productos(usuario);
            ventana.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(MenuAdministrador.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(MenuAdministrador.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(MenuAdministrador.class.getName()).log(Level.SEVERE, null, ex);
        }
        dispose();
    }//GEN-LAST:event_btnProductos1MouseClicked

    private void btnProductos1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnProductos1MouseEntered
        btnProductos1.setBackground(new java.awt.Color(255, 255, 255));
        btnColorProductos.setBackground(new java.awt.Color(4, 208, 177));
    }//GEN-LAST:event_btnProductos1MouseEntered

    private void btnProductos1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnProductos1MouseExited
        btnProductos1.setBackground(new java.awt.Color(220, 223, 242));
        btnColorProductos.setBackground(new java.awt.Color(4, 224, 190));
    }//GEN-LAST:event_btnProductos1MouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuAdministrador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BarraTitulo;
    private javax.swing.JPanel Panel;
    private javax.swing.JPanel btnAlmacen;
    private javax.swing.JPanel btnColorAlmacen;
    private javax.swing.JPanel btnColorEstadisticas;
    private javax.swing.JPanel btnColorListadoStock;
    private javax.swing.JPanel btnColorPersonal;
    private javax.swing.JPanel btnColorProductos;
    private javax.swing.JPanel btnColorPuntoVenta;
    private javax.swing.JPanel btnColorSolicitudes;
    private javax.swing.JPanel btnColorSuministradores;
    private javax.swing.JPanel btnColorUsuarios;
    private javax.swing.JPanel btnEstadisticas;
    private javax.swing.JPanel btnExit;
    private javax.swing.JPanel btnListadoStock;
    private javax.swing.JPanel btnPersonal;
    private javax.swing.JLabel btnProductos;
    private javax.swing.JPanel btnProductos1;
    private javax.swing.JPanel btnPuntoVenta;
    private javax.swing.JPanel btnSolicitudes;
    private javax.swing.JPanel btnSuministradores;
    private javax.swing.JPanel btnUsuarios;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JLabel lblAlmacen;
    private javax.swing.JLabel lblEstadisticas;
    private javax.swing.JLabel lblIcono2;
    private javax.swing.JLabel lblListadoStock;
    private javax.swing.JLabel lblPersonal;
    private javax.swing.JLabel lblProductos;
    private javax.swing.JLabel lblPuntoVenta;
    private javax.swing.JLabel lblSolicitudes;
    private javax.swing.JLabel lblSuministradores;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblTitulo4;
    private javax.swing.JLabel lblUsuarios;
    private javax.swing.JLabel txtExit;
    // End of variables declaration//GEN-END:variables
}
