/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package grafica;

import java.awt.Color;
import java.awt.Font;
import java.io.IOException;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import logica.Producto;
import logica.Sistema;
import logica.Usuario;

/**
 *
 * @author Franco
 */
public class Productos extends javax.swing.JFrame {

    Usuario usuario;
    int xMouse, yMouse;

    public Productos() throws ClassNotFoundException, SQLException, IOException {
        initComponents();
        this.setLocationRelativeTo(null);
        txtId.setText(Sistema.getInstance().mostrarSiguienteIdProducto());
        txtId.setEnabled(false);
        txtNombre.requestFocus();
        tbeListado_Productos.setModel(Sistema.getInstance().mostrarListadoProductos());
        tbeListado_Productos.setBackground(Color.white);
        tbeListado_Productos.getTableHeader().setFont(new Font("Seoge UI", Font.BOLD, 12));
        tbeListado_Productos.getTableHeader().setOpaque(false);
        tbeListado_Productos.getTableHeader().setBackground(new Color(32, 136, 203));
        tbeListado_Productos.getTableHeader().setForeground(new Color(0, 0, 0));
        lblActualizar.setEnabled(false);
    }

    public Productos(Usuario usuario) throws ClassNotFoundException, SQLException, IOException {
        initComponents();
        this.usuario = usuario;
        this.setLocationRelativeTo(null);
        txtId.setText(Sistema.getInstance().mostrarSiguienteIdProducto());
        txtId.setEnabled(false);
        txtNombre.requestFocus();
        tbeListado_Productos.setModel(Sistema.getInstance().mostrarListadoProductos());
        tbeListado_Productos.setBackground(Color.white);
        tbeListado_Productos.getTableHeader().setFont(new Font("Seoge UI", Font.BOLD, 12));
        tbeListado_Productos.getTableHeader().setOpaque(false);
        tbeListado_Productos.getTableHeader().setBackground(new Color(32, 136, 203));
        tbeListado_Productos.getTableHeader().setForeground(new Color(0, 0, 0));
        lblActualizar.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        BarraTitulo = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        btnExit = new javax.swing.JPanel();
        txtExit = new javax.swing.JLabel();
        lblIcono2 = new javax.swing.JLabel();
        RegistroUsuario = new javax.swing.JPanel();
        lblTitulo2 = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        cboCategoria = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtCantidadMinima = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtPorcentajeVenta = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        ListadoUsuarios = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbeListado_Productos = new javax.swing.JTable();
        btnBuscar = new javax.swing.JPanel();
        lblBuscar = new javax.swing.JLabel();
        btnVerTodos = new javax.swing.JPanel();
        lblVerTodos = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        lblTitulo3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtBuscador = new javax.swing.JTextField();
        jPanel9 = new javax.swing.JPanel();
        lblTitulo5 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        lblAcciones = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnModificar = new javax.swing.JPanel();
        lblModificar = new javax.swing.JLabel();
        btnEliminar = new javax.swing.JPanel();
        lblEliminar = new javax.swing.JLabel();
        btnAtras = new javax.swing.JPanel();
        lblAtras = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        btnRegistrar = new javax.swing.JPanel();
        lblRegistrar = new javax.swing.JLabel();
        btnLimpiar = new javax.swing.JPanel();
        lblLimpiar = new javax.swing.JLabel();
        btnActualizar = new javax.swing.JPanel();
        lblActualizar = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        setSize(new java.awt.Dimension(980, 690));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(231, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BarraTitulo.setBackground(new java.awt.Color(231, 255, 255));
        BarraTitulo.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                BarraTituloMouseDragged(evt);
            }
        });
        BarraTitulo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BarraTituloMousePressed(evt);
            }
        });
        BarraTitulo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitulo.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(153, 153, 153));
        lblTitulo.setText("Almacén - Productos");
        BarraTitulo.add(lblTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 8, -1, -1));

        btnExit.setBackground(new java.awt.Color(231, 255, 255));
        btnExit.setForeground(new java.awt.Color(255, 255, 255));
        btnExit.setMaximumSize(new java.awt.Dimension(30, 30));
        btnExit.setMinimumSize(new java.awt.Dimension(30, 30));
        btnExit.setPreferredSize(new java.awt.Dimension(30, 30));
        btnExit.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtExit.setBackground(new java.awt.Color(51, 51, 51));
        txtExit.setFont(new java.awt.Font("Roboto Light", 1, 24)); // NOI18N
        txtExit.setForeground(new java.awt.Color(0, 0, 0));
        txtExit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtExit.setText("X");
        txtExit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtExitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtExitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtExitMouseExited(evt);
            }
        });
        btnExit.add(txtExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 35, 30));

        BarraTitulo.add(btnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(735, 0, 35, 30));

        lblIcono2.setBackground(new java.awt.Color(51, 51, 51));
        lblIcono2.setFont(new java.awt.Font("Roboto Light", 1, 24)); // NOI18N
        lblIcono2.setForeground(new java.awt.Color(0, 0, 0));
        lblIcono2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblIcono2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/grafica/Imagenes/Icono 15px.png"))); // NOI18N
        lblIcono2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        BarraTitulo.add(lblIcono2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 35, 30));

        jPanel1.add(BarraTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 770, 30));

        RegistroUsuario.setBackground(new java.awt.Color(51, 204, 255));
        RegistroUsuario.setForeground(new java.awt.Color(204, 204, 204));
        RegistroUsuario.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitulo2.setBackground(new java.awt.Color(0, 0, 0));
        lblTitulo2.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        lblTitulo2.setForeground(new java.awt.Color(255, 255, 255));
        lblTitulo2.setText("REGISTRAR / ACTUALIZAR PRODUCTO");
        RegistroUsuario.add(lblTitulo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, -1, -1));
        RegistroUsuario.add(txtId, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 40, 80, -1));
        RegistroUsuario.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 80, 280, -1));

        cboCategoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--------------------", "Frutas", "Verduras" }));
        RegistroUsuario.add(cboCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 120, 120, 25));

        jLabel4.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Categoría:");
        RegistroUsuario.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, -1, 20));

        jLabel3.setFont(new java.awt.Font("Roboto Light", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Nombre:");
        RegistroUsuario.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 80, -1, 20));

        jLabel5.setFont(new java.awt.Font("Roboto Light", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("ID:");
        RegistroUsuario.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 40, -1, 20));
        RegistroUsuario.add(txtCantidadMinima, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 160, 70, -1));

        jLabel6.setFont(new java.awt.Font("Roboto Light", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Cantidad Minima Kg:");
        RegistroUsuario.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 160, -1, 20));
        RegistroUsuario.add(txtPorcentajeVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 195, 70, -1));

        jLabel7.setFont(new java.awt.Font("Roboto Light", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Porcentaje Venta %:");
        RegistroUsuario.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 195, -1, 20));

        jPanel11.setBackground(new java.awt.Color(255, 255, 255, 50));

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 540, Short.MAX_VALUE)
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        RegistroUsuario.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 540, 30));

        jPanel1.add(RegistroUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 540, 230));

        ListadoUsuarios.setBackground(new java.awt.Color(51, 204, 255));
        ListadoUsuarios.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tbeListado_Productos.setBackground(new java.awt.Color(255, 255, 255));
        tbeListado_Productos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tbeListado_Productos.setFocusable(false);
        tbeListado_Productos.setRowHeight(23);
        tbeListado_Productos.setSelectionBackground(new java.awt.Color(204, 28, 66));
        tbeListado_Productos.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tbeListado_Productos);

        ListadoUsuarios.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 520, 190));

        btnBuscar.setBackground(new java.awt.Color(0, 122, 193));

        lblBuscar.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        lblBuscar.setForeground(new java.awt.Color(255, 255, 255));
        lblBuscar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/grafica/Imagenes/icons8_search_20px.png"))); // NOI18N
        lblBuscar.setText("BUSCAR");
        lblBuscar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblBuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblBuscarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblBuscarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblBuscarMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnBuscarLayout = new javax.swing.GroupLayout(btnBuscar);
        btnBuscar.setLayout(btnBuscarLayout);
        btnBuscarLayout.setHorizontalGroup(
            btnBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );
        btnBuscarLayout.setVerticalGroup(
            btnBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnBuscarLayout.createSequentialGroup()
                .addGap(0, 1, Short.MAX_VALUE)
                .addComponent(lblBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        ListadoUsuarios.add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 5, 100, 40));

        btnVerTodos.setBackground(new java.awt.Color(0, 122, 193));

        lblVerTodos.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        lblVerTodos.setForeground(new java.awt.Color(255, 255, 255));
        lblVerTodos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblVerTodos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/grafica/Imagenes/icons8_search_20px.png"))); // NOI18N
        lblVerTodos.setText("Ver Todos");
        lblVerTodos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblVerTodos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblVerTodosMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblVerTodosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblVerTodosMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnVerTodosLayout = new javax.swing.GroupLayout(btnVerTodos);
        btnVerTodos.setLayout(btnVerTodosLayout);
        btnVerTodosLayout.setHorizontalGroup(
            btnVerTodosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblVerTodos, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );
        btnVerTodosLayout.setVerticalGroup(
            btnVerTodosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnVerTodosLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblVerTodos, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        ListadoUsuarios.add(btnVerTodos, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 5, 100, 40));

        jPanel12.setBackground(new java.awt.Color(255, 255, 255, 50));

        lblTitulo3.setBackground(new java.awt.Color(0, 0, 0));
        lblTitulo3.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        lblTitulo3.setForeground(new java.awt.Color(255, 255, 255));
        lblTitulo3.setText("LISTA PRODUCTOS");

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(lblTitulo3)
                .addContainerGap(415, Short.MAX_VALUE))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitulo3)
                .addContainerGap(9, Short.MAX_VALUE))
        );

        ListadoUsuarios.add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 540, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/grafica/Imagenes/icons8_search_20px.png"))); // NOI18N
        ListadoUsuarios.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 15, -1, -1));

        txtBuscador.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txtBuscador.setForeground(new java.awt.Color(204, 204, 204));
        txtBuscador.setText("Buscar...");
        txtBuscador.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtBuscadorMousePressed(evt);
            }
        });
        ListadoUsuarios.add(txtBuscador, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 180, 30));

        jPanel1.add(ListadoUsuarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, 540, 300));

        jPanel9.setBackground(new java.awt.Color(21, 47, 62));

        lblTitulo5.setBackground(new java.awt.Color(0, 0, 0));
        lblTitulo5.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        lblTitulo5.setForeground(new java.awt.Color(255, 255, 255));
        lblTitulo5.setText("Gestión de Productos");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 560, Short.MAX_VALUE)
            .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel9Layout.createSequentialGroup()
                    .addGap(0, 163, Short.MAX_VALUE)
                    .addComponent(lblTitulo5)
                    .addGap(0, 164, Short.MAX_VALUE)))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
            .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel9Layout.createSequentialGroup()
                    .addGap(0, 5, Short.MAX_VALUE)
                    .addComponent(lblTitulo5)
                    .addGap(0, 6, Short.MAX_VALUE)))
        );

        jPanel1.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 560, 40));

        jPanel7.setBackground(new java.awt.Color(4, 224, 190));

        lblAcciones.setBackground(new java.awt.Color(255, 126, 164));
        lblAcciones.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        lblAcciones.setForeground(new java.awt.Color(255, 255, 255));
        lblAcciones.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAcciones.setText("Acciones");
        lblAcciones.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lblAcciones.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblAccionesMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblAccionesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblAccionesMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblAcciones, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblAcciones, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 30, 210, 40));

        jPanel2.setBackground(new java.awt.Color(21, 47, 62));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnModificar.setBackground(new java.awt.Color(255, 77, 123));

        lblModificar.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        lblModificar.setForeground(new java.awt.Color(255, 255, 255));
        lblModificar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblModificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/grafica/Imagenes/icons8_edit_20px_2.png"))); // NOI18N
        lblModificar.setText("MODIFICAR");
        lblModificar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblModificar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblModificarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblModificarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblModificarMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnModificarLayout = new javax.swing.GroupLayout(btnModificar);
        btnModificar.setLayout(btnModificarLayout);
        btnModificarLayout.setHorizontalGroup(
            btnModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblModificar, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
        );
        btnModificarLayout.setVerticalGroup(
            btnModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnModificarLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel2.add(btnModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 60, 120, -1));

        btnEliminar.setBackground(new java.awt.Color(255, 77, 123));

        lblEliminar.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        lblEliminar.setForeground(new java.awt.Color(255, 255, 255));
        lblEliminar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/grafica/Imagenes/icons8_minus_20px.png"))); // NOI18N
        lblEliminar.setText("ELIMINAR");
        lblEliminar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblEliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblEliminarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblEliminarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblEliminarMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnEliminarLayout = new javax.swing.GroupLayout(btnEliminar);
        btnEliminar.setLayout(btnEliminarLayout);
        btnEliminarLayout.setHorizontalGroup(
            btnEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
        );
        btnEliminarLayout.setVerticalGroup(
            btnEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnEliminarLayout.createSequentialGroup()
                .addComponent(lblEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel2.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 130, 120, -1));

        btnAtras.setBackground(new java.awt.Color(42, 72, 89));

        lblAtras.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        lblAtras.setForeground(new java.awt.Color(255, 255, 255));
        lblAtras.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAtras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/grafica/Imagenes/icons8_left_20px.png"))); // NOI18N
        lblAtras.setText("ATRÁS");
        lblAtras.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblAtras.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblAtrasMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblAtrasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblAtrasMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnAtrasLayout = new javax.swing.GroupLayout(btnAtras);
        btnAtras.setLayout(btnAtrasLayout);
        btnAtrasLayout.setHorizontalGroup(
            btnAtrasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblAtras, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
        );
        btnAtrasLayout.setVerticalGroup(
            btnAtrasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblAtras, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
        );

        jPanel2.add(btnAtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 270, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 315, 210, 320));

        jPanel8.setBackground(new java.awt.Color(21, 47, 62));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnRegistrar.setBackground(new java.awt.Color(255, 77, 123));

        lblRegistrar.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        lblRegistrar.setForeground(new java.awt.Color(255, 255, 255));
        lblRegistrar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRegistrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/grafica/Imagenes/icons8_create_20px_1.png"))); // NOI18N
        lblRegistrar.setText("REGISTRAR");
        lblRegistrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblRegistrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblRegistrarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblRegistrarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblRegistrarMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnRegistrarLayout = new javax.swing.GroupLayout(btnRegistrar);
        btnRegistrar.setLayout(btnRegistrarLayout);
        btnRegistrarLayout.setHorizontalGroup(
            btnRegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblRegistrar, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
        );
        btnRegistrarLayout.setVerticalGroup(
            btnRegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnRegistrarLayout.createSequentialGroup()
                .addComponent(lblRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel8.add(btnRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 30, 120, -1));

        btnLimpiar.setBackground(new java.awt.Color(255, 77, 123));

        lblLimpiar.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        lblLimpiar.setForeground(new java.awt.Color(255, 255, 255));
        lblLimpiar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLimpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/grafica/Imagenes/icons8_eraser_20px.png"))); // NOI18N
        lblLimpiar.setText("LIMPIAR");
        lblLimpiar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblLimpiar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblLimpiarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblLimpiarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblLimpiarMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnLimpiarLayout = new javax.swing.GroupLayout(btnLimpiar);
        btnLimpiar.setLayout(btnLimpiarLayout);
        btnLimpiarLayout.setHorizontalGroup(
            btnLimpiarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblLimpiar, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
        );
        btnLimpiarLayout.setVerticalGroup(
            btnLimpiarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnLimpiarLayout.createSequentialGroup()
                .addComponent(lblLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel8.add(btnLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 100, 120, -1));

        btnActualizar.setBackground(new java.awt.Color(255, 176, 199));

        lblActualizar.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        lblActualizar.setForeground(new java.awt.Color(255, 255, 255));
        lblActualizar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblActualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/grafica/Imagenes/icons8_refresh_20px.png"))); // NOI18N
        lblActualizar.setText("ACTUALIZAR");
        lblActualizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblActualizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblActualizarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblActualizarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblActualizarMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnActualizarLayout = new javax.swing.GroupLayout(btnActualizar);
        btnActualizar.setLayout(btnActualizarLayout);
        btnActualizarLayout.setHorizontalGroup(
            btnActualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblActualizar, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
        );
        btnActualizarLayout.setVerticalGroup(
            btnActualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnActualizarLayout.createSequentialGroup()
                .addComponent(lblActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel8.add(btnActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 170, 120, -1));

        jPanel1.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 70, 210, 240));

        jPanel13.setBackground(new java.awt.Color(4, 224, 190));

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 210, Short.MAX_VALUE)
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 310, 210, 5));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 770, 635));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtExitMouseClicked
        MenuAdministrador menu = new MenuAdministrador(usuario);
        menu.setVisible(true);
        dispose();
    }//GEN-LAST:event_txtExitMouseClicked

    private void txtExitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtExitMouseEntered
        btnExit.setBackground(new Color(230, 0, 0));
        txtExit.setForeground(Color.white);
    }//GEN-LAST:event_txtExitMouseEntered

    private void txtExitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtExitMouseExited
        btnExit.setBackground(new Color(231, 255, 255));
        txtExit.setForeground(Color.black);
    }//GEN-LAST:event_txtExitMouseExited

    private void BarraTituloMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BarraTituloMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_BarraTituloMouseDragged

    private void BarraTituloMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BarraTituloMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_BarraTituloMousePressed

    private void lblRegistrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRegistrarMouseClicked
        String nombreProducto = txtNombre.getText();
        String idProducto = txtId.getText();
        String categoria = null;
        int cantidadMinima = 0;
        int porcentajeVenta = 0;

        int selecCategoria = cboCategoria.getSelectedIndex();

        if (lblRegistrar.isEnabled()) {
            if (nombreProducto.isEmpty()) {
                JOptionPane.showMessageDialog(this, "El campo \"Nombre\" es obligatorio.");
            } else if (selecCategoria == 0) {
                JOptionPane.showMessageDialog(this, "Seleccione una categoría...");
            } else if (!txtCantidadMinima.getText().matches("[0-9]+")) {
                JOptionPane.showMessageDialog(this, "El campo \"Cantidad Mínima Kg\" es inválido.");
            } else if (!txtPorcentajeVenta.getText().matches("[0-9]+")) {
                JOptionPane.showMessageDialog(this, "El campo \"Porcentaje Venta %\" es inválido.");
            } else if (selecCategoria == 1) {
                categoria = "Frutas";
                cantidadMinima = Integer.parseInt(txtCantidadMinima.getText());
                porcentajeVenta = Integer.parseInt(txtPorcentajeVenta.getText());

                Producto producto = new Producto(categoria, "FRU", idProducto, nombreProducto, cantidadMinima, porcentajeVenta);
                try {
                    if (Sistema.getInstance().registrarProducto(producto)) {
                        JOptionPane.showMessageDialog(this, "El producto se registró correctamente.");
                    } else {
                        JOptionPane.showMessageDialog(this, "Error! El producto ya existe.");
                    }
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(Productos.class.getName()).log(Level.SEVERE, null, ex);
                } catch (SQLException ex) {
                    Logger.getLogger(Productos.class.getName()).log(Level.SEVERE, null, ex);
                } catch (IOException ex) {
                    Logger.getLogger(Productos.class.getName()).log(Level.SEVERE, null, ex);
                }
                try {
                    txtId.setText(Sistema.getInstance().mostrarSiguienteIdProducto());
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(Productos.class.getName()).log(Level.SEVERE, null, ex);
                } catch (SQLException ex) {
                    Logger.getLogger(Productos.class.getName()).log(Level.SEVERE, null, ex);
                } catch (IOException ex) {
                    Logger.getLogger(Productos.class.getName()).log(Level.SEVERE, null, ex);
                }
                txtNombre.requestFocus();
                btnRegistrar.setEnabled(true);
                lblActualizar.setEnabled(false);
                try {
                    tbeListado_Productos.setModel(Sistema.getInstance().mostrarListadoProductos());
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(Productos.class.getName()).log(Level.SEVERE, null, ex);
                } catch (SQLException ex) {
                    Logger.getLogger(Productos.class.getName()).log(Level.SEVERE, null, ex);
                } catch (IOException ex) {
                    Logger.getLogger(Productos.class.getName()).log(Level.SEVERE, null, ex);
                }
            } else if (selecCategoria == 2) {
                categoria = "Verduras";
                cantidadMinima = Integer.parseInt(txtCantidadMinima.getText());
                porcentajeVenta = Integer.parseInt(txtPorcentajeVenta.getText());
                Producto producto = new Producto(categoria, "VER", idProducto, nombreProducto, cantidadMinima, porcentajeVenta);
                try {
                    if (Sistema.getInstance().registrarProducto(producto)) {
                        JOptionPane.showMessageDialog(this, "El producto se registró correctamente.");
                    } else {
                        JOptionPane.showMessageDialog(this, "Error! El producto ya existe.");
                    }
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(Productos.class.getName()).log(Level.SEVERE, null, ex);
                } catch (SQLException ex) {
                    Logger.getLogger(Productos.class.getName()).log(Level.SEVERE, null, ex);
                } catch (IOException ex) {
                    Logger.getLogger(Productos.class.getName()).log(Level.SEVERE, null, ex);
                }
                try {
                    txtId.setText(Sistema.getInstance().mostrarSiguienteIdProducto());
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(Productos.class.getName()).log(Level.SEVERE, null, ex);
                } catch (SQLException ex) {
                    Logger.getLogger(Productos.class.getName()).log(Level.SEVERE, null, ex);
                } catch (IOException ex) {
                    Logger.getLogger(Productos.class.getName()).log(Level.SEVERE, null, ex);
                }
                txtNombre.requestFocus();
                btnRegistrar.setEnabled(true);
                lblActualizar.setEnabled(false);
                try {
                    tbeListado_Productos.setModel(Sistema.getInstance().mostrarListadoProductos());
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(Productos.class.getName()).log(Level.SEVERE, null, ex);
                } catch (SQLException ex) {
                    Logger.getLogger(Productos.class.getName()).log(Level.SEVERE, null, ex);
                } catch (IOException ex) {
                    Logger.getLogger(Productos.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
    }//GEN-LAST:event_lblRegistrarMouseClicked

    private void lblRegistrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRegistrarMouseEntered
        if (lblRegistrar.isEnabled()) {
            btnRegistrar.setBackground(new Color(255, 147, 178));
        }
    }//GEN-LAST:event_lblRegistrarMouseEntered

    private void lblRegistrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRegistrarMouseExited
        if (lblRegistrar.isEnabled()) {
            btnRegistrar.setBackground(new Color(255, 77, 123));
        }
    }//GEN-LAST:event_lblRegistrarMouseExited

    private void lblLimpiarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLimpiarMouseClicked
        txtNombre.setText("");
        cboCategoria.setSelectedIndex(0);
        txtCantidadMinima.setText("");
        txtPorcentajeVenta.setText("");
        try {
            txtId.setText(Sistema.getInstance().mostrarSiguienteIdProducto());
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Productos.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Productos.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(Productos.class.getName()).log(Level.SEVERE, null, ex);
        }
        txtNombre.requestFocus();
        tbeListado_Productos.setEnabled(true);
        lblRegistrar.setEnabled(true);
        btnRegistrar.setBackground(new Color(255, 77, 123));
        lblActualizar.setEnabled(false);
        btnActualizar.setBackground(new Color(255, 176, 199));
    }//GEN-LAST:event_lblLimpiarMouseClicked

    private void lblLimpiarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLimpiarMouseEntered
        btnLimpiar.setBackground(new Color(255, 147, 178));
    }//GEN-LAST:event_lblLimpiarMouseEntered

    private void lblLimpiarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLimpiarMouseExited
        btnLimpiar.setBackground(new Color(255, 77, 123));
    }//GEN-LAST:event_lblLimpiarMouseExited

    private void lblActualizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblActualizarMouseClicked
        if (lblActualizar.isEnabled()) {
            String nombreProducto = txtNombre.getText();
            String idProducto = txtId.getText();
            String categoria = null;

            int selecCategoria = cboCategoria.getSelectedIndex();
            if (nombreProducto.isEmpty()) {
                JOptionPane.showMessageDialog(this, "El campo \"Nombre\" es obligatorio.");
            } else if (selecCategoria == 0) {
                JOptionPane.showMessageDialog(this, "Seleccione una categoría...");
            } else if (selecCategoria == 1) {
                categoria = "Frutas";
                Producto producto = new Producto(categoria, "FRU", idProducto, nombreProducto);
                try {
                    if (Sistema.getInstance().actualizarProducto(producto)) {
                        JOptionPane.showMessageDialog(this, "Se ha actualizado exitósamente.");
                    } else {
                        JOptionPane.showMessageDialog(this, "Error! No se pudo actualizar el producto, verifique los campos.");
                    }
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(Productos.class.getName()).log(Level.SEVERE, null, ex);
                } catch (SQLException ex) {
                    Logger.getLogger(Productos.class.getName()).log(Level.SEVERE, null, ex);
                } catch (IOException ex) {
                    Logger.getLogger(Productos.class.getName()).log(Level.SEVERE, null, ex);
                }
                try {
                    txtId.setText(Sistema.getInstance().mostrarSiguienteIdProducto());
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(Productos.class.getName()).log(Level.SEVERE, null, ex);
                } catch (SQLException ex) {
                    Logger.getLogger(Productos.class.getName()).log(Level.SEVERE, null, ex);
                } catch (IOException ex) {
                    Logger.getLogger(Productos.class.getName()).log(Level.SEVERE, null, ex);
                }
                txtNombre.setText("");
                cboCategoria.setSelectedIndex(0);
                txtNombre.requestFocus();
                lblRegistrar.setEnabled(true);
                btnRegistrar.setBackground(new Color(255, 77, 123));
                lblActualizar.setEnabled(false);
                btnActualizar.setBackground(new Color(255, 176, 199));
                tbeListado_Productos.setEnabled(true);
                try {
                    tbeListado_Productos.setModel(Sistema.getInstance().mostrarListadoProductos());
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(Productos.class.getName()).log(Level.SEVERE, null, ex);
                } catch (SQLException ex) {
                    Logger.getLogger(Productos.class.getName()).log(Level.SEVERE, null, ex);
                } catch (IOException ex) {
                    Logger.getLogger(Productos.class.getName()).log(Level.SEVERE, null, ex);
                }
            } else if (selecCategoria == 2) {
                categoria = "Verduras";
                Producto producto = new Producto(categoria, "VER", idProducto, nombreProducto);
                try {
                    if (Sistema.getInstance().actualizarProducto(producto)) {
                        JOptionPane.showMessageDialog(this, "Se ha actualizado exitósamente.");
                    } else {
                        JOptionPane.showMessageDialog(this, "Error! No se pudo actualizar el producto, verifique los campos.");
                    }
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(Productos.class.getName()).log(Level.SEVERE, null, ex);
                } catch (SQLException ex) {
                    Logger.getLogger(Productos.class.getName()).log(Level.SEVERE, null, ex);
                } catch (IOException ex) {
                    Logger.getLogger(Productos.class.getName()).log(Level.SEVERE, null, ex);
                }
                try {
                    txtId.setText(Sistema.getInstance().mostrarSiguienteIdProducto());
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(Productos.class.getName()).log(Level.SEVERE, null, ex);
                } catch (SQLException ex) {
                    Logger.getLogger(Productos.class.getName()).log(Level.SEVERE, null, ex);
                } catch (IOException ex) {
                    Logger.getLogger(Productos.class.getName()).log(Level.SEVERE, null, ex);
                }
                txtNombre.setText("");
                cboCategoria.setSelectedIndex(0);
                txtNombre.requestFocus();
                lblRegistrar.setEnabled(true);
                btnRegistrar.setBackground(new Color(255, 77, 123));
                lblActualizar.setEnabled(false);
                btnActualizar.setBackground(new Color(255, 176, 199));
                tbeListado_Productos.setEnabled(true);
                try {
                    tbeListado_Productos.setModel(Sistema.getInstance().mostrarListadoProductos());
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(Productos.class.getName()).log(Level.SEVERE, null, ex);
                } catch (SQLException ex) {
                    Logger.getLogger(Productos.class.getName()).log(Level.SEVERE, null, ex);
                } catch (IOException ex) {
                    Logger.getLogger(Productos.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
    }//GEN-LAST:event_lblActualizarMouseClicked

    private void lblActualizarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblActualizarMouseEntered
        if (lblActualizar.isEnabled()) {
            btnActualizar.setBackground(new Color(255, 147, 178));
        }
    }//GEN-LAST:event_lblActualizarMouseEntered

    private void lblActualizarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblActualizarMouseExited
        if (lblActualizar.isEnabled()) {
            btnActualizar.setBackground(new Color(255, 77, 123));
        }
    }//GEN-LAST:event_lblActualizarMouseExited

    private void lblModificarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblModificarMouseClicked

        int filaSeleccionada = tbeListado_Productos.getSelectedRow();

        if (filaSeleccionada == -1) {
            JOptionPane.showMessageDialog(this, "Seleccione el producto que desea modificar...");
        } else {
            lblActualizar.setEnabled(true);
            btnActualizar.setBackground(new Color(255, 77, 123));
            lblRegistrar.setEnabled(false);
            btnRegistrar.setBackground(new Color(255, 176, 199));
            txtId.setText(String.valueOf(tbeListado_Productos.getValueAt(filaSeleccionada, 0)));
            txtNombre.setText(String.valueOf(tbeListado_Productos.getValueAt(filaSeleccionada, 1)));

            if (String.valueOf(tbeListado_Productos.getValueAt(filaSeleccionada, 2)).equalsIgnoreCase("FRU")) {
                cboCategoria.setSelectedIndex(1);
            } else if (String.valueOf(tbeListado_Productos.getValueAt(filaSeleccionada, 2)).equalsIgnoreCase("VER")) {
                cboCategoria.setSelectedIndex(2);
            }
            tbeListado_Productos.setEnabled(false);
        }
    }//GEN-LAST:event_lblModificarMouseClicked

    private void lblModificarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblModificarMouseEntered
        btnModificar.setBackground(new Color(255, 147, 178));
    }//GEN-LAST:event_lblModificarMouseEntered

    private void lblModificarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblModificarMouseExited
        btnModificar.setBackground(new Color(255, 77, 123));
    }//GEN-LAST:event_lblModificarMouseExited

    private void lblEliminarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblEliminarMouseClicked
        int filaSeleccionada = tbeListado_Productos.getSelectedRow();
        String id = null;
        String nombre = null;
        if (filaSeleccionada == -1) {
            JOptionPane.showMessageDialog(this, "Seleccione el producto que desea eliminar...");
        } else {
            id = String.valueOf(tbeListado_Productos.getValueAt(filaSeleccionada, 0));
            nombre = String.valueOf(tbeListado_Productos.getValueAt(filaSeleccionada, 1));
            int confirmacion = JOptionPane.showConfirmDialog(null, "¿Desea eliminar el producto: " + nombre + "?", "Confirmación de eliminación...", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
            if (confirmacion == 0) {
                try {
                    if (Sistema.getInstance().eliminarProducto(id)) {
                        JOptionPane.showMessageDialog(this, "Se ha elmininado correctamente.");
                    } else {
                        JOptionPane.showMessageDialog(this, "Se ha producido un error, intente nuevamente.");
                    }
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(Productos.class.getName()).log(Level.SEVERE, null, ex);
                } catch (SQLException ex) {
                    Logger.getLogger(Productos.class.getName()).log(Level.SEVERE, null, ex);
                } catch (IOException ex) {
                    Logger.getLogger(Productos.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            try {
                tbeListado_Productos.setModel(Sistema.getInstance().mostrarListadoProductos());
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(Productos.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(Productos.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(Productos.class.getName()).log(Level.SEVERE, null, ex);
            }
            try {
                txtId.setText(Sistema.getInstance().mostrarSiguienteIdProducto());
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(Productos.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(Productos.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(Productos.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_lblEliminarMouseClicked

    private void lblEliminarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblEliminarMouseEntered
        btnEliminar.setBackground(new Color(255, 147, 178));
    }//GEN-LAST:event_lblEliminarMouseEntered

    private void lblEliminarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblEliminarMouseExited
        btnEliminar.setBackground(new Color(255, 77, 123));
    }//GEN-LAST:event_lblEliminarMouseExited

    private void lblBuscarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBuscarMouseClicked
        String buscar = null;
        if (txtBuscador.getText().isEmpty() || txtBuscador.getText().equals("Buscar...")) {
            JOptionPane.showMessageDialog(this, "Ingrese el producto que desea buscar.");
        } else {

            buscar = "%" + txtBuscador.getText() + "%";
            try {
                tbeListado_Productos.setModel(Sistema.getInstance().buscarProductos(buscar));
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(Productos.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(Productos.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(Productos.class.getName()).log(Level.SEVERE, null, ex);
            }

        }
    }//GEN-LAST:event_lblBuscarMouseClicked

    private void lblBuscarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBuscarMouseEntered
        btnBuscar.setBackground(new Color(64, 172, 234));
    }//GEN-LAST:event_lblBuscarMouseEntered

    private void lblBuscarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBuscarMouseExited
        btnBuscar.setBackground(new Color(0, 122, 193));
    }//GEN-LAST:event_lblBuscarMouseExited

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        if (txtBuscador.getText().isEmpty()) {
            txtBuscador.setText("Buscar...");
            txtBuscador.setForeground(new Color(204, 204, 204));
        }
    }//GEN-LAST:event_formMouseClicked

    private void lblVerTodosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblVerTodosMouseClicked
        try {
            tbeListado_Productos.setModel(Sistema.getInstance().mostrarListadoProductos());
            txtBuscador.setText("Buscar...");
            txtBuscador.setForeground(new Color(204, 204, 204));
            txtNombre.requestFocus();;
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Productos.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Productos.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(Productos.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_lblVerTodosMouseClicked

    private void lblVerTodosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblVerTodosMouseEntered
        btnVerTodos.setBackground(new Color(64, 172, 234));
    }//GEN-LAST:event_lblVerTodosMouseEntered

    private void lblVerTodosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblVerTodosMouseExited
        btnVerTodos.setBackground(new Color(0, 122, 193));
    }//GEN-LAST:event_lblVerTodosMouseExited

    private void lblAccionesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAccionesMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblAccionesMouseClicked

    private void lblAccionesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAccionesMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_lblAccionesMouseEntered

    private void lblAccionesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAccionesMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_lblAccionesMouseExited

    private void txtBuscadorMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtBuscadorMousePressed
        if (txtBuscador.getText().equals("Buscar...")) {
            txtBuscador.setText("");
            txtBuscador.setForeground(Color.black);
        }
    }//GEN-LAST:event_txtBuscadorMousePressed

    private void lblAtrasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAtrasMouseClicked
        MenuAdministrador menu = new MenuAdministrador(usuario);
        menu.setVisible(true);
        dispose();
    }//GEN-LAST:event_lblAtrasMouseClicked

    private void lblAtrasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAtrasMouseEntered
        btnAtras.setBackground(new Color(55, 86, 103));
    }//GEN-LAST:event_lblAtrasMouseEntered

    private void lblAtrasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAtrasMouseExited
        btnAtras.setBackground(new Color(42, 72, 89));
    }//GEN-LAST:event_lblAtrasMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Productos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Productos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Productos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Productos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Productos().setVisible(true);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(Productos.class.getName()).log(Level.SEVERE, null, ex);
                } catch (SQLException ex) {
                    Logger.getLogger(Productos.class.getName()).log(Level.SEVERE, null, ex);
                } catch (IOException ex) {
                    Logger.getLogger(Productos.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BarraTitulo;
    private javax.swing.JPanel ListadoUsuarios;
    private javax.swing.JPanel RegistroUsuario;
    private javax.swing.JPanel btnActualizar;
    private javax.swing.JPanel btnAtras;
    private javax.swing.JPanel btnBuscar;
    private javax.swing.JPanel btnEliminar;
    private javax.swing.JPanel btnExit;
    private javax.swing.JPanel btnLimpiar;
    private javax.swing.JPanel btnModificar;
    private javax.swing.JPanel btnRegistrar;
    private javax.swing.JPanel btnVerTodos;
    private javax.swing.JComboBox<String> cboCategoria;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAcciones;
    private javax.swing.JLabel lblActualizar;
    private javax.swing.JLabel lblAtras;
    private javax.swing.JLabel lblBuscar;
    private javax.swing.JLabel lblEliminar;
    private javax.swing.JLabel lblIcono2;
    private javax.swing.JLabel lblLimpiar;
    private javax.swing.JLabel lblModificar;
    private javax.swing.JLabel lblRegistrar;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblTitulo2;
    private javax.swing.JLabel lblTitulo3;
    private javax.swing.JLabel lblTitulo5;
    private javax.swing.JLabel lblVerTodos;
    private javax.swing.JTable tbeListado_Productos;
    private javax.swing.JTextField txtBuscador;
    private javax.swing.JTextField txtCantidadMinima;
    private javax.swing.JLabel txtExit;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtPorcentajeVenta;
    // End of variables declaration//GEN-END:variables
}
