/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package grafica;

import java.awt.Color;
import java.io.IOException;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import logica.Sistema;
import logica.Usuario;

public class Solicitudes extends javax.swing.JFrame {

    int xMouse, yMouse;
    Usuario usuario;
    
    public Solicitudes() throws ClassNotFoundException, SQLException, IOException {
        initComponents();
        this.setLocationRelativeTo(null);
        tbeSolicitudes.setModel(Sistema.getInstance().mostrarSolicitudesSinAbastecer());
    }

    public Solicitudes(Usuario usuario) throws ClassNotFoundException, SQLException, IOException {
        this.usuario = usuario;        
        initComponents();
        this.setLocationRelativeTo(null);
        tbeSolicitudes.setModel(Sistema.getInstance().mostrarSolicitudesSinAbastecer());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbeSolicitudes = new javax.swing.JTable();
        btnTodas = new javax.swing.JPanel();
        lblTodas = new javax.swing.JLabel();
        btnAbastecidas = new javax.swing.JPanel();
        lblAbastecidas = new javax.swing.JLabel();
        btnSinAbastecer = new javax.swing.JPanel();
        lblSinAbastecer = new javax.swing.JLabel();
        btnRechazadas = new javax.swing.JPanel();
        lblRechazadas = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        lblTitulo3 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        btnMarcarComoAbastecida = new javax.swing.JPanel();
        lblMarcarComoAbastecida = new javax.swing.JLabel();
        btnRechazar = new javax.swing.JPanel();
        lblRechazar = new javax.swing.JLabel();
        btnAtras = new javax.swing.JPanel();
        lblAtras = new javax.swing.JLabel();
        BarraTitulo = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        btnExit = new javax.swing.JPanel();
        txtExit = new javax.swing.JLabel();
        lblIcono2 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        lblTitulo5 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        lblAcciones = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(790, 370));
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(231, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(51, 204, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tbeSolicitudes.setBackground(new java.awt.Color(255, 255, 255));
        tbeSolicitudes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Producto", "Fecha", "Estado"
            }
        ));
        tbeSolicitudes.setFocusable(false);
        tbeSolicitudes.setRowHeight(23);
        tbeSolicitudes.setSelectionBackground(new java.awt.Color(204, 28, 66));
        tbeSolicitudes.getTableHeader().setReorderingAllowed(false);
        jScrollPane3.setViewportView(tbeSolicitudes);

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 40, 390, 230));

        btnTodas.setBackground(new java.awt.Color(0, 122, 193));

        lblTodas.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        lblTodas.setForeground(new java.awt.Color(255, 255, 255));
        lblTodas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTodas.setText("Todas");
        lblTodas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblTodas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblTodasMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblTodasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblTodasMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnTodasLayout = new javax.swing.GroupLayout(btnTodas);
        btnTodas.setLayout(btnTodasLayout);
        btnTodasLayout.setHorizontalGroup(
            btnTodasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTodas, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
        );
        btnTodasLayout.setVerticalGroup(
            btnTodasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnTodasLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblTodas, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(btnTodas, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 223, 130, -1));

        btnAbastecidas.setBackground(new java.awt.Color(0, 122, 193));

        lblAbastecidas.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        lblAbastecidas.setForeground(new java.awt.Color(255, 255, 255));
        lblAbastecidas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAbastecidas.setText("Abastecidas");
        lblAbastecidas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblAbastecidas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblAbastecidasMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblAbastecidasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblAbastecidasMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnAbastecidasLayout = new javax.swing.GroupLayout(btnAbastecidas);
        btnAbastecidas.setLayout(btnAbastecidasLayout);
        btnAbastecidasLayout.setHorizontalGroup(
            btnAbastecidasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblAbastecidas, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
        );
        btnAbastecidasLayout.setVerticalGroup(
            btnAbastecidasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnAbastecidasLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblAbastecidas, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(btnAbastecidas, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 103, 130, -1));

        btnSinAbastecer.setBackground(new java.awt.Color(0, 122, 193));

        lblSinAbastecer.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        lblSinAbastecer.setForeground(new java.awt.Color(255, 255, 255));
        lblSinAbastecer.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSinAbastecer.setText("Sin abastecer");
        lblSinAbastecer.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblSinAbastecer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblSinAbastecerMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblSinAbastecerMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblSinAbastecerMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnSinAbastecerLayout = new javax.swing.GroupLayout(btnSinAbastecer);
        btnSinAbastecer.setLayout(btnSinAbastecerLayout);
        btnSinAbastecerLayout.setHorizontalGroup(
            btnSinAbastecerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblSinAbastecer, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
        );
        btnSinAbastecerLayout.setVerticalGroup(
            btnSinAbastecerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnSinAbastecerLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblSinAbastecer, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(btnSinAbastecer, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 43, 130, -1));

        btnRechazadas.setBackground(new java.awt.Color(0, 122, 193));

        lblRechazadas.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        lblRechazadas.setForeground(new java.awt.Color(255, 255, 255));
        lblRechazadas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRechazadas.setText("Rechazadas");
        lblRechazadas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblRechazadas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblRechazadasMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblRechazadasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblRechazadasMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnRechazadasLayout = new javax.swing.GroupLayout(btnRechazadas);
        btnRechazadas.setLayout(btnRechazadasLayout);
        btnRechazadasLayout.setHorizontalGroup(
            btnRechazadasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblRechazadas, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
        );
        btnRechazadasLayout.setVerticalGroup(
            btnRechazadasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnRechazadasLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblRechazadas, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(btnRechazadas, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 163, 130, -1));

        jPanel11.setBackground(new java.awt.Color(255, 255, 255, 50));

        lblTitulo3.setBackground(new java.awt.Color(0, 0, 0));
        lblTitulo3.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        lblTitulo3.setForeground(new java.awt.Color(255, 255, 255));
        lblTitulo3.setText("SOLICITUDES DE COMPRA");

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(186, 186, 186)
                .addComponent(lblTitulo3, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(204, Short.MAX_VALUE))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitulo3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 550, 30));

        jPanel2.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 550, 280));

        jPanel8.setBackground(new java.awt.Color(21, 47, 62));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnMarcarComoAbastecida.setBackground(new java.awt.Color(255, 77, 123));

        lblMarcarComoAbastecida.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        lblMarcarComoAbastecida.setForeground(new java.awt.Color(255, 255, 255));
        lblMarcarComoAbastecida.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMarcarComoAbastecida.setIcon(new javax.swing.ImageIcon(getClass().getResource("/grafica/Imagenes/icons8_approval_20px.png"))); // NOI18N
        lblMarcarComoAbastecida.setText("Marcar como abastecida");
        lblMarcarComoAbastecida.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblMarcarComoAbastecida.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblMarcarComoAbastecidaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblMarcarComoAbastecidaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblMarcarComoAbastecidaMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnMarcarComoAbastecidaLayout = new javax.swing.GroupLayout(btnMarcarComoAbastecida);
        btnMarcarComoAbastecida.setLayout(btnMarcarComoAbastecidaLayout);
        btnMarcarComoAbastecidaLayout.setHorizontalGroup(
            btnMarcarComoAbastecidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblMarcarComoAbastecida, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
        );
        btnMarcarComoAbastecidaLayout.setVerticalGroup(
            btnMarcarComoAbastecidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblMarcarComoAbastecida, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jPanel8.add(btnMarcarComoAbastecida, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        btnRechazar.setBackground(new java.awt.Color(255, 77, 123));

        lblRechazar.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        lblRechazar.setForeground(new java.awt.Color(255, 255, 255));
        lblRechazar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRechazar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/grafica/Imagenes/icons8_Close_20px.png"))); // NOI18N
        lblRechazar.setText("Rechazar");
        lblRechazar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblRechazar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblRechazarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblRechazarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblRechazarMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnRechazarLayout = new javax.swing.GroupLayout(btnRechazar);
        btnRechazar.setLayout(btnRechazarLayout);
        btnRechazarLayout.setHorizontalGroup(
            btnRechazarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnRechazarLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblRechazar, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        btnRechazarLayout.setVerticalGroup(
            btnRechazarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnRechazarLayout.createSequentialGroup()
                .addComponent(lblRechazar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel8.add(btnRechazar, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, 100, -1));

        btnAtras.setBackground(new java.awt.Color(42, 72, 89));

        lblAtras.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        lblAtras.setForeground(new java.awt.Color(255, 255, 255));
        lblAtras.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAtras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/grafica/Imagenes/icons8_left_20px.png"))); // NOI18N
        lblAtras.setText("ATRÁS");
        lblAtras.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblAtras.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblAtrasMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblAtrasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblAtrasMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnAtrasLayout = new javax.swing.GroupLayout(btnAtras);
        btnAtras.setLayout(btnAtrasLayout);
        btnAtrasLayout.setHorizontalGroup(
            btnAtrasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblAtras, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
        );
        btnAtrasLayout.setVerticalGroup(
            btnAtrasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblAtras, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
        );

        jPanel8.add(btnAtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 250, -1, -1));

        jPanel2.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 70, 220, 300));

        BarraTitulo.setBackground(new java.awt.Color(231, 255, 255));
        BarraTitulo.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                BarraTituloMouseDragged(evt);
            }
        });
        BarraTitulo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BarraTituloMousePressed(evt);
            }
        });
        BarraTitulo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitulo.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(153, 153, 153));
        lblTitulo.setText("Almacén - Solicitudes");
        BarraTitulo.add(lblTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 8, -1, -1));

        btnExit.setBackground(new java.awt.Color(231, 255, 255));
        btnExit.setForeground(new java.awt.Color(255, 255, 255));
        btnExit.setMaximumSize(new java.awt.Dimension(30, 30));
        btnExit.setMinimumSize(new java.awt.Dimension(30, 30));
        btnExit.setPreferredSize(new java.awt.Dimension(30, 30));
        btnExit.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtExit.setBackground(new java.awt.Color(51, 51, 51));
        txtExit.setFont(new java.awt.Font("Roboto Light", 1, 24)); // NOI18N
        txtExit.setForeground(new java.awt.Color(0, 0, 0));
        txtExit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtExit.setText("X");
        txtExit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtExitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtExitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtExitMouseExited(evt);
            }
        });
        btnExit.add(txtExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 35, 30));

        BarraTitulo.add(btnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(755, 0, 35, 30));

        lblIcono2.setBackground(new java.awt.Color(51, 51, 51));
        lblIcono2.setFont(new java.awt.Font("Roboto Light", 1, 24)); // NOI18N
        lblIcono2.setForeground(new java.awt.Color(0, 0, 0));
        lblIcono2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblIcono2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/grafica/Imagenes/Icono 15px.png"))); // NOI18N
        lblIcono2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        BarraTitulo.add(lblIcono2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 35, 30));

        jPanel2.add(BarraTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel9.setBackground(new java.awt.Color(21, 47, 62));

        lblTitulo5.setBackground(new java.awt.Color(0, 0, 0));
        lblTitulo5.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        lblTitulo5.setForeground(new java.awt.Color(255, 255, 255));
        lblTitulo5.setText("Gestión de Solicitudes");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 570, Short.MAX_VALUE)
            .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel9Layout.createSequentialGroup()
                    .addGap(0, 164, Short.MAX_VALUE)
                    .addComponent(lblTitulo5)
                    .addGap(0, 165, Short.MAX_VALUE)))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
            .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel9Layout.createSequentialGroup()
                    .addGap(0, 5, Short.MAX_VALUE)
                    .addComponent(lblTitulo5)
                    .addGap(0, 6, Short.MAX_VALUE)))
        );

        jPanel2.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 570, -1));

        jPanel7.setBackground(new java.awt.Color(4, 224, 190));

        lblAcciones.setBackground(new java.awt.Color(255, 126, 164));
        lblAcciones.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        lblAcciones.setForeground(new java.awt.Color(255, 255, 255));
        lblAcciones.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAcciones.setText("Acciones");
        lblAcciones.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lblAcciones.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblAccionesMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblAccionesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblAccionesMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblAcciones, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblAcciones, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 30, 220, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 790, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblMarcarComoAbastecidaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMarcarComoAbastecidaMouseClicked
        String idSolicitud = null;
        String estado = null;

        int filaSeleccionada = tbeSolicitudes.getSelectedRow();

        if (filaSeleccionada == -1) {
            JOptionPane.showMessageDialog(this, "Seleccione la solicitud");
        } else {
            idSolicitud = String.valueOf(tbeSolicitudes.getValueAt(filaSeleccionada, 0));
            estado = "Abastecida";
            try {
                if (Sistema.getInstance().cambiarEstadoSolicitud(idSolicitud, estado)) {
                    JOptionPane.showMessageDialog(this, "Se actualizó correctamente");
                    tbeSolicitudes.setModel(Sistema.getInstance().mostrarTodasLasSolicitudes());
                } else {
                    JOptionPane.showMessageDialog(this, "Ocurrió un error. Intente Nuevamente.");
                    tbeSolicitudes.setModel(Sistema.getInstance().mostrarTodasLasSolicitudes());
                }
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(Solicitudes.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(Solicitudes.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(Solicitudes.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_lblMarcarComoAbastecidaMouseClicked

    private void lblMarcarComoAbastecidaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMarcarComoAbastecidaMouseEntered
        btnMarcarComoAbastecida.setBackground(new Color(255, 147, 178));
    }//GEN-LAST:event_lblMarcarComoAbastecidaMouseEntered

    private void lblMarcarComoAbastecidaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMarcarComoAbastecidaMouseExited
        btnMarcarComoAbastecida.setBackground(new Color(255, 77, 123));
    }//GEN-LAST:event_lblMarcarComoAbastecidaMouseExited

    private void lblRechazarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRechazarMouseClicked
        String idSolicitud = null;
        String estado = null;

        int filaSeleccionada = tbeSolicitudes.getSelectedRow();

        if (filaSeleccionada == -1) {
            JOptionPane.showMessageDialog(this, "Seleccione la solicitud");
        } else {
            idSolicitud = String.valueOf(tbeSolicitudes.getValueAt(filaSeleccionada, 0));
            estado = "Rechazada";
            try {
                if (Sistema.getInstance().cambiarEstadoSolicitud(idSolicitud, estado)) {
                    JOptionPane.showMessageDialog(this, "Se actualizó correctamente");
                    tbeSolicitudes.setModel(Sistema.getInstance().mostrarTodasLasSolicitudes());
                } else {
                    JOptionPane.showMessageDialog(this, "Ocurrió un error. Intente Nuevamente.");
                    tbeSolicitudes.setModel(Sistema.getInstance().mostrarTodasLasSolicitudes());
                }
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(Solicitudes.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(Solicitudes.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(Solicitudes.class.getName()).log(Level.SEVERE, null, ex);
            }
        }                
    }//GEN-LAST:event_lblRechazarMouseClicked

    private void lblRechazarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRechazarMouseEntered
        btnRechazar.setBackground(new Color(255, 147, 178));
    }//GEN-LAST:event_lblRechazarMouseEntered

    private void lblRechazarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRechazarMouseExited
        btnRechazar.setBackground(new Color(255, 77, 123));
    }//GEN-LAST:event_lblRechazarMouseExited

    private void lblTodasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblTodasMouseClicked
        try {
            tbeSolicitudes.setModel(Sistema.getInstance().mostrarTodasLasSolicitudes());
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Solicitudes.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Solicitudes.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(Solicitudes.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_lblTodasMouseClicked

    private void lblTodasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblTodasMouseEntered
        btnTodas.setBackground(new Color(64, 172, 234));
    }//GEN-LAST:event_lblTodasMouseEntered

    private void lblTodasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblTodasMouseExited
        btnTodas.setBackground(new Color(0, 122, 193));
    }//GEN-LAST:event_lblTodasMouseExited

    private void lblAbastecidasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAbastecidasMouseClicked
        try {
            tbeSolicitudes.setModel(Sistema.getInstance().mostrarSolicitudesAbastecidas());
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Solicitudes.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Solicitudes.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(Solicitudes.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_lblAbastecidasMouseClicked

    private void lblAbastecidasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAbastecidasMouseEntered
        btnAbastecidas.setBackground(new Color(64, 172, 234));
    }//GEN-LAST:event_lblAbastecidasMouseEntered

    private void lblAbastecidasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAbastecidasMouseExited
        btnAbastecidas.setBackground(new Color(0, 122, 193));
    }//GEN-LAST:event_lblAbastecidasMouseExited

    private void lblSinAbastecerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSinAbastecerMouseClicked
        try {
            tbeSolicitudes.setModel(Sistema.getInstance().mostrarSolicitudesSinAbastecer());        // TODO add your handling code here:
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Solicitudes.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Solicitudes.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(Solicitudes.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_lblSinAbastecerMouseClicked

    private void lblSinAbastecerMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSinAbastecerMouseEntered
        btnSinAbastecer.setBackground(new Color(64, 172, 234));
    }//GEN-LAST:event_lblSinAbastecerMouseEntered

    private void lblSinAbastecerMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSinAbastecerMouseExited
        btnSinAbastecer.setBackground(new Color(0, 122, 193));
    }//GEN-LAST:event_lblSinAbastecerMouseExited

    private void lblRechazadasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRechazadasMouseClicked
        try {
            tbeSolicitudes.setModel(Sistema.getInstance().mostrarSolicitudesRechazadas());
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Solicitudes.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Solicitudes.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(Solicitudes.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_lblRechazadasMouseClicked

    private void lblRechazadasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRechazadasMouseEntered
        btnRechazadas.setBackground(new Color(64, 172, 234));
    }//GEN-LAST:event_lblRechazadasMouseEntered

    private void lblRechazadasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRechazadasMouseExited
        btnRechazadas.setBackground(new Color(0, 122, 193));
    }//GEN-LAST:event_lblRechazadasMouseExited

    private void txtExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtExitMouseClicked
        MenuAdministrador menu = new MenuAdministrador(usuario);
        menu.setVisible(true);
        dispose();
    }//GEN-LAST:event_txtExitMouseClicked

    private void txtExitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtExitMouseEntered
        btnExit.setBackground(new Color(230, 0, 0));
        txtExit.setForeground(Color.white);
    }//GEN-LAST:event_txtExitMouseEntered

    private void txtExitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtExitMouseExited
        btnExit.setBackground(new Color(231, 255, 255));
        txtExit.setForeground(Color.black);
    }//GEN-LAST:event_txtExitMouseExited

    private void BarraTituloMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BarraTituloMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_BarraTituloMouseDragged

    private void BarraTituloMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BarraTituloMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_BarraTituloMousePressed

    private void lblAccionesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAccionesMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblAccionesMouseClicked

    private void lblAccionesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAccionesMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_lblAccionesMouseEntered

    private void lblAccionesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAccionesMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_lblAccionesMouseExited

    private void lblAtrasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAtrasMouseClicked
        MenuAdministrador menu = new MenuAdministrador(usuario);
        menu.setVisible(true);
        dispose();
    }//GEN-LAST:event_lblAtrasMouseClicked

    private void lblAtrasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAtrasMouseEntered
        btnAtras.setBackground(new Color(55, 86, 103));
    }//GEN-LAST:event_lblAtrasMouseEntered

    private void lblAtrasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAtrasMouseExited
        btnAtras.setBackground(new Color(42, 72, 89));
    }//GEN-LAST:event_lblAtrasMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Solicitudes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Solicitudes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Solicitudes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Solicitudes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Solicitudes().setVisible(true);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(Solicitudes.class.getName()).log(Level.SEVERE, null, ex);
                } catch (SQLException ex) {
                    Logger.getLogger(Solicitudes.class.getName()).log(Level.SEVERE, null, ex);
                } catch (IOException ex) {
                    Logger.getLogger(Solicitudes.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BarraTitulo;
    private javax.swing.JPanel btnAbastecidas;
    private javax.swing.JPanel btnAtras;
    private javax.swing.JPanel btnExit;
    private javax.swing.JPanel btnMarcarComoAbastecida;
    private javax.swing.JPanel btnRechazadas;
    private javax.swing.JPanel btnRechazar;
    private javax.swing.JPanel btnSinAbastecer;
    private javax.swing.JPanel btnTodas;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblAbastecidas;
    private javax.swing.JLabel lblAcciones;
    private javax.swing.JLabel lblAtras;
    private javax.swing.JLabel lblIcono2;
    private javax.swing.JLabel lblMarcarComoAbastecida;
    private javax.swing.JLabel lblRechazadas;
    private javax.swing.JLabel lblRechazar;
    private javax.swing.JLabel lblSinAbastecer;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblTitulo3;
    private javax.swing.JLabel lblTitulo5;
    private javax.swing.JLabel lblTodas;
    private javax.swing.JTable tbeSolicitudes;
    private javax.swing.JLabel txtExit;
    // End of variables declaration//GEN-END:variables
}
