/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package grafica;

import java.awt.Color;
import java.io.IOException;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import logica.Sistema;
import logica.Usuario;

/**
 *
 * @author Franco
 */
public class Stock extends javax.swing.JFrame {

    Usuario usuario;
    int xMouse, yMouse;

    public Stock() throws ClassNotFoundException, SQLException, IOException {
        initComponents();
        this.setLocationRelativeTo(null);
        tbeStockFrutas.setModel(Sistema.getInstance().stockFrutas());
        tbeStockVerduras.setModel(Sistema.getInstance().stockVerduras());
        lblBuscarFruta.requestFocus();
    }

    public Stock(Usuario usuario) throws ClassNotFoundException, SQLException, IOException {
        initComponents();
        this.usuario = usuario;
        this.setLocationRelativeTo(null);
        tbeStockFrutas.setModel(Sistema.getInstance().stockFrutas());
        tbeStockVerduras.setModel(Sistema.getInstance().stockVerduras());
        lblBuscarFruta.requestFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JPanel = new javax.swing.JPanel();
        BarraTitulo = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        btnExit = new javax.swing.JPanel();
        txtExit = new javax.swing.JLabel();
        lblIcono2 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        lblTitulo5 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        txtBuscadorFrutas = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btnBuscarFruta = new javax.swing.JPanel();
        lblBuscarFruta = new javax.swing.JLabel();
        btnVerFrutas = new javax.swing.JPanel();
        lblVerFrutas = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        txtBuscadorVerduras = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        btnBuscarVerdura = new javax.swing.JPanel();
        lblBuscarVerdura = new javax.swing.JLabel();
        btnVerVerduras = new javax.swing.JPanel();
        lblVerVerduras = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        btnAtras = new javax.swing.JPanel();
        lblAtras = new javax.swing.JLabel();
        ListadoFrutas = new javax.swing.JPanel();
        jPanel14 = new javax.swing.JPanel();
        lblTitulo3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbeStockFrutas = new javax.swing.JTable();
        ListadoVerduras = new javax.swing.JPanel();
        jPanel15 = new javax.swing.JPanel();
        lblTitulo4 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbeStockVerduras = new javax.swing.JTable();
        jPanel16 = new javax.swing.JPanel();
        jPanel17 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(770, 650));
        setMinimumSize(new java.awt.Dimension(770, 650));
        setUndecorated(true);
        setResizable(false);
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        JPanel.setBackground(new java.awt.Color(231, 255, 255));
        JPanel.setMaximumSize(new java.awt.Dimension(770, 600));
        JPanel.setMinimumSize(new java.awt.Dimension(770, 600));
        JPanel.setPreferredSize(new java.awt.Dimension(770, 600));
        JPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BarraTitulo.setBackground(new java.awt.Color(231, 255, 255));
        BarraTitulo.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                BarraTituloMouseDragged(evt);
            }
        });
        BarraTitulo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BarraTituloMousePressed(evt);
            }
        });
        BarraTitulo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitulo.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(153, 153, 153));
        lblTitulo.setText("Almacén - Stock");
        BarraTitulo.add(lblTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 8, -1, -1));

        btnExit.setBackground(new java.awt.Color(231, 255, 255));
        btnExit.setForeground(new java.awt.Color(255, 255, 255));
        btnExit.setMaximumSize(new java.awt.Dimension(30, 30));
        btnExit.setMinimumSize(new java.awt.Dimension(30, 30));
        btnExit.setPreferredSize(new java.awt.Dimension(30, 30));
        btnExit.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtExit.setBackground(new java.awt.Color(51, 51, 51));
        txtExit.setFont(new java.awt.Font("Roboto Light", 1, 24)); // NOI18N
        txtExit.setForeground(new java.awt.Color(0, 0, 0));
        txtExit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtExit.setText("X");
        txtExit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtExitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtExitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtExitMouseExited(evt);
            }
        });
        btnExit.add(txtExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 35, 30));

        BarraTitulo.add(btnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(735, 0, 35, 30));

        lblIcono2.setBackground(new java.awt.Color(51, 51, 51));
        lblIcono2.setFont(new java.awt.Font("Roboto Light", 1, 24)); // NOI18N
        lblIcono2.setForeground(new java.awt.Color(0, 0, 0));
        lblIcono2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblIcono2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/grafica/Imagenes/Icono 15px.png"))); // NOI18N
        lblIcono2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        BarraTitulo.add(lblIcono2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 35, 30));

        JPanel.add(BarraTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 770, 30));

        jPanel11.setBackground(new java.awt.Color(21, 47, 62));

        lblTitulo5.setBackground(new java.awt.Color(0, 0, 0));
        lblTitulo5.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        lblTitulo5.setForeground(new java.awt.Color(255, 255, 255));
        lblTitulo5.setText("Listados de Stock");

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 770, Short.MAX_VALUE)
            .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel11Layout.createSequentialGroup()
                    .addGap(0, 288, Short.MAX_VALUE)
                    .addComponent(lblTitulo5)
                    .addGap(0, 288, Short.MAX_VALUE)))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
            .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel11Layout.createSequentialGroup()
                    .addGap(0, 5, Short.MAX_VALUE)
                    .addComponent(lblTitulo5)
                    .addGap(0, 6, Short.MAX_VALUE)))
        );

        JPanel.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 770, 40));

        jPanel2.setBackground(new java.awt.Color(21, 47, 62));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtBuscadorFrutas.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txtBuscadorFrutas.setForeground(new java.awt.Color(204, 204, 204));
        txtBuscadorFrutas.setText("Buscar por nombre...");
        txtBuscadorFrutas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtBuscadorFrutasMousePressed(evt);
            }
        });
        jPanel2.add(txtBuscadorFrutas, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 160, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/grafica/Imagenes/icons8_search_20px.png"))); // NOI18N
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 35, -1, -1));

        btnBuscarFruta.setBackground(new java.awt.Color(255, 77, 123));

        lblBuscarFruta.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        lblBuscarFruta.setForeground(new java.awt.Color(255, 255, 255));
        lblBuscarFruta.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBuscarFruta.setText("Buscar");
        lblBuscarFruta.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblBuscarFruta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblBuscarFrutaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblBuscarFrutaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblBuscarFrutaMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnBuscarFrutaLayout = new javax.swing.GroupLayout(btnBuscarFruta);
        btnBuscarFruta.setLayout(btnBuscarFrutaLayout);
        btnBuscarFrutaLayout.setHorizontalGroup(
            btnBuscarFrutaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblBuscarFruta, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
        );
        btnBuscarFrutaLayout.setVerticalGroup(
            btnBuscarFrutaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblBuscarFruta, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jPanel2.add(btnBuscarFruta, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, 90, 40));

        btnVerFrutas.setBackground(new java.awt.Color(255, 77, 123));

        lblVerFrutas.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        lblVerFrutas.setForeground(new java.awt.Color(255, 255, 255));
        lblVerFrutas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblVerFrutas.setText("Ver Todas");
        lblVerFrutas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblVerFrutas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblVerFrutasMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblVerFrutasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblVerFrutasMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnVerFrutasLayout = new javax.swing.GroupLayout(btnVerFrutas);
        btnVerFrutas.setLayout(btnVerFrutasLayout);
        btnVerFrutasLayout.setHorizontalGroup(
            btnVerFrutasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblVerFrutas, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
        );
        btnVerFrutasLayout.setVerticalGroup(
            btnVerFrutasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblVerFrutas, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jPanel2.add(btnVerFrutas, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 155, 90, 40));
        btnVerFrutas.getAccessibleContext().setAccessibleName("");

        jPanel3.setBackground(new java.awt.Color(25, 57, 76));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 210, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 210, 50));

        JPanel.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 80, 210, 263));

        jPanel4.setBackground(new java.awt.Color(21, 47, 62));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtBuscadorVerduras.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txtBuscadorVerduras.setForeground(new java.awt.Color(204, 204, 204));
        txtBuscadorVerduras.setText("Buscar por nombre...");
        txtBuscadorVerduras.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtBuscadorVerdurasMousePressed(evt);
            }
        });
        jPanel4.add(txtBuscadorVerduras, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 160, 30));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/grafica/Imagenes/icons8_search_20px.png"))); // NOI18N
        jPanel4.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 35, -1, -1));

        btnBuscarVerdura.setBackground(new java.awt.Color(255, 77, 123));

        lblBuscarVerdura.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        lblBuscarVerdura.setForeground(new java.awt.Color(255, 255, 255));
        lblBuscarVerdura.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBuscarVerdura.setText("Buscar");
        lblBuscarVerdura.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblBuscarVerdura.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblBuscarVerduraMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblBuscarVerduraMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblBuscarVerduraMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnBuscarVerduraLayout = new javax.swing.GroupLayout(btnBuscarVerdura);
        btnBuscarVerdura.setLayout(btnBuscarVerduraLayout);
        btnBuscarVerduraLayout.setHorizontalGroup(
            btnBuscarVerduraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblBuscarVerdura, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
        );
        btnBuscarVerduraLayout.setVerticalGroup(
            btnBuscarVerduraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblBuscarVerdura, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jPanel4.add(btnBuscarVerdura, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, 90, 40));

        btnVerVerduras.setBackground(new java.awt.Color(255, 77, 123));

        lblVerVerduras.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        lblVerVerduras.setForeground(new java.awt.Color(255, 255, 255));
        lblVerVerduras.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblVerVerduras.setText("Ver Todas");
        lblVerVerduras.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblVerVerduras.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblVerVerdurasMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblVerVerdurasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblVerVerdurasMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnVerVerdurasLayout = new javax.swing.GroupLayout(btnVerVerduras);
        btnVerVerduras.setLayout(btnVerVerdurasLayout);
        btnVerVerdurasLayout.setHorizontalGroup(
            btnVerVerdurasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblVerVerduras, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
        );
        btnVerVerdurasLayout.setVerticalGroup(
            btnVerVerdurasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblVerVerduras, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jPanel4.add(btnVerVerduras, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 155, 90, 40));

        jPanel5.setBackground(new java.awt.Color(25, 57, 76));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 210, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        jPanel4.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 210, 50));

        btnAtras.setBackground(new java.awt.Color(42, 72, 89));

        lblAtras.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        lblAtras.setForeground(new java.awt.Color(255, 255, 255));
        lblAtras.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAtras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/grafica/Imagenes/icons8_left_20px.png"))); // NOI18N
        lblAtras.setText("ATRÁS");
        lblAtras.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblAtras.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblAtrasMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblAtrasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblAtrasMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnAtrasLayout = new javax.swing.GroupLayout(btnAtras);
        btnAtras.setLayout(btnAtrasLayout);
        btnAtrasLayout.setHorizontalGroup(
            btnAtrasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblAtras, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
        );
        btnAtrasLayout.setVerticalGroup(
            btnAtrasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblAtras, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
        );

        jPanel4.add(btnAtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 255, -1, -1));

        JPanel.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 348, 210, 303));

        ListadoFrutas.setBackground(new java.awt.Color(51, 204, 255));
        ListadoFrutas.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel14.setBackground(new java.awt.Color(255, 255, 255, 50));

        lblTitulo3.setBackground(new java.awt.Color(0, 0, 0));
        lblTitulo3.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        lblTitulo3.setForeground(new java.awt.Color(255, 255, 255));
        lblTitulo3.setText("LISTA FRUTAS");

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(lblTitulo3)
                .addContainerGap(443, Short.MAX_VALUE))
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel14Layout.createSequentialGroup()
                .addContainerGap(9, Short.MAX_VALUE)
                .addComponent(lblTitulo3)
                .addContainerGap())
        );

        ListadoFrutas.add(jPanel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 540, 30));

        tbeStockFrutas.setBackground(new java.awt.Color(255, 255, 255));
        tbeStockFrutas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Producto", "Precio", "Stock Kg"
            }
        ));
        tbeStockFrutas.setFocusable(false);
        tbeStockFrutas.setRowHeight(23);
        tbeStockFrutas.setSelectionBackground(new java.awt.Color(204, 28, 66));
        tbeStockFrutas.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(tbeStockFrutas);

        ListadoFrutas.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 520, 210));

        JPanel.add(ListadoFrutas, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, 260));

        ListadoVerduras.setBackground(new java.awt.Color(51, 204, 255));
        ListadoVerduras.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel15.setBackground(new java.awt.Color(255, 255, 255, 50));

        lblTitulo4.setBackground(new java.awt.Color(0, 0, 0));
        lblTitulo4.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        lblTitulo4.setForeground(new java.awt.Color(255, 255, 255));
        lblTitulo4.setText("LISTA VERDURAS");

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(lblTitulo4)
                .addContainerGap(426, Short.MAX_VALUE))
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel15Layout.createSequentialGroup()
                .addContainerGap(9, Short.MAX_VALUE)
                .addComponent(lblTitulo4)
                .addContainerGap())
        );

        ListadoVerduras.add(jPanel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 540, 30));

        tbeStockVerduras.setBackground(new java.awt.Color(255, 255, 255));
        tbeStockVerduras.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Producto", "Precio", "Stock Kg"
            }
        ));
        tbeStockVerduras.setFocusable(false);
        tbeStockVerduras.setRowHeight(23);
        tbeStockVerduras.setSelectionBackground(new java.awt.Color(204, 28, 66));
        tbeStockVerduras.getTableHeader().setReorderingAllowed(false);
        jScrollPane3.setViewportView(tbeStockVerduras);

        ListadoVerduras.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 520, 210));

        JPanel.add(ListadoVerduras, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, 540, 260));

        jPanel16.setBackground(new java.awt.Color(4, 224, 190));

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 210, Short.MAX_VALUE)
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        JPanel.add(jPanel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 70, 210, 10));

        jPanel17.setBackground(new java.awt.Color(4, 224, 190));

        javax.swing.GroupLayout jPanel17Layout = new javax.swing.GroupLayout(jPanel17);
        jPanel17.setLayout(jPanel17Layout);
        jPanel17Layout.setHorizontalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 210, Short.MAX_VALUE)
        );
        jPanel17Layout.setVerticalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );

        JPanel.add(jPanel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 343, 210, 5));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 650, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtExitMouseClicked
        if (usuario.getTipoUsuario().equals("Adm")) {
            MenuAdministrador menu = new MenuAdministrador(usuario);
            menu.setVisible(true);
            dispose();
        } else if (usuario.getTipoUsuario().equals("Ven")) {
            MenuVendedor menu = new MenuVendedor(usuario);
            menu.setVisible(true);
            dispose();
        }
    }//GEN-LAST:event_txtExitMouseClicked

    private void txtExitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtExitMouseEntered
        btnExit.setBackground(new Color(230, 0, 0));
        txtExit.setForeground(Color.white);
    }//GEN-LAST:event_txtExitMouseEntered

    private void txtExitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtExitMouseExited
        btnExit.setBackground(new Color(231, 255, 255));
        txtExit.setForeground(Color.black);
    }//GEN-LAST:event_txtExitMouseExited

    private void BarraTituloMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BarraTituloMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_BarraTituloMouseDragged

    private void BarraTituloMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BarraTituloMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_BarraTituloMousePressed

    private void txtBuscadorFrutasMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtBuscadorFrutasMousePressed
        if (txtBuscadorFrutas.getText().equals("Buscar por nombre...")) {
            txtBuscadorFrutas.setText("");
            txtBuscadorFrutas.setForeground(Color.black);
        }
    }//GEN-LAST:event_txtBuscadorFrutasMousePressed

    private void lblBuscarFrutaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBuscarFrutaMouseClicked
        String buscar = null;
        if (txtBuscadorFrutas.getText().isEmpty() || txtBuscadorFrutas.getText().equals("Buscar por nombre...")) {
            JOptionPane.showMessageDialog(this, "Ingrese el producto que desea buscar.");
        } else {
            buscar = "%" + txtBuscadorFrutas.getText() + "%";
            try {
                tbeStockFrutas.setModel(Sistema.getInstance().buscarFruta(buscar));
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(Almacen.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(Almacen.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(Almacen.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_lblBuscarFrutaMouseClicked

    private void lblBuscarFrutaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBuscarFrutaMouseEntered
        btnBuscarFruta.setBackground(new Color(255, 147, 178));
    }//GEN-LAST:event_lblBuscarFrutaMouseEntered

    private void lblBuscarFrutaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBuscarFrutaMouseExited
        btnBuscarFruta.setBackground(new Color(255, 77, 123));
    }//GEN-LAST:event_lblBuscarFrutaMouseExited

    private void lblVerFrutasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblVerFrutasMouseClicked
        try {
            tbeStockFrutas.setModel(Sistema.getInstance().stockFrutas());
            txtBuscadorFrutas.setText("Buscar por nombre...");
            txtBuscadorFrutas.setForeground(new Color(204, 204, 204));
            lblBuscarFruta.requestFocus();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Almacen.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Almacen.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(Almacen.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_lblVerFrutasMouseClicked

    private void lblVerFrutasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblVerFrutasMouseEntered
        btnVerFrutas.setBackground(new Color(255, 147, 178));
    }//GEN-LAST:event_lblVerFrutasMouseEntered

    private void lblVerFrutasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblVerFrutasMouseExited
        btnVerFrutas.setBackground(new Color(255, 77, 123));
    }//GEN-LAST:event_lblVerFrutasMouseExited

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        if (txtBuscadorFrutas.getText().isEmpty()) {
            txtBuscadorFrutas.setText("Buscar por nombre...");
            txtBuscadorFrutas.setForeground(new Color(204, 204, 204));
        } else if (txtBuscadorVerduras.getText().isEmpty()) {
            txtBuscadorVerduras.setText("Buscar por nombre...");
            txtBuscadorVerduras.setForeground(new Color(204, 204, 204));
        }
    }//GEN-LAST:event_formMouseClicked

    private void txtBuscadorVerdurasMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtBuscadorVerdurasMousePressed
        if (txtBuscadorVerduras.getText().equals("Buscar por nombre...")) {
            txtBuscadorVerduras.setText("");
            txtBuscadorVerduras.setForeground(Color.black);
        }
    }//GEN-LAST:event_txtBuscadorVerdurasMousePressed

    private void lblBuscarVerduraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBuscarVerduraMouseClicked
        String buscar = null;
        if (txtBuscadorVerduras.getText().isEmpty() || txtBuscadorVerduras.getText().equals("Buscar por nombre...")) {
            JOptionPane.showMessageDialog(this, "Ingrese el producto que desea buscar.");
        } else {
            buscar = "%" + txtBuscadorVerduras.getText() + "%";
            try {
                tbeStockVerduras.setModel(Sistema.getInstance().buscarVerdura(buscar));
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(Almacen.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(Almacen.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(Almacen.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_lblBuscarVerduraMouseClicked

    private void lblBuscarVerduraMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBuscarVerduraMouseEntered
        btnBuscarVerdura.setBackground(new Color(255, 147, 178));        // TODO add your handling code here:
    }//GEN-LAST:event_lblBuscarVerduraMouseEntered

    private void lblBuscarVerduraMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBuscarVerduraMouseExited
        btnBuscarVerdura.setBackground(new Color(255, 77, 123));
    }//GEN-LAST:event_lblBuscarVerduraMouseExited

    private void lblVerVerdurasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblVerVerdurasMouseClicked
        try {
            tbeStockVerduras.setModel(Sistema.getInstance().stockVerduras());
            txtBuscadorVerduras.setText("Buscar por nombre...");
            txtBuscadorVerduras.setForeground(new Color(204, 204, 204));
            lblBuscarVerdura.requestFocus();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Almacen.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Almacen.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(Almacen.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_lblVerVerdurasMouseClicked

    private void lblVerVerdurasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblVerVerdurasMouseEntered
        btnVerVerduras.setBackground(new Color(255, 147, 178));
    }//GEN-LAST:event_lblVerVerdurasMouseEntered

    private void lblVerVerdurasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblVerVerdurasMouseExited
        btnVerVerduras.setBackground(new Color(255, 77, 123));
    }//GEN-LAST:event_lblVerVerdurasMouseExited

    private void lblAtrasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAtrasMouseClicked
        if (usuario.getTipoUsuario().equals("Adm")) {
            MenuAdministrador menu = new MenuAdministrador(usuario);
            menu.setVisible(true);
            dispose();
        } else if (usuario.getTipoUsuario().equals("Ven")) {
            MenuVendedor menu = new MenuVendedor(usuario);
            menu.setVisible(true);
            dispose();
        }
    }//GEN-LAST:event_lblAtrasMouseClicked

    private void lblAtrasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAtrasMouseEntered
        btnAtras.setBackground(new Color(55, 86, 103));
    }//GEN-LAST:event_lblAtrasMouseEntered

    private void lblAtrasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAtrasMouseExited
        btnAtras.setBackground(new Color(42, 72, 89));
    }//GEN-LAST:event_lblAtrasMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Stock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Stock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Stock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Stock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Stock().setVisible(true);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(Stock.class.getName()).log(Level.SEVERE, null, ex);
                } catch (SQLException ex) {
                    Logger.getLogger(Stock.class.getName()).log(Level.SEVERE, null, ex);
                } catch (IOException ex) {
                    Logger.getLogger(Stock.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BarraTitulo;
    private javax.swing.JPanel JPanel;
    private javax.swing.JPanel ListadoFrutas;
    private javax.swing.JPanel ListadoVerduras;
    private javax.swing.JPanel btnAtras;
    private javax.swing.JPanel btnBuscarFruta;
    private javax.swing.JPanel btnBuscarVerdura;
    private javax.swing.JPanel btnExit;
    private javax.swing.JPanel btnVerFrutas;
    private javax.swing.JPanel btnVerVerduras;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblAtras;
    private javax.swing.JLabel lblBuscarFruta;
    private javax.swing.JLabel lblBuscarVerdura;
    private javax.swing.JLabel lblIcono2;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblTitulo3;
    private javax.swing.JLabel lblTitulo4;
    private javax.swing.JLabel lblTitulo5;
    private javax.swing.JLabel lblVerFrutas;
    private javax.swing.JLabel lblVerVerduras;
    private javax.swing.JTable tbeStockFrutas;
    private javax.swing.JTable tbeStockVerduras;
    private javax.swing.JTextField txtBuscadorFrutas;
    private javax.swing.JTextField txtBuscadorVerduras;
    private javax.swing.JLabel txtExit;
    // End of variables declaration//GEN-END:variables
}
