/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package grafica;

import java.awt.Color;
import java.awt.Font;
import java.io.IOException;
import java.lang.System.Logger;
import java.lang.System.Logger.Level;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import logica.Sistema;
import logica.Suministrador;
import logica.Usuario;

/**
 *
 * @author Franco
 */
public class Suministradores extends javax.swing.JFrame {

    int xMouse, yMouse;
    Usuario usuario;

    public Suministradores() throws ClassNotFoundException, SQLException, IOException {
        initComponents();
        this.setLocationRelativeTo(null);
        txtNombreSuministrador.requestFocus();
        tbeListado_Suministradores.setModel(Sistema.getInstance().mostrarListadoSuministradores());
        tbeListado_Suministradores.setBackground(Color.white);
        tbeListado_Suministradores.getTableHeader().setFont(new Font("Seoge UI", Font.BOLD, 12));
        tbeListado_Suministradores.getTableHeader().setOpaque(false);
        tbeListado_Suministradores.getTableHeader().setBackground(new Color(32, 136, 203));
        tbeListado_Suministradores.getTableHeader().setForeground(new Color(0, 0, 0));
        lblActualizar.setEnabled(false);
    }

    public Suministradores(Usuario usuario) throws ClassNotFoundException, SQLException, IOException {
        initComponents();
        this.usuario = usuario;
        this.setLocationRelativeTo(null);
        txtNombreSuministrador.requestFocus();
        tbeListado_Suministradores.setModel(Sistema.getInstance().mostrarListadoSuministradores());
        tbeListado_Suministradores.setBackground(Color.white);
        tbeListado_Suministradores.getTableHeader().setFont(new Font("Seoge UI", Font.BOLD, 12));
        tbeListado_Suministradores.getTableHeader().setOpaque(false);
        tbeListado_Suministradores.getTableHeader().setBackground(new Color(32, 136, 203));
        tbeListado_Suministradores.getTableHeader().setForeground(new Color(0, 0, 0));
        lblActualizar.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        RegistroSuministradores = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lblTitulo2 = new javax.swing.JLabel();
        txtNombreSuministrador = new javax.swing.JTextField();
        txtDireccion = new javax.swing.JTextField();
        txtTelefono = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        jPanel11 = new javax.swing.JPanel();
        ListadoSuministradores = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbeListado_Suministradores = new javax.swing.JTable();
        lblTitulo3 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        lblTitulo5 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        lblAcciones = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        btnRegistrar = new javax.swing.JPanel();
        lblRegistrar = new javax.swing.JLabel();
        btnLimpiar = new javax.swing.JPanel();
        lblLimpiar = new javax.swing.JLabel();
        btnActualizar = new javax.swing.JPanel();
        lblActualizar = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btnModificar = new javax.swing.JPanel();
        lblModificar = new javax.swing.JLabel();
        btnEliminar = new javax.swing.JPanel();
        lblEliminar = new javax.swing.JLabel();
        btnAtras = new javax.swing.JPanel();
        lblAtras = new javax.swing.JLabel();
        BarraTitulo = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        btnExit = new javax.swing.JPanel();
        txtExit = new javax.swing.JLabel();
        lblIcono2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Suministradores");
        setMaximumSize(new java.awt.Dimension(750, 625));
        setMinimumSize(new java.awt.Dimension(750, 625));
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(231, 255, 255));
        jPanel1.setMaximumSize(new java.awt.Dimension(980, 630));
        jPanel1.setMinimumSize(new java.awt.Dimension(980, 630));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        RegistroSuministradores.setBackground(new java.awt.Color(51, 204, 255));
        RegistroSuministradores.setForeground(new java.awt.Color(204, 204, 204));
        RegistroSuministradores.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Roboto Light", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Nombre:");
        RegistroSuministradores.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, -1, -1));

        jLabel3.setFont(new java.awt.Font("Roboto Light", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Dirección:");
        RegistroSuministradores.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, -1, -1));

        jLabel4.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Email:");
        RegistroSuministradores.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, -1, -1));

        jLabel7.setFont(new java.awt.Font("Roboto Light", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Teléfono:");
        RegistroSuministradores.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, -1, -1));

        lblTitulo2.setBackground(new java.awt.Color(0, 0, 0));
        lblTitulo2.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        lblTitulo2.setForeground(new java.awt.Color(255, 255, 255));
        lblTitulo2.setText("REGISTRAR/ACTUALIZAR SUMINISTRADOR");
        RegistroSuministradores.add(lblTitulo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, -1, -1));
        RegistroSuministradores.add(txtNombreSuministrador, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 50, 300, -1));
        RegistroSuministradores.add(txtDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 90, 300, -1));
        RegistroSuministradores.add(txtTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 130, 140, -1));
        RegistroSuministradores.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 170, 300, -1));

        jPanel11.setBackground(new java.awt.Color(255, 255, 255, 50));

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 520, Short.MAX_VALUE)
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        RegistroSuministradores.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 520, 30));

        jPanel1.add(RegistroSuministradores, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 520, 250));

        ListadoSuministradores.setBackground(new java.awt.Color(51, 204, 255));
        ListadoSuministradores.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tbeListado_Suministradores.setBackground(new java.awt.Color(255, 255, 255));
        tbeListado_Suministradores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tbeListado_Suministradores.setFocusable(false);
        tbeListado_Suministradores.setRowHeight(23);
        tbeListado_Suministradores.setSelectionBackground(new java.awt.Color(204, 28, 66));
        tbeListado_Suministradores.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tbeListado_Suministradores);

        ListadoSuministradores.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 500, 220));

        lblTitulo3.setBackground(new java.awt.Color(0, 0, 0));
        lblTitulo3.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        lblTitulo3.setForeground(new java.awt.Color(255, 255, 255));
        lblTitulo3.setText("LISTA SUMINISTRADORES");
        ListadoSuministradores.add(lblTitulo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jPanel12.setBackground(new java.awt.Color(255, 255, 255, 50));

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 520, Short.MAX_VALUE)
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        ListadoSuministradores.add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 520, 30));

        jPanel1.add(ListadoSuministradores, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, -1, 270));

        jPanel9.setBackground(new java.awt.Color(21, 47, 62));

        lblTitulo5.setBackground(new java.awt.Color(0, 0, 0));
        lblTitulo5.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        lblTitulo5.setForeground(new java.awt.Color(255, 255, 255));
        lblTitulo5.setText("Gestión de Suministradores");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 540, Short.MAX_VALUE)
            .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel9Layout.createSequentialGroup()
                    .addGap(0, 120, Short.MAX_VALUE)
                    .addComponent(lblTitulo5)
                    .addGap(0, 121, Short.MAX_VALUE)))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
            .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel9Layout.createSequentialGroup()
                    .addGap(0, 5, Short.MAX_VALUE)
                    .addComponent(lblTitulo5)
                    .addGap(0, 6, Short.MAX_VALUE)))
        );

        jPanel1.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 540, 40));

        jPanel7.setBackground(new java.awt.Color(4, 224, 190));

        lblAcciones.setBackground(new java.awt.Color(255, 126, 164));
        lblAcciones.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        lblAcciones.setForeground(new java.awt.Color(255, 255, 255));
        lblAcciones.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAcciones.setText("Acciones");
        lblAcciones.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lblAcciones.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblAccionesMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblAccionesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblAccionesMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblAcciones, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblAcciones, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 30, 210, 40));

        jPanel8.setBackground(new java.awt.Color(21, 47, 62));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnRegistrar.setBackground(new java.awt.Color(255, 77, 123));

        lblRegistrar.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        lblRegistrar.setForeground(new java.awt.Color(255, 255, 255));
        lblRegistrar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRegistrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/grafica/Imagenes/icons8_create_20px_1.png"))); // NOI18N
        lblRegistrar.setText("REGISTRAR");
        lblRegistrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblRegistrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblRegistrarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblRegistrarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblRegistrarMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnRegistrarLayout = new javax.swing.GroupLayout(btnRegistrar);
        btnRegistrar.setLayout(btnRegistrarLayout);
        btnRegistrarLayout.setHorizontalGroup(
            btnRegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblRegistrar, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
        );
        btnRegistrarLayout.setVerticalGroup(
            btnRegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnRegistrarLayout.createSequentialGroup()
                .addComponent(lblRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel8.add(btnRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 40, 120, -1));

        btnLimpiar.setBackground(new java.awt.Color(255, 77, 123));

        lblLimpiar.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        lblLimpiar.setForeground(new java.awt.Color(255, 255, 255));
        lblLimpiar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLimpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/grafica/Imagenes/icons8_eraser_20px.png"))); // NOI18N
        lblLimpiar.setText("LIMPIAR");
        lblLimpiar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblLimpiar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblLimpiarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblLimpiarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblLimpiarMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnLimpiarLayout = new javax.swing.GroupLayout(btnLimpiar);
        btnLimpiar.setLayout(btnLimpiarLayout);
        btnLimpiarLayout.setHorizontalGroup(
            btnLimpiarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblLimpiar, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
        );
        btnLimpiarLayout.setVerticalGroup(
            btnLimpiarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnLimpiarLayout.createSequentialGroup()
                .addComponent(lblLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel8.add(btnLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 110, 120, -1));

        btnActualizar.setBackground(new java.awt.Color(255, 176, 199));

        lblActualizar.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        lblActualizar.setForeground(new java.awt.Color(255, 255, 255));
        lblActualizar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblActualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/grafica/Imagenes/icons8_refresh_20px.png"))); // NOI18N
        lblActualizar.setText("ACTUALIZAR");
        lblActualizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblActualizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblActualizarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblActualizarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblActualizarMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnActualizarLayout = new javax.swing.GroupLayout(btnActualizar);
        btnActualizar.setLayout(btnActualizarLayout);
        btnActualizarLayout.setHorizontalGroup(
            btnActualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblActualizar, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
        );
        btnActualizarLayout.setVerticalGroup(
            btnActualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnActualizarLayout.createSequentialGroup()
                .addComponent(lblActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel8.add(btnActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 180, 120, -1));

        jPanel1.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 70, 210, 260));

        jPanel13.setBackground(new java.awt.Color(4, 224, 190));

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 210, Short.MAX_VALUE)
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 330, 210, 5));

        jPanel2.setBackground(new java.awt.Color(21, 47, 62));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnModificar.setBackground(new java.awt.Color(255, 77, 123));

        lblModificar.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        lblModificar.setForeground(new java.awt.Color(255, 255, 255));
        lblModificar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblModificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/grafica/Imagenes/icons8_edit_20px_2.png"))); // NOI18N
        lblModificar.setText("MODIFICAR");
        lblModificar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblModificar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblModificarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblModificarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblModificarMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnModificarLayout = new javax.swing.GroupLayout(btnModificar);
        btnModificar.setLayout(btnModificarLayout);
        btnModificarLayout.setHorizontalGroup(
            btnModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblModificar, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
        );
        btnModificarLayout.setVerticalGroup(
            btnModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnModificarLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel2.add(btnModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, -1, -1));

        btnEliminar.setBackground(new java.awt.Color(255, 77, 123));

        lblEliminar.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        lblEliminar.setForeground(new java.awt.Color(255, 255, 255));
        lblEliminar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/grafica/Imagenes/icons8_minus_20px.png"))); // NOI18N
        lblEliminar.setText("ELIMINAR");
        lblEliminar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblEliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblEliminarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblEliminarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblEliminarMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnEliminarLayout = new javax.swing.GroupLayout(btnEliminar);
        btnEliminar.setLayout(btnEliminarLayout);
        btnEliminarLayout.setHorizontalGroup(
            btnEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
        );
        btnEliminarLayout.setVerticalGroup(
            btnEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnEliminarLayout.createSequentialGroup()
                .addComponent(lblEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel2.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, -1, -1));

        btnAtras.setBackground(new java.awt.Color(42, 72, 89));

        lblAtras.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        lblAtras.setForeground(new java.awt.Color(255, 255, 255));
        lblAtras.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAtras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/grafica/Imagenes/icons8_left_20px.png"))); // NOI18N
        lblAtras.setText("ATRÁS");
        lblAtras.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblAtras.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblAtrasMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblAtrasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblAtrasMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnAtrasLayout = new javax.swing.GroupLayout(btnAtras);
        btnAtras.setLayout(btnAtrasLayout);
        btnAtrasLayout.setHorizontalGroup(
            btnAtrasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblAtras, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
        );
        btnAtrasLayout.setVerticalGroup(
            btnAtrasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblAtras, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
        );

        jPanel2.add(btnAtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 240, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 335, 210, 290));

        BarraTitulo.setBackground(new java.awt.Color(231, 255, 255));
        BarraTitulo.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                BarraTituloMouseDragged(evt);
            }
        });
        BarraTitulo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BarraTituloMousePressed(evt);
            }
        });
        BarraTitulo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitulo.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(153, 153, 153));
        lblTitulo.setText("Almacén - Suministradores");
        BarraTitulo.add(lblTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 8, -1, -1));

        btnExit.setBackground(new java.awt.Color(231, 255, 255));
        btnExit.setForeground(new java.awt.Color(255, 255, 255));
        btnExit.setMaximumSize(new java.awt.Dimension(30, 30));
        btnExit.setMinimumSize(new java.awt.Dimension(30, 30));
        btnExit.setPreferredSize(new java.awt.Dimension(30, 30));
        btnExit.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtExit.setBackground(new java.awt.Color(51, 51, 51));
        txtExit.setFont(new java.awt.Font("Roboto Light", 1, 24)); // NOI18N
        txtExit.setForeground(new java.awt.Color(0, 0, 0));
        txtExit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtExit.setText("X");
        txtExit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtExitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtExitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtExitMouseExited(evt);
            }
        });
        btnExit.add(txtExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 35, 30));

        BarraTitulo.add(btnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(715, 0, 35, 30));

        lblIcono2.setBackground(new java.awt.Color(51, 51, 51));
        lblIcono2.setFont(new java.awt.Font("Roboto Light", 1, 24)); // NOI18N
        lblIcono2.setForeground(new java.awt.Color(0, 0, 0));
        lblIcono2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblIcono2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/grafica/Imagenes/Icono 15px.png"))); // NOI18N
        lblIcono2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        BarraTitulo.add(lblIcono2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 35, 30));

        jPanel1.add(BarraTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 750, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblRegistrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRegistrarMouseClicked
        String nombreSuministrador = txtDireccion.getText();
        String direccion = txtDireccion.getText();
        String telefono = txtTelefono.getText();
        String email = txtEmail.getText();

        Suministrador suministrador = new Suministrador(nombreSuministrador, direccion, telefono, email);

        if (lblRegistrar.isEnabled()) {
            if (nombreSuministrador.isEmpty() || direccion.isEmpty() || telefono.isEmpty() || email.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Verifique los campos obligatorios.");
            } else if (telefono.length() != 8 || !telefono.matches("[0-9]+")) {
                JOptionPane.showMessageDialog(this, "Teléfono inválido, verifique el campo.");
            } else try {
                if (Sistema.getInstance().registrarSuministrador(suministrador)) {
                    JOptionPane.showMessageDialog(this, "¡Se registró correctamente!");
                } else {
                    JOptionPane.showMessageDialog(this, "Error! No se puedo registrar.");
                }
            } catch (ClassNotFoundException ex) {
                java.util.logging.Logger.getLogger(Suministradores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                java.util.logging.Logger.getLogger(Suministradores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            } catch (IOException ex) {
                java.util.logging.Logger.getLogger(Suministradores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            }
            try {
                tbeListado_Suministradores.setModel(Sistema.getInstance().mostrarListadoSuministradores());
            } catch (ClassNotFoundException ex) {
                java.util.logging.Logger.getLogger(Suministradores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                java.util.logging.Logger.getLogger(Suministradores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            } catch (IOException ex) {
                java.util.logging.Logger.getLogger(Suministradores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_lblRegistrarMouseClicked

    private void lblRegistrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRegistrarMouseEntered
        if (lblRegistrar.isEnabled()) {
            btnRegistrar.setBackground(new Color(255, 147, 178));
        }
    }//GEN-LAST:event_lblRegistrarMouseEntered

    private void lblRegistrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRegistrarMouseExited
        if (lblRegistrar.isEnabled()) {
            btnRegistrar.setBackground(new Color(255, 77, 123));
        }
    }//GEN-LAST:event_lblRegistrarMouseExited

    private void lblLimpiarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLimpiarMouseClicked
        txtNombreSuministrador.setText("");
        txtDireccion.setText("");
        txtTelefono.setText("");
        txtEmail.setText("");
        txtNombreSuministrador.requestFocus();
        lblRegistrar.setEnabled(true);
        btnRegistrar.setBackground(new Color(255, 77, 123));
        lblActualizar.setEnabled(false);
        btnActualizar.setBackground(new Color(255, 176, 199));
        tbeListado_Suministradores.setEnabled(true);
    }//GEN-LAST:event_lblLimpiarMouseClicked

    private void lblLimpiarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLimpiarMouseEntered
        btnLimpiar.setBackground(new Color(255, 147, 178));
    }//GEN-LAST:event_lblLimpiarMouseEntered

    private void lblLimpiarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLimpiarMouseExited
        btnLimpiar.setBackground(new Color(255, 77, 123));
    }//GEN-LAST:event_lblLimpiarMouseExited

    private void lblActualizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblActualizarMouseClicked
    if (lblActualizar.isEnabled()) {
        int filaSeleccionada = tbeListado_Suministradores.getSelectedRow();

        String nombre = txtNombreSuministrador.getText();
        String direccion = txtDireccion.getText();
        String telefono = txtTelefono.getText();
        String email = txtEmail.getText();
        String id = String.valueOf(tbeListado_Suministradores.getValueAt(filaSeleccionada, 0));

        Suministrador suministrador = new Suministrador(nombre, direccion, telefono, email);

        
            if (nombre.isEmpty() || direccion.isEmpty() || telefono.isEmpty() || email.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Verifique los campos obligatorios.");
            } else if (telefono.length() != 8 || !telefono.matches("[0-9]+")) {
                JOptionPane.showMessageDialog(this, "Teléfono inválido, verifique el campo.");
            } else try {
                if (Sistema.getInstance().actualizarSuministrador(suministrador, id)) {
                    JOptionPane.showMessageDialog(this, "¡Se actualizó correctamente!");
                    txtNombreSuministrador.setText("");
                    txtDireccion.setText("");
                    txtTelefono.setText("");
                    txtEmail.setText("");
                    txtNombreSuministrador.requestFocus();
                    lblRegistrar.setEnabled(true);
                    btnRegistrar.setBackground(new Color(255, 77, 123));
                    lblActualizar.setEnabled(false);
                    btnActualizar.setBackground(new Color(255, 176, 199));
                    tbeListado_Suministradores.setEnabled(true);
                } else {
                    JOptionPane.showMessageDialog(this, "Error! No se puedo actualizar.");
                }
            } catch (ClassNotFoundException ex) {
                java.util.logging.Logger.getLogger(Suministradores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                java.util.logging.Logger.getLogger(Suministradores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            } catch (IOException ex) {
                java.util.logging.Logger.getLogger(Suministradores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            }
            try {
                tbeListado_Suministradores.setModel(Sistema.getInstance().mostrarListadoSuministradores());
            } catch (ClassNotFoundException ex) {
                java.util.logging.Logger.getLogger(Suministradores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                java.util.logging.Logger.getLogger(Suministradores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            } catch (IOException ex) {
                java.util.logging.Logger.getLogger(Suministradores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_lblActualizarMouseClicked

    private void lblActualizarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblActualizarMouseEntered
        if (lblActualizar.isEnabled()) {
            btnActualizar.setBackground(new Color(255, 147, 178));
        }
    }//GEN-LAST:event_lblActualizarMouseEntered

    private void lblActualizarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblActualizarMouseExited
        if (lblActualizar.isEnabled()) {
            btnActualizar.setBackground(new Color(255, 77, 123));
        }
    }//GEN-LAST:event_lblActualizarMouseExited

    private void lblModificarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblModificarMouseClicked

        int filaSeleccionada = tbeListado_Suministradores.getSelectedRow();

        if (filaSeleccionada == -1) {
            JOptionPane.showMessageDialog(this, "Seleccione el suministrador que desea modificar...");
        } else {
            lblActualizar.setEnabled(true);
            btnActualizar.setBackground(new Color(255, 77, 123));
            lblRegistrar.setEnabled(false);
            btnRegistrar.setBackground(new Color(255, 176, 199));
            txtNombreSuministrador.setText(String.valueOf(tbeListado_Suministradores.getValueAt(filaSeleccionada, 1)));
            txtDireccion.setText(String.valueOf(tbeListado_Suministradores.getValueAt(filaSeleccionada, 2)));
            txtTelefono.setText(String.valueOf(tbeListado_Suministradores.getValueAt(filaSeleccionada, 3)));
            txtEmail.setText(String.valueOf(tbeListado_Suministradores.getValueAt(filaSeleccionada, 4)));
            tbeListado_Suministradores.setEnabled(false);
        }

    }//GEN-LAST:event_lblModificarMouseClicked

    private void lblModificarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblModificarMouseEntered
        btnModificar.setBackground(new Color(255, 147, 178));
    }//GEN-LAST:event_lblModificarMouseEntered

    private void lblModificarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblModificarMouseExited
        btnModificar.setBackground(new Color(255, 77, 123));
    }//GEN-LAST:event_lblModificarMouseExited

    private void lblEliminarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblEliminarMouseClicked
        int filaSeleccionada = tbeListado_Suministradores.getSelectedRow();
        String id = null;
        String nombreSuministrador = null;
        if (filaSeleccionada == -1) {
            JOptionPane.showMessageDialog(this, "Seleccione el suministrador que desea eliminar...");
        } else {
            id = String.valueOf(tbeListado_Suministradores.getValueAt(filaSeleccionada, 0));
            nombreSuministrador = String.valueOf(tbeListado_Suministradores.getValueAt(filaSeleccionada, 1));
            int confirmacion = JOptionPane.showConfirmDialog(null, "¿Desea eliminar el suministrador: " + nombreSuministrador + "?", "Confirmación de eliminación...", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
            if (confirmacion == 0) {
                try {
                    if (Sistema.getInstance().eliminarSuministrador(id)) {
                        JOptionPane.showMessageDialog(this, "Se ha elmininado correctamente.");
                    } else {
                        JOptionPane.showMessageDialog(this, "Se ha producido un error, intente nuevamente.");
                    }
                } catch (ClassNotFoundException ex) {
                    java.util.logging.Logger.getLogger(Suministradores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                } catch (SQLException ex) {
                    java.util.logging.Logger.getLogger(Suministradores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                } catch (IOException ex) {
                    java.util.logging.Logger.getLogger(Suministradores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                }
            }
            try {
                tbeListado_Suministradores.setModel(Sistema.getInstance().mostrarListadoSuministradores());
            } catch (ClassNotFoundException ex) {
                java.util.logging.Logger.getLogger(Suministradores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                java.util.logging.Logger.getLogger(Suministradores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            } catch (IOException ex) {
                java.util.logging.Logger.getLogger(Suministradores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_lblEliminarMouseClicked

    private void lblEliminarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblEliminarMouseEntered
        btnEliminar.setBackground(new Color(255, 147, 178));
    }//GEN-LAST:event_lblEliminarMouseEntered

    private void lblEliminarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblEliminarMouseExited
        btnEliminar.setBackground(new Color(255, 77, 123));
    }//GEN-LAST:event_lblEliminarMouseExited

    private void lblAccionesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAccionesMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblAccionesMouseClicked

    private void lblAccionesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAccionesMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_lblAccionesMouseEntered

    private void lblAccionesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAccionesMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_lblAccionesMouseExited

    private void lblAtrasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAtrasMouseClicked
        MenuAdministrador menu = new MenuAdministrador(usuario);
        menu.setVisible(true);
        dispose();
    }//GEN-LAST:event_lblAtrasMouseClicked

    private void lblAtrasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAtrasMouseEntered
        btnAtras.setBackground(new Color(55, 86, 103));
    }//GEN-LAST:event_lblAtrasMouseEntered

    private void lblAtrasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAtrasMouseExited
        btnAtras.setBackground(new Color(42, 72, 89));
    }//GEN-LAST:event_lblAtrasMouseExited

    private void txtExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtExitMouseClicked
        MenuAdministrador menu = new MenuAdministrador(usuario);
        menu.setVisible(true);
        dispose();
    }//GEN-LAST:event_txtExitMouseClicked

    private void txtExitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtExitMouseEntered
        btnExit.setBackground(new Color(230, 0, 0));
        txtExit.setForeground(Color.white);
    }//GEN-LAST:event_txtExitMouseEntered

    private void txtExitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtExitMouseExited
        btnExit.setBackground(new Color(231, 255, 255));
        txtExit.setForeground(Color.black);
    }//GEN-LAST:event_txtExitMouseExited

    private void BarraTituloMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BarraTituloMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_BarraTituloMouseDragged

    private void BarraTituloMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BarraTituloMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_BarraTituloMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Suministradores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Suministradores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Suministradores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Suministradores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Suministradores().setVisible(true);
                } catch (ClassNotFoundException ex) {
                    java.util.logging.Logger.getLogger(Suministradores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                } catch (SQLException ex) {
                    java.util.logging.Logger.getLogger(Suministradores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                } catch (IOException ex) {
                    java.util.logging.Logger.getLogger(Suministradores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BarraTitulo;
    private javax.swing.JPanel ListadoSuministradores;
    private javax.swing.JPanel RegistroSuministradores;
    private javax.swing.JPanel btnActualizar;
    private javax.swing.JPanel btnAtras;
    private javax.swing.JPanel btnEliminar;
    private javax.swing.JPanel btnExit;
    private javax.swing.JPanel btnLimpiar;
    private javax.swing.JPanel btnModificar;
    private javax.swing.JPanel btnRegistrar;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAcciones;
    private javax.swing.JLabel lblActualizar;
    private javax.swing.JLabel lblAtras;
    private javax.swing.JLabel lblEliminar;
    private javax.swing.JLabel lblIcono2;
    private javax.swing.JLabel lblLimpiar;
    private javax.swing.JLabel lblModificar;
    private javax.swing.JLabel lblRegistrar;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblTitulo2;
    private javax.swing.JLabel lblTitulo3;
    private javax.swing.JLabel lblTitulo5;
    private javax.swing.JTable tbeListado_Suministradores;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JLabel txtExit;
    private javax.swing.JTextField txtNombreSuministrador;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
