/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package grafica;

import java.awt.Color;
import java.awt.Font;
import java.io.IOException;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import logica.Sistema;
import logica.Usuario;

/**
 *
 * @author Franco
 */
public class Usuarios extends javax.swing.JFrame {

    int xMouse, yMouse;
    Usuario usuario;

    public Usuarios() throws SQLException, ClassNotFoundException, IOException {
        initComponents();
        this.setLocationRelativeTo(null);
        tbeListado_Usuarios.setModel(Sistema.getInstance().mostrarListadoUsuarios());
        tbeListado_Usuarios.setBackground(Color.white);
        tbeListado_Usuarios.getTableHeader().setFont(new Font("Seoge UI", Font.BOLD, 12));
        tbeListado_Usuarios.getTableHeader().setOpaque(false);
        tbeListado_Usuarios.getTableHeader().setBackground(new Color(32, 136, 203));
        tbeListado_Usuarios.getTableHeader().setForeground(new Color(0, 0, 0));
        btnActualizar.setEnabled(false);
        lblActualizar.setEnabled(false);
    }

    public Usuarios(Usuario usuario) throws SQLException, ClassNotFoundException, IOException {
        initComponents();
        this.setLocationRelativeTo(null);
        tbeListado_Usuarios.setModel(Sistema.getInstance().mostrarListadoUsuarios());
        tbeListado_Usuarios.setBackground(Color.white);
        tbeListado_Usuarios.getTableHeader().setFont(new Font("Seoge UI", Font.BOLD, 12));
        tbeListado_Usuarios.getTableHeader().setOpaque(false);
        tbeListado_Usuarios.getTableHeader().setBackground(new Color(32, 136, 203));
        tbeListado_Usuarios.getTableHeader().setForeground(new Color(0, 0, 0));
        btnActualizar.setEnabled(false);
        lblActualizar.setEnabled(false);
        this.usuario = usuario;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rbgBuscar = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        Buscador = new javax.swing.JPanel();
        IdEmpleado = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        lblIdEmpleado = new javax.swing.JLabel();
        lblTitulo1 = new javax.swing.JLabel();
        txtBuscador = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        btnBuscar = new javax.swing.JPanel();
        lblBuscar = new javax.swing.JLabel();
        btnLimpiarBuscador = new javax.swing.JPanel();
        lblLimpiarBuscador = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        ListadoUsuarios = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbeListado_Usuarios = new javax.swing.JTable();
        lblTitulo3 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        RegistroUsuario = new javax.swing.JPanel();
        txtIdEmpleado = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cboTipo_Usuario = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        txtNuevo_Usuario = new javax.swing.JTextField();
        txtConfirmarContrasenia = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtContrasenia = new javax.swing.JTextField();
        lblTitulo2 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        btnCrear = new javax.swing.JPanel();
        lblCrear = new javax.swing.JLabel();
        btnLimpiar = new javax.swing.JPanel();
        lblLimpiar = new javax.swing.JLabel();
        btnActualizar = new javax.swing.JPanel();
        lblActualizar = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        lblTitulo5 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        lblAcciones = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        btnModificar = new javax.swing.JPanel();
        lblModificar = new javax.swing.JLabel();
        btnEliminar = new javax.swing.JPanel();
        lblEliminar = new javax.swing.JLabel();
        jPanel14 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        btnAtras = new javax.swing.JPanel();
        lblAtras = new javax.swing.JLabel();
        BarraTitulo = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        btnExit = new javax.swing.JPanel();
        txtExit = new javax.swing.JLabel();
        lblIcono4 = new javax.swing.JLabel();
        lblIcono3 = new javax.swing.JLabel();
        lblIcono2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Usuarios");
        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMaximumSize(new java.awt.Dimension(960, 610));
        setMinimumSize(new java.awt.Dimension(960, 610));
        setUndecorated(true);
        setResizable(false);
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(231, 255, 255));
        jPanel1.setForeground(new java.awt.Color(0, 102, 204));
        jPanel1.setMaximumSize(new java.awt.Dimension(980, 630));
        jPanel1.setMinimumSize(new java.awt.Dimension(980, 630));
        jPanel1.setPreferredSize(new java.awt.Dimension(980, 630));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Buscador.setBackground(new java.awt.Color(51, 204, 255));
        Buscador.setForeground(new java.awt.Color(0, 102, 255));
        Buscador.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        IdEmpleado.setBackground(new java.awt.Color(177, 234, 253));
        IdEmpleado.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("ID Empleado:");
        IdEmpleado.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        lblIdEmpleado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIdEmpleado.setText("ID");
        lblIdEmpleado.setEnabled(false);
        IdEmpleado.add(lblIdEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 50, 90, -1));

        Buscador.add(IdEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 110, 90));

        lblTitulo1.setBackground(new java.awt.Color(0, 0, 0));
        lblTitulo1.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        lblTitulo1.setForeground(new java.awt.Color(255, 255, 255));
        lblTitulo1.setText("BUSCAR EMPLEADO");
        Buscador.add(lblTitulo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, -1, -1));

        txtBuscador.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txtBuscador.setForeground(new java.awt.Color(204, 204, 204));
        txtBuscador.setText("Ingresar C.I empleado...");
        txtBuscador.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtBuscadorMousePressed(evt);
            }
        });
        txtBuscador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscadorActionPerformed(evt);
            }
        });
        Buscador.add(txtBuscador, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 250, -1));

        jPanel2.setBackground(new java.awt.Color(21, 47, 62));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnBuscar.setBackground(new java.awt.Color(255, 77, 123));

        lblBuscar.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        lblBuscar.setForeground(new java.awt.Color(255, 255, 255));
        lblBuscar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/grafica/Imagenes/icons8_search_20px.png"))); // NOI18N
        lblBuscar.setText("BUSCAR");
        lblBuscar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblBuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblBuscarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblBuscarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblBuscarMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnBuscarLayout = new javax.swing.GroupLayout(btnBuscar);
        btnBuscar.setLayout(btnBuscarLayout);
        btnBuscarLayout.setHorizontalGroup(
            btnBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
        );
        btnBuscarLayout.setVerticalGroup(
            btnBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnBuscarLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel2.add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 25, -1, -1));

        btnLimpiarBuscador.setBackground(new java.awt.Color(255, 77, 123));

        lblLimpiarBuscador.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        lblLimpiarBuscador.setForeground(new java.awt.Color(255, 255, 255));
        lblLimpiarBuscador.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLimpiarBuscador.setIcon(new javax.swing.ImageIcon(getClass().getResource("/grafica/Imagenes/icons8_eraser_20px.png"))); // NOI18N
        lblLimpiarBuscador.setText("LIMPIAR");
        lblLimpiarBuscador.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblLimpiarBuscador.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblLimpiarBuscadorMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblLimpiarBuscadorMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblLimpiarBuscadorMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnLimpiarBuscadorLayout = new javax.swing.GroupLayout(btnLimpiarBuscador);
        btnLimpiarBuscador.setLayout(btnLimpiarBuscadorLayout);
        btnLimpiarBuscadorLayout.setHorizontalGroup(
            btnLimpiarBuscadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblLimpiarBuscador, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
        );
        btnLimpiarBuscadorLayout.setVerticalGroup(
            btnLimpiarBuscadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnLimpiarBuscadorLayout.createSequentialGroup()
                .addComponent(lblLimpiarBuscador, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel2.add(btnLimpiarBuscador, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 90, 120, -1));

        Buscador.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 90, 170, 160));

        jPanel13.setBackground(new java.awt.Color(255, 255, 255, 50));

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 350, Short.MAX_VALUE)
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        Buscador.add(jPanel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 350, 30));

        jPanel1.add(Buscador, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 80, 350, 250));

        ListadoUsuarios.setBackground(new java.awt.Color(51, 204, 255));
        ListadoUsuarios.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tbeListado_Usuarios.setBackground(new java.awt.Color(255, 255, 255));
        tbeListado_Usuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tbeListado_Usuarios.setFocusable(false);
        tbeListado_Usuarios.setRowHeight(23);
        tbeListado_Usuarios.setSelectionBackground(new java.awt.Color(204, 28, 66));
        tbeListado_Usuarios.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tbeListado_Usuarios);

        ListadoUsuarios.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 410, 210));

        lblTitulo3.setBackground(new java.awt.Color(0, 0, 0));
        lblTitulo3.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        lblTitulo3.setForeground(new java.awt.Color(255, 255, 255));
        lblTitulo3.setText("LISTA USUARIOS");
        ListadoUsuarios.add(lblTitulo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jPanel12.setBackground(new java.awt.Color(255, 255, 255, 50));

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 430, Short.MAX_VALUE)
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        ListadoUsuarios.add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 430, 30));

        jPanel1.add(ListadoUsuarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, 430, 260));

        RegistroUsuario.setBackground(new java.awt.Color(51, 204, 255));
        RegistroUsuario.setForeground(new java.awt.Color(204, 204, 204));
        RegistroUsuario.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        RegistroUsuario.add(txtIdEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 210, 120, -1));

        jLabel2.setFont(new java.awt.Font("Roboto Light", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Nuevo usuario:");
        RegistroUsuario.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, -1, -1));

        jLabel3.setFont(new java.awt.Font("Roboto Light", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Nueva Contraseña:");
        RegistroUsuario.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, -1));

        jLabel4.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Tipo:");
        RegistroUsuario.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 170, -1, -1));

        cboTipo_Usuario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--------------------", "Administrador", "Vendedor" }));
        RegistroUsuario.add(cboTipo_Usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 170, 120, -1));

        jLabel5.setFont(new java.awt.Font("Roboto Light", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Empleado:");
        RegistroUsuario.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 210, -1, -1));
        RegistroUsuario.add(txtNuevo_Usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 50, 250, -1));
        RegistroUsuario.add(txtConfirmarContrasenia, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 130, 250, -1));

        jLabel7.setFont(new java.awt.Font("Roboto Light", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Confirmar Contraseña:");
        RegistroUsuario.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, -1));
        RegistroUsuario.add(txtContrasenia, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 90, 250, -1));

        lblTitulo2.setBackground(new java.awt.Color(0, 0, 0));
        lblTitulo2.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        lblTitulo2.setForeground(new java.awt.Color(255, 255, 255));
        lblTitulo2.setText("REGISTRAR/ACTUALIZAR USUARIO");
        RegistroUsuario.add(lblTitulo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, -1, -1));

        jPanel11.setBackground(new java.awt.Color(255, 255, 255, 50));

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 430, Short.MAX_VALUE)
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        RegistroUsuario.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 430, 30));

        jPanel1.add(RegistroUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 430, 250));

        jPanel3.setBackground(new java.awt.Color(21, 47, 62));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnCrear.setBackground(new java.awt.Color(255, 77, 123));

        lblCrear.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        lblCrear.setForeground(new java.awt.Color(255, 255, 255));
        lblCrear.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCrear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/grafica/Imagenes/icons8_create_20px_1.png"))); // NOI18N
        lblCrear.setText("CREAR");
        lblCrear.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblCrear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCrearMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblCrearMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblCrearMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnCrearLayout = new javax.swing.GroupLayout(btnCrear);
        btnCrear.setLayout(btnCrearLayout);
        btnCrearLayout.setHorizontalGroup(
            btnCrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblCrear, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
        );
        btnCrearLayout.setVerticalGroup(
            btnCrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnCrearLayout.createSequentialGroup()
                .addComponent(lblCrear, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel3.add(btnCrear, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 40, 120, -1));

        btnLimpiar.setBackground(new java.awt.Color(255, 77, 123));

        lblLimpiar.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        lblLimpiar.setForeground(new java.awt.Color(255, 255, 255));
        lblLimpiar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLimpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/grafica/Imagenes/icons8_eraser_20px.png"))); // NOI18N
        lblLimpiar.setText("LIMPIAR");
        lblLimpiar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblLimpiar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblLimpiarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblLimpiarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblLimpiarMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnLimpiarLayout = new javax.swing.GroupLayout(btnLimpiar);
        btnLimpiar.setLayout(btnLimpiarLayout);
        btnLimpiarLayout.setHorizontalGroup(
            btnLimpiarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblLimpiar, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
        );
        btnLimpiarLayout.setVerticalGroup(
            btnLimpiarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnLimpiarLayout.createSequentialGroup()
                .addComponent(lblLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel3.add(btnLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 110, 120, -1));

        btnActualizar.setBackground(new java.awt.Color(255, 176, 199));

        lblActualizar.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        lblActualizar.setForeground(new java.awt.Color(255, 255, 255));
        lblActualizar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblActualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/grafica/Imagenes/icons8_refresh_20px.png"))); // NOI18N
        lblActualizar.setText("ACTUALIZAR");
        lblActualizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblActualizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblActualizarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblActualizarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblActualizarMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnActualizarLayout = new javax.swing.GroupLayout(btnActualizar);
        btnActualizar.setLayout(btnActualizarLayout);
        btnActualizarLayout.setHorizontalGroup(
            btnActualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblActualizar, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
        );
        btnActualizarLayout.setVerticalGroup(
            btnActualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnActualizarLayout.createSequentialGroup()
                .addComponent(lblActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel3.add(btnActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 180, 120, -1));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 70, 150, 260));

        jPanel9.setBackground(new java.awt.Color(21, 47, 62));

        lblTitulo5.setBackground(new java.awt.Color(0, 0, 0));
        lblTitulo5.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        lblTitulo5.setForeground(new java.awt.Color(255, 255, 255));
        lblTitulo5.setText("Gestión de Usuarios");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 450, Short.MAX_VALUE)
            .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel9Layout.createSequentialGroup()
                    .addGap(0, 117, Short.MAX_VALUE)
                    .addComponent(lblTitulo5)
                    .addGap(0, 117, Short.MAX_VALUE)))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
            .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel9Layout.createSequentialGroup()
                    .addGap(0, 5, Short.MAX_VALUE)
                    .addComponent(lblTitulo5)
                    .addGap(0, 6, Short.MAX_VALUE)))
        );

        jPanel1.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 450, 40));

        jPanel7.setBackground(new java.awt.Color(4, 224, 190));

        lblAcciones.setBackground(new java.awt.Color(255, 126, 164));
        lblAcciones.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        lblAcciones.setForeground(new java.awt.Color(255, 255, 255));
        lblAcciones.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAcciones.setText("Acciones");
        lblAcciones.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lblAcciones.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblAccionesMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblAccionesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblAccionesMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblAcciones, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblAcciones, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 30, 150, 40));

        jPanel4.setBackground(new java.awt.Color(21, 47, 62));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnModificar.setBackground(new java.awt.Color(255, 77, 123));

        lblModificar.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        lblModificar.setForeground(new java.awt.Color(255, 255, 255));
        lblModificar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblModificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/grafica/Imagenes/icons8_edit_20px_2.png"))); // NOI18N
        lblModificar.setText("MODIFICAR");
        lblModificar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblModificar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblModificarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblModificarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblModificarMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnModificarLayout = new javax.swing.GroupLayout(btnModificar);
        btnModificar.setLayout(btnModificarLayout);
        btnModificarLayout.setHorizontalGroup(
            btnModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblModificar, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
        );
        btnModificarLayout.setVerticalGroup(
            btnModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnModificarLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel4.add(btnModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 110, -1));

        btnEliminar.setBackground(new java.awt.Color(255, 77, 123));

        lblEliminar.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        lblEliminar.setForeground(new java.awt.Color(255, 255, 255));
        lblEliminar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/grafica/Imagenes/icons8_minus_20px.png"))); // NOI18N
        lblEliminar.setText("ELIMINAR");
        lblEliminar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblEliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblEliminarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblEliminarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblEliminarMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnEliminarLayout = new javax.swing.GroupLayout(btnEliminar);
        btnEliminar.setLayout(btnEliminarLayout);
        btnEliminarLayout.setHorizontalGroup(
            btnEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
        );
        btnEliminarLayout.setVerticalGroup(
            btnEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnEliminarLayout.createSequentialGroup()
                .addComponent(lblEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel4.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 110, -1));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 335, 150, 265));

        jPanel14.setBackground(new java.awt.Color(4, 224, 190));

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 150, Short.MAX_VALUE)
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 330, 150, 5));

        jPanel10.setBackground(new java.awt.Color(21, 47, 62));

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 360, Short.MAX_VALUE)
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 30, 360, 40));

        btnAtras.setBackground(new java.awt.Color(42, 72, 89));

        lblAtras.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        lblAtras.setForeground(new java.awt.Color(255, 255, 255));
        lblAtras.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAtras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/grafica/Imagenes/icons8_left_20px.png"))); // NOI18N
        lblAtras.setText("ATRÁS");
        lblAtras.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblAtras.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblAtrasMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblAtrasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblAtrasMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnAtrasLayout = new javax.swing.GroupLayout(btnAtras);
        btnAtras.setLayout(btnAtrasLayout);
        btnAtrasLayout.setHorizontalGroup(
            btnAtrasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblAtras, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
        );
        btnAtrasLayout.setVerticalGroup(
            btnAtrasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblAtras, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
        );

        jPanel1.add(btnAtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 560, -1, -1));

        BarraTitulo.setBackground(new java.awt.Color(231, 255, 255));
        BarraTitulo.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                BarraTituloMouseDragged(evt);
            }
        });
        BarraTitulo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BarraTituloMousePressed(evt);
            }
        });
        BarraTitulo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitulo.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(153, 153, 153));
        lblTitulo.setText("Almacén - Usuarios");
        BarraTitulo.add(lblTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 8, -1, -1));

        btnExit.setBackground(new java.awt.Color(231, 255, 255));
        btnExit.setForeground(new java.awt.Color(255, 255, 255));
        btnExit.setMaximumSize(new java.awt.Dimension(30, 30));
        btnExit.setMinimumSize(new java.awt.Dimension(30, 30));
        btnExit.setPreferredSize(new java.awt.Dimension(30, 30));
        btnExit.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtExit.setBackground(new java.awt.Color(51, 51, 51));
        txtExit.setFont(new java.awt.Font("Roboto Light", 1, 24)); // NOI18N
        txtExit.setForeground(new java.awt.Color(0, 0, 0));
        txtExit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtExit.setText("X");
        txtExit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtExitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtExitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtExitMouseExited(evt);
            }
        });
        btnExit.add(txtExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 35, 30));

        BarraTitulo.add(btnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(925, 0, 35, 30));

        lblIcono4.setBackground(new java.awt.Color(51, 51, 51));
        lblIcono4.setFont(new java.awt.Font("Roboto Light", 1, 24)); // NOI18N
        lblIcono4.setForeground(new java.awt.Color(0, 0, 0));
        lblIcono4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblIcono4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/grafica/Imagenes/Icono 15px.png"))); // NOI18N
        lblIcono4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        BarraTitulo.add(lblIcono4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 35, 30));

        jPanel1.add(BarraTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 960, -1));

        lblIcono3.setBackground(new java.awt.Color(51, 51, 51));
        lblIcono3.setFont(new java.awt.Font("Roboto Light", 1, 24)); // NOI18N
        lblIcono3.setForeground(new java.awt.Color(0, 0, 0));
        lblIcono3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblIcono3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/grafica/Imagenes/Icono 15px.png"))); // NOI18N
        lblIcono3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblIcono3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblIcono3MouseExited(evt);
            }
        });
        jPanel1.add(lblIcono3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 35, 30));

        lblIcono2.setBackground(new java.awt.Color(51, 51, 51));
        lblIcono2.setFont(new java.awt.Font("Roboto Light", 1, 24)); // NOI18N
        lblIcono2.setForeground(new java.awt.Color(0, 0, 0));
        lblIcono2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblIcono2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/grafica/Imagenes/Icono 155 px.png"))); // NOI18N
        lblIcono2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.add(lblIcono2, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 380, 155, 157));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 960, 610));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        if (txtBuscador.getText().isEmpty()) {
            txtBuscador.setText("Ingresar C.I empleado...");
            txtBuscador.setForeground(new Color(204, 204, 204));
        }
    }//GEN-LAST:event_formMouseClicked

    private void lblCrearMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCrearMouseClicked
        String nombreUsuario = txtNuevo_Usuario.getText();
        String contrasenia = txtContrasenia.getText();
        String confirmContrasenia = txtConfirmarContrasenia.getText();
        String idEmpleado = txtIdEmpleado.getText();
        String tipoUsuario = null;

        int selecTipoUsuario = cboTipo_Usuario.getSelectedIndex();

        if (lblCrear.isEnabled()) {
            if (nombreUsuario.isEmpty() || contrasenia.isEmpty() || confirmContrasenia.isEmpty() || idEmpleado.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Verifique los campos obligatorios.");
            } else if (!txtContrasenia.getText().equals(txtConfirmarContrasenia.getText())) {
                JOptionPane.showMessageDialog(this, "Las contraseñas no coinciden.");
            } else if (selecTipoUsuario == 0) {
                JOptionPane.showMessageDialog(this, "Seleccione el tipo de usuario...");
            } else if (selecTipoUsuario == 1) {
                tipoUsuario = "Adm";
                try {
                    if (Sistema.getInstance().crearUsuario(nombreUsuario, contrasenia, idEmpleado, tipoUsuario)) {
                        JOptionPane.showMessageDialog(this, "¡Usuario creado exitósamente!");
                    } else {
                        JOptionPane.showMessageDialog(this, "Error! Posibles causas: 1) El usuario ya existe. 2) El empleado ya tiene usuario creado. 3) El empleado no existe.");
                    }
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(Usuarios.class.getName()).log(Level.SEVERE, null, ex);
                } catch (SQLException ex) {
                    Logger.getLogger(Usuarios.class.getName()).log(Level.SEVERE, null, ex);
                } catch (IOException ex) {
                    Logger.getLogger(Usuarios.class.getName()).log(Level.SEVERE, null, ex);
                }
            } else if (selecTipoUsuario == 2) {
                tipoUsuario = "Ven";
                try {
                    if (Sistema.getInstance().crearUsuario(nombreUsuario, contrasenia, idEmpleado, tipoUsuario)) {
                        JOptionPane.showMessageDialog(this, "¡Usuario creado exitósamente!");
                    } else {
                        JOptionPane.showMessageDialog(this, "Error! Posibles causas: 1) El usuario ya existe. 2) El empleado ya tiene usuario creado. 3) El empleado no existe.");
                    }
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(Usuarios.class.getName()).log(Level.SEVERE, null, ex);
                } catch (SQLException ex) {
                    Logger.getLogger(Usuarios.class.getName()).log(Level.SEVERE, null, ex);
                } catch (IOException ex) {
                    Logger.getLogger(Usuarios.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            try {
                tbeListado_Usuarios.setModel(Sistema.getInstance().mostrarListadoUsuarios());
            } catch (SQLException ex) {
                Logger.getLogger(Usuarios.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(Usuarios.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(Usuarios.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_lblCrearMouseClicked

    private void lblCrearMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCrearMouseEntered
        if (lblCrear.isEnabled()) {
            btnCrear.setBackground(new Color(255, 147, 178));
        }
    }//GEN-LAST:event_lblCrearMouseEntered

    private void lblCrearMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCrearMouseExited
        if (lblCrear.isEnabled()) {
            btnCrear.setBackground(new Color(255, 77, 123));
        }
    }//GEN-LAST:event_lblCrearMouseExited

    private void lblLimpiarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLimpiarMouseClicked
        txtNuevo_Usuario.setText("");
        txtContrasenia.setText("");
        txtConfirmarContrasenia.setText("");
        cboTipo_Usuario.setSelectedIndex(0);
        txtIdEmpleado.setText("");
        txtNuevo_Usuario.requestFocus();
        btnCrear.setEnabled(true);
        lblCrear.setEnabled(true);
        btnCrear.setBackground(new Color(255, 77, 123));
        btnActualizar.setEnabled(false);
        lblActualizar.setEnabled(false);
        btnActualizar.setBackground(new Color(255, 176, 199));
        txtIdEmpleado.setEnabled(true);
    }//GEN-LAST:event_lblLimpiarMouseClicked

    private void lblLimpiarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLimpiarMouseEntered
        btnLimpiar.setBackground(new Color(255, 147, 178));
    }//GEN-LAST:event_lblLimpiarMouseEntered

    private void lblLimpiarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLimpiarMouseExited
        btnLimpiar.setBackground(new Color(255, 77, 123));
    }//GEN-LAST:event_lblLimpiarMouseExited

    private void lblActualizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblActualizarMouseClicked
        String nombreUsuario = txtNuevo_Usuario.getText();
        String contrasenia = txtContrasenia.getText();
        String confirmContrasenia = txtConfirmarContrasenia.getText();
        String idEmpleado = txtIdEmpleado.getText();
        String tipoUsuario = null;
        int selecTipoUsuario = cboTipo_Usuario.getSelectedIndex();
        if (lblActualizar.isEnabled()) {
            if (nombreUsuario.isEmpty() || txtIdEmpleado.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Verifique los campos obligatorios.");
            } else if (!txtContrasenia.getText().equals(txtConfirmarContrasenia.getText())) {
                JOptionPane.showMessageDialog(this, "Las contraseñas no coinciden.");
            } else if (selecTipoUsuario == 0) {
                JOptionPane.showMessageDialog(this, "Seleccione el tipo de usuario...");
            } else if (selecTipoUsuario == 1) {
                tipoUsuario = "Adm";
                try {
                    if (Sistema.getInstance().actualizarUsuario(nombreUsuario, contrasenia, idEmpleado, tipoUsuario)) {
                        JOptionPane.showMessageDialog(this, "¡Se actualizó exitósamente!");
                    } else {
                        JOptionPane.showMessageDialog(this, "Error! Ya existe un usuario con el mismo nombre y/o el empleado no existe.");
                    }
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(Usuarios.class.getName()).log(Level.SEVERE, null, ex);
                } catch (SQLException ex) {
                    Logger.getLogger(Usuarios.class.getName()).log(Level.SEVERE, null, ex);
                } catch (IOException ex) {
                    Logger.getLogger(Usuarios.class.getName()).log(Level.SEVERE, null, ex);
                }
                txtNuevo_Usuario.setText("");
                txtContrasenia.setText("");
                txtConfirmarContrasenia.setText("");
                cboTipo_Usuario.setSelectedIndex(0);
                txtIdEmpleado.setText("");
                txtNuevo_Usuario.requestFocus();
                btnCrear.setEnabled(true);
                lblCrear.setEnabled(true);
                btnCrear.setBackground(new Color(255, 77, 123));
                btnActualizar.setEnabled(false);
                lblActualizar.setEnabled(false);
                btnActualizar.setBackground(new Color(255, 176, 199));
                txtIdEmpleado.setEnabled(true);
                tbeListado_Usuarios.setEnabled(true);
            } else if (selecTipoUsuario == 2) {
                tipoUsuario = "Ven";
                try {
                    if (Sistema.getInstance().actualizarUsuario(nombreUsuario, contrasenia, idEmpleado, tipoUsuario)) {
                        JOptionPane.showMessageDialog(this, "¡Se actualizó exitósamente!");
                    } else {
                        JOptionPane.showMessageDialog(this, "Error! Ya existe un usuario con el mismo nombre y/o el empleado no existe.");
                    }
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(Usuarios.class.getName()).log(Level.SEVERE, null, ex);
                } catch (SQLException ex) {
                    Logger.getLogger(Usuarios.class.getName()).log(Level.SEVERE, null, ex);
                } catch (IOException ex) {
                    Logger.getLogger(Usuarios.class.getName()).log(Level.SEVERE, null, ex);
                }
                txtNuevo_Usuario.setText("");
                txtContrasenia.setText("");
                txtConfirmarContrasenia.setText("");
                cboTipo_Usuario.setSelectedIndex(0);
                txtIdEmpleado.setText("");
                txtNuevo_Usuario.requestFocus();
                btnCrear.setEnabled(true);
                lblCrear.setEnabled(true);
                btnCrear.setBackground(new Color(255, 77, 123));
                btnActualizar.setEnabled(false);
                lblActualizar.setEnabled(false);
                btnActualizar.setBackground(new Color(255, 176, 199));
                txtIdEmpleado.setEnabled(true);
                tbeListado_Usuarios.setEnabled(true);
            }

            try {
                tbeListado_Usuarios.setModel(Sistema.getInstance().mostrarListadoUsuarios());
            } catch (SQLException ex) {
                Logger.getLogger(Usuarios.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(Usuarios.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(Usuarios.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_lblActualizarMouseClicked

    private void lblActualizarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblActualizarMouseEntered
        if (lblActualizar.isEnabled()) {
            btnActualizar.setBackground(new Color(255, 147, 178));
        }
    }//GEN-LAST:event_lblActualizarMouseEntered

    private void lblActualizarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblActualizarMouseExited
        if (lblActualizar.isEnabled()) {
            btnActualizar.setBackground(new Color(255, 77, 123));
        }
    }//GEN-LAST:event_lblActualizarMouseExited

    private void txtBuscadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscadorActionPerformed

    }//GEN-LAST:event_txtBuscadorActionPerformed

    private void txtBuscadorMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtBuscadorMousePressed
        if (txtBuscador.getText().equals("Ingresar C.I empleado...")) {
            txtBuscador.setText("");
            txtBuscador.setForeground(Color.black);
        }
    }//GEN-LAST:event_txtBuscadorMousePressed

    private void lblModificarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblModificarMouseClicked

        int filaSeleccionada = tbeListado_Usuarios.getSelectedRow();

        if (filaSeleccionada == -1) {
            JOptionPane.showMessageDialog(this, "Seleccione el usuario que desea modificar...");
        } else {
            btnCrear.setEnabled(false);
            lblCrear.setEnabled(false);
            btnCrear.setBackground(new Color(255, 176, 199));
            btnActualizar.setEnabled(true);
            lblActualizar.setEnabled(true);
            btnActualizar.setBackground(new Color(255, 77, 123));
            txtNuevo_Usuario.setText(String.valueOf(tbeListado_Usuarios.getValueAt(filaSeleccionada, 2)));
            txtContrasenia.setText("");
            txtConfirmarContrasenia.setText("");
            txtIdEmpleado.setText(String.valueOf(tbeListado_Usuarios.getValueAt(filaSeleccionada, 1)));
            txtIdEmpleado.setEnabled(false);
            if (String.valueOf(tbeListado_Usuarios.getValueAt(filaSeleccionada, 3)).equalsIgnoreCase("Administrador")) {
                cboTipo_Usuario.setSelectedIndex(1);
            } else if (String.valueOf(tbeListado_Usuarios.getValueAt(filaSeleccionada, 3)).equalsIgnoreCase("Vendedor")) {
                cboTipo_Usuario.setSelectedIndex(2);
            }
            tbeListado_Usuarios.setEnabled(false);
        }
    }//GEN-LAST:event_lblModificarMouseClicked

    private void lblModificarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblModificarMouseEntered
        btnModificar.setBackground(new Color(255, 147, 178));
    }//GEN-LAST:event_lblModificarMouseEntered

    private void lblModificarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblModificarMouseExited
        btnModificar.setBackground(new Color(255, 77, 123));
    }//GEN-LAST:event_lblModificarMouseExited

    private void lblEliminarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblEliminarMouseClicked
        int filaSeleccionada = tbeListado_Usuarios.getSelectedRow();
        String idUsuario = null;
        String nombreUsuario = null;
        String tipoUsuario = null;

        if (filaSeleccionada == -1) {
            JOptionPane.showMessageDialog(this, "Seleccione el usuario que desea eliminar...");
        } else {
            idUsuario = String.valueOf(tbeListado_Usuarios.getValueAt(filaSeleccionada, 0));
            nombreUsuario = (String.valueOf(tbeListado_Usuarios.getValueAt(filaSeleccionada, 2)));
            tipoUsuario = (String.valueOf(tbeListado_Usuarios.getValueAt(filaSeleccionada, 3)));
            int confirmacion = JOptionPane.showConfirmDialog(null, "¿Desea eliminar el usuario: " + nombreUsuario + ", Tipo: " + tipoUsuario + "?", "Confirmación de eliminación...", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
            if (confirmacion == 0) {
                try {
                    if (Sistema.getInstance().eliminarUsuario(idUsuario)) {
                        JOptionPane.showMessageDialog(this, "Se ha elmininado correctamente.");
                    } else {
                        JOptionPane.showMessageDialog(this, "Se ha producido un error, intente nuevamente.");
                    }
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(Usuarios.class.getName()).log(Level.SEVERE, null, ex);
                } catch (SQLException ex) {
                    Logger.getLogger(Usuarios.class.getName()).log(Level.SEVERE, null, ex);
                } catch (IOException ex) {
                    Logger.getLogger(Usuarios.class.getName()).log(Level.SEVERE, null, ex);
                }
                try {
                    tbeListado_Usuarios.setModel(Sistema.getInstance().mostrarListadoUsuarios());
                } catch (SQLException ex) {
                    Logger.getLogger(Usuarios.class.getName()).log(Level.SEVERE, null, ex);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(Usuarios.class.getName()).log(Level.SEVERE, null, ex);
                } catch (IOException ex) {
                    Logger.getLogger(Usuarios.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
    }//GEN-LAST:event_lblEliminarMouseClicked

    private void lblEliminarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblEliminarMouseEntered
        btnEliminar.setBackground(new Color(255, 147, 178));
    }//GEN-LAST:event_lblEliminarMouseEntered

    private void lblEliminarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblEliminarMouseExited
        btnEliminar.setBackground(new Color(255, 77, 123));
    }//GEN-LAST:event_lblEliminarMouseExited

    private void lblBuscarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBuscarMouseClicked
        String cedula = null;
        if (txtBuscador.getText().isEmpty() || txtBuscador.getText().equals("Ingresar C.I empleado...")) {
            JOptionPane.showMessageDialog(this, "Ingrese el número de C.I para buscar empleado...");
        } else if (txtBuscador.getText().length() == 8) {
            try {
                int cedulaNumerica = Integer.parseInt(txtBuscador.getText());
                cedula = String.valueOf(cedulaNumerica);
                lblIdEmpleado.setText("" + Sistema.getInstance().buscarEmpleadoPorCedula(cedula));
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "El campo debe ser numérico");
            } catch (SQLException ex) {
                Logger.getLogger(Usuarios.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(Usuarios.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(Usuarios.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            JOptionPane.showMessageDialog(this, "C.I inválida. Verifique nuevamente...");
        }
    }//GEN-LAST:event_lblBuscarMouseClicked

    private void lblBuscarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBuscarMouseEntered
        btnBuscar.setBackground(new Color(255, 147, 178));
    }//GEN-LAST:event_lblBuscarMouseEntered

    private void lblBuscarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBuscarMouseExited
        btnBuscar.setBackground(new Color(255, 77, 123));
    }//GEN-LAST:event_lblBuscarMouseExited

    private void lblLimpiarBuscadorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLimpiarBuscadorMouseClicked
        txtBuscador.setText("");
        lblIdEmpleado.setText("ID");
        txtBuscador.requestFocus();
    }//GEN-LAST:event_lblLimpiarBuscadorMouseClicked

    private void lblLimpiarBuscadorMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLimpiarBuscadorMouseEntered
        btnLimpiarBuscador.setBackground(new Color(255, 147, 178));
    }//GEN-LAST:event_lblLimpiarBuscadorMouseEntered

    private void lblLimpiarBuscadorMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLimpiarBuscadorMouseExited
        btnLimpiarBuscador.setBackground(new Color(255, 77, 123));
    }//GEN-LAST:event_lblLimpiarBuscadorMouseExited

    private void lblAccionesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAccionesMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblAccionesMouseClicked

    private void lblAccionesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAccionesMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_lblAccionesMouseEntered

    private void lblAccionesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAccionesMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_lblAccionesMouseExited

    private void lblAtrasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAtrasMouseClicked
        MenuAdministrador menu = new MenuAdministrador(usuario);
        menu.setVisible(true);
        dispose();
    }//GEN-LAST:event_lblAtrasMouseClicked

    private void lblAtrasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAtrasMouseEntered
        btnAtras.setBackground(new Color(55, 86, 103));
    }//GEN-LAST:event_lblAtrasMouseEntered

    private void lblAtrasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAtrasMouseExited
        btnAtras.setBackground(new Color(42, 72, 89));
    }//GEN-LAST:event_lblAtrasMouseExited

    private void txtExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtExitMouseClicked
        MenuAdministrador menu = new MenuAdministrador(usuario);
        menu.setVisible(true);
        dispose();
    }//GEN-LAST:event_txtExitMouseClicked

    private void txtExitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtExitMouseEntered
        btnExit.setBackground(new Color(230, 0, 0));
        txtExit.setForeground(Color.white);
    }//GEN-LAST:event_txtExitMouseEntered

    private void txtExitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtExitMouseExited
        btnExit.setBackground(new Color(231, 255, 255));
        txtExit.setForeground(Color.black);
    }//GEN-LAST:event_txtExitMouseExited

    private void BarraTituloMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BarraTituloMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_BarraTituloMouseDragged

    private void BarraTituloMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BarraTituloMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_BarraTituloMousePressed

    private void lblIcono3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblIcono3MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_lblIcono3MouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Usuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Usuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Usuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Usuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Usuarios().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(Usuarios.class.getName()).log(Level.SEVERE, null, ex);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(Usuarios.class.getName()).log(Level.SEVERE, null, ex);
                } catch (IOException ex) {
                    Logger.getLogger(Usuarios.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BarraTitulo;
    private javax.swing.JPanel Buscador;
    private javax.swing.JPanel IdEmpleado;
    private javax.swing.JPanel ListadoUsuarios;
    private javax.swing.JPanel RegistroUsuario;
    private javax.swing.JPanel btnActualizar;
    private javax.swing.JPanel btnAtras;
    private javax.swing.JPanel btnBuscar;
    private javax.swing.JPanel btnCrear;
    private javax.swing.JPanel btnEliminar;
    private javax.swing.JPanel btnExit;
    private javax.swing.JPanel btnLimpiar;
    private javax.swing.JPanel btnLimpiarBuscador;
    private javax.swing.JPanel btnModificar;
    private javax.swing.JComboBox<String> cboTipo_Usuario;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAcciones;
    private javax.swing.JLabel lblActualizar;
    private javax.swing.JLabel lblAtras;
    private javax.swing.JLabel lblBuscar;
    private javax.swing.JLabel lblCrear;
    private javax.swing.JLabel lblEliminar;
    private javax.swing.JLabel lblIcono2;
    private javax.swing.JLabel lblIcono3;
    private javax.swing.JLabel lblIcono4;
    private javax.swing.JLabel lblIdEmpleado;
    private javax.swing.JLabel lblLimpiar;
    private javax.swing.JLabel lblLimpiarBuscador;
    private javax.swing.JLabel lblModificar;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblTitulo1;
    private javax.swing.JLabel lblTitulo2;
    private javax.swing.JLabel lblTitulo3;
    private javax.swing.JLabel lblTitulo5;
    private javax.swing.ButtonGroup rbgBuscar;
    private javax.swing.JTable tbeListado_Usuarios;
    private javax.swing.JTextField txtBuscador;
    private javax.swing.JTextField txtConfirmarContrasenia;
    private javax.swing.JTextField txtContrasenia;
    private javax.swing.JLabel txtExit;
    private javax.swing.JTextField txtIdEmpleado;
    private javax.swing.JTextField txtNuevo_Usuario;
    // End of variables declaration//GEN-END:variables
}
